use crate::database::WarehousedItem;
// resolve_excel_path no longer needed — NameResolver handles names
use rusqlite::params;
use std::time::Instant;
use crate::AppState;
use serde::{Deserialize, Serialize};
use tauri::State;

const DEFAULT_WAREHOUSE_PAGE: &str = "默认收藏";

/// Simplified warehouse item for frontend display
#[derive(Debug, Serialize, Deserialize)]
pub struct WarehouseItemResult {
    pub id: String,
    pub item_code: String,
    pub item_name: String,
    pub item_kind: String,
    pub quality: Option<String>,
    pub quantity: u32,
    pub page_name: String,
    pub imported_at: String,
    pub tags: String,
    pub notes: String,
    /// Inventory footprint width (cells). Frontend uses this to render the drag
    /// preview and the placement validator; without it `width × scaledCell` is
    /// `NaN` and the CSS layout collapses.
    pub inv_width: i32,
    /// Inventory footprint height (cells). See `inv_width` for rationale.
    pub inv_height: i32,
    /// Tooltip lines for hover/display, generated by TooltipFormatter::stash_tooltip.
    /// Empty when tooltip data is unavailable (old fallback path).
    pub tooltip_lines: Vec<String>,
    /// 结构化 tooltip 数据（与角色页 build_tooltip_from_stats 同款分类：
    /// 白字基础/蓝字词缀/符文/套装分色 + 镶嵌区块）。
    /// 前端优先消费此字段, None 时降级到 tooltip_lines。
    pub tooltip: Option<crate::commands::character::TooltipData>,
}

/// Default-page lookup result for an item. Returned by `warehouse_resolve_default`.
/// `effective` is the resolved fallback chain result — useful for the frontend
/// to render "当前默认页: X" without doing two round trips.
#[derive(Debug, Serialize, Deserialize)]
pub struct DefaultPageInfo {
    pub item_code: String,
    pub code_default: Option<String>,
    pub item_default: Option<String>,
    pub effective: Option<String>,
}

fn localize_warehouse_items(
    db: &crate::database::Database,
    items: Vec<WarehousedItem>,
) -> Vec<WarehouseItemResult> {
    let language = db
        .get_config("language")
        .ok()
        .flatten()
        .unwrap_or_else(|| "enUS".to_string());
    let profile_id = crate::commands::config::get_active_profile_id(db).unwrap_or(0);
    let conn_ref = db.get_connection();

    if profile_id > 0 {
        let resolver = crate::resource::get_cached_resolver(conn_ref, profile_id);
        let quality_u8 = |q: &Option<String>| -> Option<u8> {
            match q.as_deref() {
                Some("unique") => Some(7),
                Some("rare") => Some(6),
                Some("set") => Some(5),
                Some("magic") => Some(4),
                Some("superior") => Some(3),
                Some("low") => Some(1),
                _ => None,
            }
        };
        items
            .into_iter()
            .map(|i| {
                let mut resolved = resolver.resolve(conn_ref, &i.item_code, None, None, None, &language);
                // 符文之语名字: 从 item_json 的 socketed_items 匹配 runeword,
                // 与角色页 build_stored_item_summary 一致 (底材名[精神])
                let socketed: Vec<crate::protocol::common::Item> = serde_json::from_str::<serde_json::Value>(&i.item_json)
                    .ok()
                    .and_then(|j| j.get("socketed_items").cloned())
                    .and_then(|v| serde_json::from_value(v).ok())
                    .unwrap_or_default();
                let runes: Vec<&str> = socketed.iter().map(|s| s.code.as_str()).collect();
                if !runes.is_empty()
                    && let Some(rw_en) = crate::data::runewords::match_runeword(&runes) {
                    if language == "enUS" {
                        resolved.display_name = format!("{} [{}]", resolved.display_name, rw_en);
                    } else if let Some(rw_zh) = crate::data::runewords::match_runeword_zh(&runes) {
                        resolved.display_name = format!("{}[{}]", resolved.display_name, rw_zh);
                    } else {
                        resolved.display_name = format!("{} [{}]", resolved.display_name, rw_en);
                    }
                }
                // Parse stat_lists from item_json (stored during deposit)
                let stat_lists: Vec<crate::protocol::common::stat_list::StatList> = serde_json::from_str::<serde_json::Value>(&i.item_json)
                    .ok()
                    .and_then(|j| j.get("stat_lists").cloned())
                    .and_then(|sl| serde_json::from_value(sl).ok())
                    .unwrap_or_default();
                let stats: Vec<crate::protocol::common::ItemStat> =
                    stat_lists.iter().flat_map(|sl| sl.stats.iter().cloned()).collect();
                let tooltip_lines = crate::resource::TooltipFormatter::stash_tooltip(
                    &resolved.display_name,
                    &resolved.name_en,
                    &i.item_code,
                    &i.item_kind,
                    quality_u8(&i.quality),
                    i.quantity,
                    &language,
                    &stats,
                );
                // 结构化 tooltip: 与角色页 build_tooltip_from_stats 同款分类
                // (白字基础/蓝字词缀/符文/套装分色 + 镶嵌区块), 收藏页 hover 与角色页一致
                let quality_byte = quality_u8(&i.quality);
                let stats_cat = crate::commands::character::categorize_item_stats(
                    quality_byte.unwrap_or(2),
                    !runes.is_empty(),
                    &stat_lists,
                );
                let mut tooltip = crate::commands::character::build_tooltip_from_stats(
                    &stats_cat, &language, Some(conn_ref), profile_id,
                );
                // 底材基础行 (对齐角色页 build_stored_item_summary)
                // 实际防御优先: item_json 存的实际 defense;0/缺失时回退底材区间
                let stored_defense: u16 = serde_json::from_str::<serde_json::Value>(&i.item_json)
                    .ok()
                    .and_then(|j| j.get("defense").cloned())
                    .and_then(|v| v.as_u64().map(|n| n as u16))
                    .unwrap_or(0);
                if let Some(def) = crate::data::items_base::armor_stats(&i.item_code) {
                    if stored_defense > 0 {
                        tooltip.base_stats.insert(0, format!("防御: {}", stored_defense));
                    } else if def.minac > 0 || def.maxac > 0 {
                        tooltip.base_stats.insert(0, format!("防御: {}-{}", def.minac, def.maxac));
                    }
                    if def.levelreq > 0 { tooltip.base_stats.push(format!("需要等级: {}", def.levelreq)); }
                    if def.reqstr > 0 { tooltip.base_stats.push(format!("需要力量: {}", def.reqstr)); }
                    if def.reqdex > 0 { tooltip.base_stats.push(format!("需要敏捷: {}", def.reqdex)); }
                }
                // 盾牌 smite 伤害 (含圣骑士盾)
                if let Some((smin, smax)) = crate::data::items_base::shield_smite(&i.item_code) {
                    tooltip.base_stats.push(if smin == smax {
                        format!("盾击伤害: {}", smin)
                    } else {
                        format!("盾击伤害: {}-{}", smin, smax)
                    });
                }
                if let Some(wpn) = crate::data::items_base::weapon_stats(&i.item_code) {
                    let (dmin, dmax) = wpn.display_damage();
                    if dmin > 0 || dmax > 0 {
                        tooltip.base_stats.push(if dmin == dmax {
                            format!("攻击力: {}", dmin)
                        } else {
                            format!("攻击力: {}-{}", dmin, dmax)
                        });
                    }
                    if wpn.levelreq > 0 { tooltip.base_stats.push(format!("需要等级: {}", wpn.levelreq)); }
                    if wpn.reqstr > 0 { tooltip.base_stats.push(format!("需要力量: {}", wpn.reqstr)); }
                    if wpn.reqdex > 0 { tooltip.base_stats.push(format!("需要敏捷: {}", wpn.reqdex)); }
                }
                // 孔位 + 镶嵌 (对齐角色页)
                if !socketed.is_empty() {
                    tooltip.sockets = Some(crate::commands::character::SocketsInfo {
                        count: socketed.len() as u8,
                        items: socketed.iter().map(|s| crate::commands::character::SocketedItemInfo {
                            code: s.code.clone(),
                            name_zh: None,
                            name_en: None,
                            quality: Some(s.quality.as_u8()).filter(|&q| (2..=8).contains(&q)),
                            amount: s.amount,
                        }).collect(),
                    });
                }
                WarehouseItemResult {
                    id: i.id,
                    item_code: i.item_code,
                    item_name: resolved.display_name,
                    item_kind: i.item_kind,
                    quality: i.quality,
                    quantity: i.quantity,
                    page_name: i.page_name,
                    imported_at: i.imported_at,
                    tags: i.tags,
                    notes: i.notes,
                    inv_width: i.inv_width,
                    inv_height: i.inv_height,
                    tooltip_lines,
                    tooltip: Some(tooltip),
                }
            })
            .collect()
    } else {
        items
            .into_iter()
            .map(|i| {
                let code = i.item_code.clone();
                let tooltip_lines = crate::resource::TooltipFormatter::stash_tooltip(
                    &code, &code, &code, &i.item_kind,
                    None, i.quantity, &language, &[],
                );
                WarehouseItemResult {
                    id: i.id,
                    item_code: code,
                    item_name: i.item_code,
                    item_kind: i.item_kind,
                    quality: i.quality,
                    quantity: i.quantity,
                    page_name: i.page_name,
                    imported_at: i.imported_at,
                    tags: i.tags,
                    notes: i.notes,
                    inv_width: i.inv_width,
                    inv_height: i.inv_height,
                    tooltip_lines,
                    tooltip: None,
                }
            })
            .collect()
    }
}

fn validate_page_name(input: &str) -> Result<String, String> {
    let name = input.trim();
    if name.is_empty() {
        return Err("收藏页名称不能为空".to_string());
    }
    if name.chars().count() > 64 {
        return Err("收藏页名称不能超过 64 个字符".to_string());
    }
    if name.chars().any(|ch| ch.is_control()) {
        return Err("收藏页名称不能包含控制字符".to_string());
    }
    Ok(name.to_string())
}

/// List all warehoused items (with localized names)
#[tauri::command]
pub fn warehouse_list(state: State<AppState>) -> Result<Vec<WarehouseItemResult>, String> {
    let db = state.db.lock().map_err(|e| e.to_string())?;
    let active_profile_key = crate::commands::config::get_active_profile_key(&db).unwrap_or_default();
    let items = if !active_profile_key.is_empty() {
        db.warehouse_list_by_profile(&active_profile_key)
            .or_else(|_| db.warehouse_list_all())
            .map_err(|e| e.to_string())?
    } else {
        db.warehouse_list_all().map_err(|e| e.to_string())?
    };
    Ok(localize_warehouse_items(&db, items))
}

#[tauri::command]
pub fn warehouse_list_pages(state: State<AppState>) -> Result<Vec<String>, String> {
    let db = state.db.lock().map_err(|e| e.to_string())?;
    let active_profile_key = crate::commands::config::get_active_profile_key(&db).unwrap_or_default();
    if !active_profile_key.is_empty() {
        return db
            .warehouse_list_pages_in_profile(&active_profile_key)
            .or_else(|_| db.warehouse_list_pages())
            .map_err(|e| e.to_string());
    }
    db.warehouse_list_pages().map_err(|e| e.to_string())
}

#[tauri::command]
pub fn warehouse_list_by_page(
    state: State<AppState>,
    page_name: String,
) -> Result<Vec<WarehouseItemResult>, String> {
    let db = state.db.lock().map_err(|e| e.to_string())?;
    let active_profile_key = crate::commands::config::get_active_profile_key(&db).unwrap_or_default();
    let items = if !active_profile_key.is_empty() {
        db.warehouse_list_by_page_in_profile(&active_profile_key, &page_name)
            .or_else(|_| db.warehouse_list_by_page(&page_name))
            .map_err(|e| e.to_string())?
    } else {
        db.warehouse_list_by_page(&page_name).map_err(|e| e.to_string())?
    };
    Ok(localize_warehouse_items(&db, items))
}

#[tauri::command]
pub fn warehouse_update_meta(
    state: State<AppState>,
    item_id: String,
    page_name: String,
    tags: String,
    notes: String,
) -> Result<(), String> {
    let validated_page_name = validate_page_name(&page_name)?;
    let db = state.db.lock().map_err(|e| e.to_string())?;
    let active_profile_key = crate::commands::config::get_active_profile_key(&db).unwrap_or_default();
    let updated = if !active_profile_key.is_empty() {
        db.warehouse_update_meta_in_profile(&active_profile_key, &item_id, &validated_page_name, &tags, &notes)
            .or_else(|_| db.warehouse_update_meta(&item_id, &validated_page_name, &tags, &notes))
            .map_err(|e| e.to_string())?
    } else {
        db.warehouse_update_meta(&item_id, &validated_page_name, &tags, &notes)
            .map_err(|e| e.to_string())?
    };
    if !updated {
        return Err("Warehouse item not found in active profile".to_string());
    }
    Ok(())
}

#[tauri::command]
pub fn warehouse_rename_page(
    state: State<AppState>,
    old_page_name: String,
    new_page_name: String,
) -> Result<(), String> {
    if old_page_name.trim() == DEFAULT_WAREHOUSE_PAGE {
        return Err("默认收藏不可重命名".to_string());
    }
    let validated_old_name = validate_page_name(&old_page_name)?;
    let validated_new_name = validate_page_name(&new_page_name)?;
    let db = state.db.lock().map_err(|e| e.to_string())?;
    let active_profile_key = crate::commands::config::get_active_profile_key(&db).unwrap_or_default();
    let conn = db.get_connection();

    conn.execute_batch("BEGIN IMMEDIATE TRANSACTION").map_err(|e| e.to_string())?;
    let result = if !active_profile_key.is_empty() {
        conn.execute(
            "UPDATE warehouse_items SET page_name = ?1 WHERE profile_key = ?2 AND page_name = ?3",
            params![validated_new_name, active_profile_key, validated_old_name],
        )
    } else {
        conn.execute(
            "UPDATE warehouse_items SET page_name = ?1 WHERE page_name = ?2",
            params![validated_new_name, validated_old_name],
        )
    };

    match result {
        Ok(_) => {
            conn.execute_batch("COMMIT").map_err(|e| e.to_string())?;
            Ok(())
        }
        Err(e) => {
            let _ = conn.execute_batch("ROLLBACK");
            Err(e.to_string())
        }
    }
}

#[tauri::command]
pub fn warehouse_delete_page(
    state: State<AppState>,
    page_name: String,
    delete_items: bool,
) -> Result<(), String> {
    if page_name.trim() == DEFAULT_WAREHOUSE_PAGE {
        return Err("默认收藏不可删除".to_string());
    }
    let validated_page_name = validate_page_name(&page_name)?;
    let db = state.db.lock().map_err(|e| e.to_string())?;
    let active_profile_key = crate::commands::config::get_active_profile_key(&db).unwrap_or_default();
    let conn = db.get_connection();

    conn.execute_batch("BEGIN IMMEDIATE TRANSACTION").map_err(|e| e.to_string())?;
    let result = if delete_items {
        if !active_profile_key.is_empty() {
            conn.execute(
                "DELETE FROM warehouse_items WHERE profile_key = ?1 AND page_name = ?2",
                params![active_profile_key, validated_page_name],
            )
        } else {
            conn.execute(
                "DELETE FROM warehouse_items WHERE page_name = ?1",
                params![validated_page_name],
            )
        }
    } else if !active_profile_key.is_empty() {
        conn.execute(
            "UPDATE warehouse_items SET page_name = ?1 WHERE profile_key = ?2 AND page_name = ?3",
            params![DEFAULT_WAREHOUSE_PAGE, active_profile_key, validated_page_name],
        )
    } else {
        conn.execute(
            "UPDATE warehouse_items SET page_name = ?1 WHERE page_name = ?2",
            params![DEFAULT_WAREHOUSE_PAGE, validated_page_name],
        )
    };

    match result {
        Ok(_) => {
            conn.execute_batch("COMMIT").map_err(|e| e.to_string())?;
            Ok(())
        }
        Err(e) => {
            let _ = conn.execute_batch("ROLLBACK");
            Err(e.to_string())
        }
    }
}

/// Normalize a raw item's mode/location/position for stash placement.
///
/// Overwrites mode → Stored, location → None, and px/py to the desired
/// stash grid position, while preserving the pg (page) field.
///
/// Bit layout (from item start):
///   bits 0-31:   flags (u32)
///   bits 32-34:  version (3 bits)
///   bits 35-37:  mode (3 bits) — overwritten to Stored(0)
///   bits 38-41:  location (4 bits) — overwritten to None(0)
///   bits 42-45:  px (4 bits) — set to position_x
///   bits 46-49:  py (4 bits) — set to position_y
///   bits 50-52:  pg (3 bits) — overwritten to SharedStash(6)
///   bits 53+:    Huffman code + body
///
/// For stackable stash items the game encodes quantity as `(py << 4) | px`;
/// for non-stackable items these are the grid position on the stash page.
fn update_item_position(raw_bits: &[u8], position_x: u8, position_y: u8, _new_amount: Option<u32>) -> Vec<u8> {
    use crate::protocol::d2i::legacy::{BitReader, BitWriter};

    // ★ Try to find the actual item start within raw_bits.
    // D2S-originated bits may have intra-byte padding (item starts at bit N%8).
    // Use try_parse_one to locate the true item header offset.
    let item_start_bit = {
        // Wrap raw_bits as JM data (prefix +64 byte zero header) for parse_jm_page
        let mut probe_buf = Vec::with_capacity(64 + raw_bits.len() + 4);
        probe_buf.extend_from_slice(&[0u8; 64]);
        probe_buf.extend_from_slice(b"JM");
        probe_buf.extend_from_slice(&[1u8, 0]); // count=1
        probe_buf.extend_from_slice(raw_bits);
        let parsed = crate::protocol::d2i::jm_reader::parse_jm_page(&probe_buf, 0, false);
        match parsed.first() {
            Some(pi) => {
                // item_start_bit = bit offset within raw_bits where the item header starts
                log::info!("[update_item_position] detected item_start_bit={} code={} x={} y={}",
                    pi.raw_bit_offset, pi.item.code, pi.item.x, pi.item.y);
                pi.raw_bit_offset
            }
            None => {
                log::warn!("[update_item_position] could not find item in raw_bits, assuming 0");
                0
            }
        }
    };

    let mut reader = BitReader::new(raw_bits);
    let mut writer = BitWriter::new(raw_bits.len() * 2);

    // Copy bits before item start unchanged (padding from extraction)
    for _ in 0..item_start_bit {
        if reader.remaining_bits() > 0 { writer.write_bit(reader.read_bit()); }
    }

    // Copy bits 0-34 unchanged (flags 32 + version 3)
    for _ in 0..35 {
        if reader.remaining_bits() > 0 { writer.write_bit(reader.read_bit()); }
    }

    // Write mode = Stored(0), 3 bits LSB-first
    for _ in 0..3 { writer.write_bit(0); }
    // Write location = None(0), 4 bits LSB-first
    for _ in 0..4 { writer.write_bit(0); }

    log::info!("[update_item_position] mode→Stored loc→None px={} py={} raw_bits={}B item_start_bit={}",
        position_x, position_y, raw_bits.len(), item_start_bit);

    // Write px (4 bits, LSB-first)
    for i in 0..4 {
        writer.write_bit((position_x >> i) & 1);
    }
    // Write py (4 bits, LSB-first)
    for i in 0..4 {
        writer.write_bit((position_y >> i) & 1);
    }

    // Write pg = MyStash(5), 3 bits LSB-first
    // ★ 游戏实际保存的共享仓库物品 pg=5（MyStash）——备份文件逐项验证过。
    //   写 6 会被游戏忽略（物品不显示）。Equipment items have pg=Equipped(0)
    //   which crashes D2R when placed in stash, 所以必须改写。
    for i in 0..3 { writer.write_bit((5u8 >> i) & 1); }

    // Skip old mode(3) + loc(4) + px(4) + py(4) + pg(3) = 18 bits in the reader
    for _ in 0..18 {
        reader.read_bit();
    }

    // Copy remaining bits unchanged
    while reader.remaining_bits() > 0 {
        writer.write_bit(reader.read_bit());
    }

    let result = writer.to_bytes();
    
    // Strip leading padding bytes (from item_start_bit offset) so the output
    // can be directly appended to JM data without shifting item alignment.
    let trim_bytes = item_start_bit / 8;
    let result = if trim_bytes > 0 && trim_bytes < result.len() {
        let mut trimmed = result[trim_bytes..].to_vec();
        // 补回 1 字节尾部填充（对齐测试文件）
        trimmed.push(0);
        log::info!("[update_item_position] stripped {} leading padding, padded trailing, output={}B", trim_bytes, trimmed.len());
        trimmed
    } else {
        result
    };
    log::info!("[update_item_position] output={}B", result.len());
    result
}


fn extract_item_bits(payload: &[u8], start_bit: usize, bit_len: usize) -> Result<Vec<u8>, String> {
    use crate::protocol::d2i::legacy::{BitReader, BitWriter};

    if start_bit + bit_len > payload.len() * 8 {
        return Err(format!(
            "Item bits out of range: start_bit={} bit_len={} payload_bits={}",
            start_bit,
            bit_len,
            payload.len() * 8
        ));
    }

    let mut reader = BitReader::new(payload);
    reader.seek(start_bit);

    let mut writer = BitWriter::new(bit_len + 8);
    for _ in 0..bit_len {
        if reader.remaining_bits() == 0 {
            return Err("Unexpected end of payload while extracting item bits".to_string());
        }
        writer.write_bit(reader.read_bit());
    }

    writer.align();
    Ok(writer.to_bytes())
}

/// Count actual items in a raw JM item bitstream.
fn count_items_in_jm_stream(data: &[u8]) -> usize {
    if data.is_empty() { return 0; }
    let mut buf = Vec::with_capacity(data.len() + 4);
    buf.extend_from_slice(b"JM");
    buf.extend_from_slice(&[0xFFu8, 0]);
    buf.extend_from_slice(data);
    let items = crate::protocol::d2i::parser::parse_item_stream_sequential(&buf, 0, false);
    log::info!("[withdraw] count_items_in_jm: {} items in {}B", items.len(), data.len());
    items.len()
}

fn restore_stash_from_backup(stash_path: &str, backup_path: &std::path::Path) -> Result<(), String> {
    std::fs::copy(backup_path, stash_path)
        .map(|_| ())
        .map_err(|e| format!("Failed to restore stash from backup: {}", e))
}


/// Deposit a stash item into the extended warehouse.
/// Deducts the item from the game stash and stores it in the database.
#[tauri::command]
pub fn warehouse_deposit(
    state: State<AppState>,
    stash_path: String,
    item_code: String,
    page_index: usize,
    position_x: u8,
    position_y: u8,
    quantity: u32,
    page_name: Option<String>,
) -> Result<(), String> {
    warehouse_deposit_inner(&state, stash_path, item_code, page_index, position_x, position_y, quantity, page_name)
}

/// Testable inner function: does the actual deposit work without tauri::State wrapper.
pub fn warehouse_deposit_inner(
    state: &AppState,
    stash_path: String,
    item_code: String,
    page_index: usize,
    position_x: u8,
    position_y: u8,
    quantity: u32,
    page_name: Option<String>,
) -> Result<(), String> {
    let _t0 = Instant::now();
    log::info!(
        "[deposit] ENTRY: stash_path={} item_code={} page_index={} pos=({},{}) quantity={}",
        stash_path, item_code, page_index, position_x, position_y, quantity
    );
    let stash_file = crate::core::MmapFile::open(&stash_path)
        .map_err(|e| { log::error!("[deposit] step1 mmap FAILED: {}", e); format!("Failed to read stash: {}", e) })?;
    let stash_data: &[u8] = stash_file.as_slice();
    log::info!("[deposit] step1: read stash OK, size={}B ({:.2?})", stash_data.len(), _t0.elapsed());
    let file = crate::protocol::d2i::parser::parse_file(stash_data)
        .map_err(|e| { log::error!("[deposit] step1b parse FAILED: {}", e); format!("Failed to parse stash: {}", e) })?;
    drop(stash_file);
    log::info!("[deposit] step1b: stash pages={} ({:.2?})", file.pages.len(), _t0.elapsed());
    for (i, p) in file.pages.iter().enumerate() {
        log::info!("[deposit]   page[{}]: is_stackable={} data_len={}", i, p.is_stackable, p.data.len());
    }
    let page = file.pages.get(page_index)
        .ok_or_else(|| { log::error!("[deposit] step2 page_index={} out of range (total={})", page_index, file.pages.len()); format!("Page {} not found", page_index) })?;
    log::info!("[deposit] step2: page found, is_stackable={} data_len={} ({:.2?})", page.is_stackable, page.data.len(), _t0.elapsed());
    let page_items: Vec<&crate::protocol::d2i::parser::ParsedItem> = file.items.iter()
        .filter(|pi| pi.page_index == page_index)
        .collect();
    log::info!("[deposit] step3: page has {} items ({:.2?})", page_items.len(), _t0.elapsed());
    let source_pi = if page.is_stackable {
        // Stackable page: x/y encodes quantity, not grid position.
        // Match by code only. If multiple stacks exist, picks the first.
        page_items.iter()
            .find(|pi| pi.item.code == item_code && pi.item.amount > 0)
    } else {
        page_items.iter()
            .find(|pi| pi.item.code == item_code && pi.item.amount > 0 && pi.item.x == position_x && pi.item.y == position_y)
    }
    .ok_or_else(|| {
        let pos_info = if page.is_stackable {
            "(stackable page, x/y encodes qty)".to_string()
        } else {
            format!("at ({},{})", position_x, position_y)
        };
        log::error!(
            "[deposit] step3b item '{}' NOT FOUND among {} page items {}",
            item_code, page_items.len(), pos_info
        );
        format!("Item '{}' not found on page {} {}", item_code, page_index, pos_info)
    })?;
    log::info!("[deposit] step3b: source item found: code={} amount={} pos=({},{}) simple={} raw_off={} raw_len={} ({:.2?})",
        source_pi.item.code, source_pi.item.amount, source_pi.item.x, source_pi.item.y,
        source_pi.item.flags.simple_item(), source_pi.raw_bit_offset, source_pi.raw_bit_length, _t0.elapsed());
    let item_data = &page.data[64..];
    let _socketed_count = source_pi.item.socketed_items.len();
    
    // Compute bit range to extract: parent + any socketed sub-items.
    // ★ 删除/提取区间必须覆盖 socket children：parse 的 raw_bit_length 只覆盖
    //   父物品，带镶嵌物的物品实际占用 = 父物品 + children（如 skp 56B + r04/r03
    //   = 110B）。若只删到 raw_end，children 会残留为孤儿字节，游戏解析错位。
    //   终点用下一个顶层物品边界（或页尾），天然覆盖 children 且不碰下一个物品。
    let (target_start_bit, target_bit_len) = {
        let next_item = page_items.iter()
            .filter(|pi| pi.raw_bit_offset > source_pi.raw_bit_offset)
            .min_by_key(|pi| pi.raw_bit_offset);
        let clamped_end = match next_item {
            Some(next) => next.raw_bit_offset,
            None => item_data[4..].len() * 8,
        };
        (source_pi.raw_bit_offset, clamped_end - source_pi.raw_bit_offset)
    };

    // Clamp to payload boundary: parser's raw_bit_length may include
    // byte-alignment padding past the end of available data for the last
    // item on a page. Those padding bits are not real item data.
    let payload_bits = item_data[4..].len() * 8;
    let clamped_bit_len = target_bit_len.min(payload_bits.saturating_sub(target_start_bit));
    if clamped_bit_len != target_bit_len {
        log::info!("[deposit] step3d: clamped bit_len {} -> {} (payload_bits={} start_bit={})",
            target_bit_len, clamped_bit_len, payload_bits, target_start_bit);
    }
    
    let raw_bits = extract_item_bits(&item_data[4..], target_start_bit, clamped_bit_len)?;
    let raw_bit_length = clamped_bit_len;
    if raw_bits.is_empty() {
        log::error!("[deposit] step4: failed to extract raw bits for {} (off={} len={})", item_code, target_start_bit, target_bit_len);
        return Err("Failed to extract raw item bits".into());
    }

    // Pre-write verify: re-parse the extracted bits and confirm the item
    // code matches. Catches bit-level extraction errors (misaligned start_bit
    // or length) that would silently corrupt the stored item.
    {
        let mut verify_jm = Vec::with_capacity(raw_bits.len() + 4);
        verify_jm.extend_from_slice(b"JM");
        verify_jm.extend_from_slice(&[1u8, 0]); // count=1
        verify_jm.extend_from_slice(&raw_bits);
        let parsed = crate::protocol::d2i::parser::parse_item_stream_sequential(
            &verify_jm, page_index, page.is_stackable
        );
        match parsed.first() {
            Some(pi) if pi.item.code == item_code => {
                log::info!("[deposit] step4 verify OK: extracted bits parse as '{}'", item_code);
            }
            Some(pi) => {
                log::error!(
                    "[deposit] step4 verify FAILED: extracted bits parse as '{}', expected '{}'. \
                     Aborting deposit to prevent database corruption.",
                    pi.item.code, item_code
                );
                return Err(format!(
                    "Deposit verify failed: extracted item code '{}' does not match expected '{}'. \
                     This indicates a bit-level extraction error. Item NOT deposited.",
                    pi.item.code, item_code
                ));
            }
            None => {
                log::error!(
                    "[deposit] step4 verify FAILED: extracted bits could not be parsed as a valid item. \
                     Aborting deposit to prevent database corruption."
                );
                return Err(
                    "Deposit verify failed: extracted item bits could not be parsed. Item NOT deposited."
                    .to_string()
                );
            }
        }
    }
    let actual_qty = quantity.min(source_pi.item.amount);
    log::info!("[deposit] step5: actual_qty={} (requested={}, available={}) page_is_stackable={} ({:.2?})",
        actual_qty, quantity, source_pi.item.amount, page.is_stackable, _t0.elapsed());
    if actual_qty == 0 {
        log::error!("[deposit] step5: quantity=0 requested for item={}", item_code);
        return Err("Quantity must be > 0".into());
    }
    // Detect mod stash: page has raw is_stackable >= 2 signals mod extension
    // (e.g. Cycle of Immortals). For these stashes the game keeps zero-qty items
    // in the JM stream rather than removing them, because mod metadata in the
    // extension page indexes items by stream position.
    let is_mod_stash = file.pages.iter().any(|p| p.data.len() > 20 && p.data[20] >= 2);
    if is_mod_stash {
        log::info!("[deposit] step5: detected mod stash (is_stackable >= 2), keeping items in stream");
    }
    let updated_page_data = {
        let old_count = u16::from_le_bytes([item_data[2], item_data[3]]) as usize;
        let start_byte = target_start_bit / 8;
        let end_byte = (target_start_bit + target_bit_len).div_ceil(8);
        eprintln!("[deposit] DIAG: target_start_bit={} target_bit_len={} start_byte={} end_byte={} item_data.len()={}",
            target_start_bit, target_bit_len, start_byte, end_byte, item_data.len());

        // ── Diagnostic: log byte boundaries and adjacent data ──
        let jm_payload = &item_data[4..];
        let adj_before = if start_byte > 0 && start_byte <= jm_payload.len() {
            format!("{:02x?}", &jm_payload[start_byte.saturating_sub(4)..start_byte.min(jm_payload.len())])
        } else { "N/A".into() };
        let adj_removed = if start_byte < jm_payload.len() {
            format!("{:02x?}", &jm_payload[start_byte..end_byte.min(jm_payload.len())])
        } else { "N/A".into() };
        let adj_after = if end_byte + 4 <= jm_payload.len() {
            format!("{:02x?}", &jm_payload[end_byte..(end_byte + 4).min(jm_payload.len())])
        } else if end_byte < jm_payload.len() {
            format!("{:02x?}", &jm_payload[end_byte..jm_payload.len()])
        } else { "N/A".into() };
        log::info!(
            "[deposit] diag: page_idx={} code={} bit_off={} bit_len={} -> byte=[{},{}), jm_payload={}B, adj before={} removed={} after={}",
            page_index, item_code, target_start_bit, target_bit_len, start_byte, end_byte,
            jm_payload.len(), adj_before, adj_removed, adj_after
        );
        // Find previous item boundary for cross-check
        let prev_item = page_items.iter()
            .filter(|pi| pi.raw_bit_offset < source_pi.raw_bit_offset)
            .max_by_key(|pi| pi.raw_bit_offset);
        if let Some(prev) = prev_item {
            let prev_end = prev.raw_bit_offset + prev.raw_bit_length;
            let prev_end_byte = prev_end / 8;
            let gap = start_byte.saturating_sub(prev_end_byte);
            if gap != 0 {
                log::info!("[deposit] diag: prev item '{}' ends at byte {}, our item starts at byte {} (gap={}B)",
                    prev.item.code, prev_end_byte, start_byte, gap);
            }
        }
        // Verify that the byte BEFORE our slice is the last byte of previous item
        if start_byte > 0 && start_byte <= jm_payload.len()
            && let Some(prev) = prev_item
        {
            let prev_end = prev.raw_bit_offset + prev.raw_bit_length;
            log::info!("[deposit] diag: prev end_bit={} (byte={}) our start_bit={} (byte={})",
                prev_end, prev_end / 8, target_start_bit, start_byte);
        }
        // ── end diagnostic ──

        let mut new_jm = Vec::with_capacity(item_data.len());
        new_jm.extend_from_slice(b"JM");
        new_jm.extend_from_slice(&[0, 0]);
        if start_byte > 0 {
            let before_end = 4 + start_byte;
            new_jm.extend_from_slice(&item_data[4..before_end]);
        }
        if actual_qty >= source_pi.item.amount {
            if is_mod_stash {
                // Mod stash: keep item in stream with zeroed position (amount=0)
                // so mod metadata in extension pages stays indexed correctly.
                let px = 0u8;
                let py = 0u8;
                if 4 + end_byte <= item_data.len() && start_byte < end_byte {
                    let modified = update_item_position(&item_data[4+start_byte..4+end_byte], px, py, Some(0));
                    new_jm.extend_from_slice(&modified);
                }
                log::info!("[deposit] step5: mod-stash removal of code={} -> zeroed position (kept in stream)", item_code);
            } else {
                log::info!("[deposit] step5: remove item code={} (full removal, {}B, {:.2?})", item_code, end_byte - start_byte, _t0.elapsed());
            }
        } else {
            let new_amount = source_pi.item.amount - actual_qty;
            log::info!("[deposit] step5: reduce item code={} amount={}->{} ({:.2?})", item_code, source_pi.item.amount, new_amount, _t0.elapsed());
            let px = (new_amount & 0x0F) as u8;
            let py = ((new_amount >> 4) & 0x0F) as u8;
            if 4 + end_byte <= item_data.len() && start_byte < end_byte {
                let slice = &item_data[4+start_byte..4+end_byte];
                eprintln!("[deposit] update_item_position: start_byte={} end_byte={} slice_len={} px={} py={}",
                    start_byte, end_byte, slice.len(), px, py);
                eprintln!("[deposit]   slice[5] before=0x{:02x} slice[6] before=0x{:02x}",
                    slice[5], slice[6]);
                let modified = update_item_position(slice, px, py, Some(new_amount));
                eprintln!("[deposit]   slice[5] after=0x{:02x} slice[6] after=0x{:02x}",
                    modified[5], modified[6]);
                new_jm.extend_from_slice(&modified);
            }
        }
        if 4 + end_byte < item_data.len() {
            new_jm.extend_from_slice(&item_data[4+end_byte..]);
        }
        // Patch realm data amount (game reads amount from realm data, not position_x).
        // Realm data: item_start + compact_body_bytes + 15 = item_data[4+end_byte + 15]
        // Encoding: byte = amount * step + base, where step = largest power of 2
        if page.is_stackable && start_byte > 0 && source_pi.item.flags.simple_item() {
            const CORE_BYTES: usize = 10; // 简单堆叠项核心固定 80 bits
            let realm_off = 4 + (target_start_bit / 8) + CORE_BYTES + 15;
            let new_amount = source_pi.item.amount - actual_qty;
            if realm_off < item_data.len() {
                let old_b = item_data[realm_off];
                let old_amt = source_pi.item.amount as u8;
                // Find step = largest power of 2 such that base = old_b - old_amt * step is positive
                let step = [128u8, 64, 32, 16, 8, 4, 2, 1].into_iter()
                    .find(|&s| old_b as u16 > old_amt as u16 * s as u16)
                    .unwrap_or(1);
                let base_mul = old_b as i16 - old_amt as i16 * step as i16;
                let new_b = if base_mul >= 0 && base_mul < 256 {
                    let mul_result = base_mul + new_amount as i16 * step as i16;
                    if mul_result <= 255 {
                        mul_result as u8
                    } else {
                        // MUL 溢出: 尝试更小的 step
                        let mut found = None;
                        let mut try_step = step;
                        while try_step > 1 {
                            try_step /= 2;
                            let b = old_b as i16 - old_amt as i16 * try_step as i16;
                            if b >= 0 {
                                let r = b + new_amount as i16 * try_step as i16;
                                if r <= 255 {
                                    found = Some((try_step, r as u8));
                                    break;
                                }
                            }
                        }
                        if let Some((s, r)) = found {
                            log::info!("[deposit] realm MUL overflow: step {}->{} result={}", step, s, r);
                            r
                        } else {
                            // 全部 MUL 失败，尝试 DIV
                            let mut best: Option<(u8, u8)> = None;
                            for shift in 1u8..=7u8 {
                                let b = old_b as i16 - ((old_amt as i16) >> shift);
                                if b >= 0 && b < (1i16 << shift) {
                                    best = Some((shift, b as u8));
                                    break;
                                }
                            }
                            if let Some((shift, base)) = best {
                                ((new_amount >> shift) + base as u32) as u8
                            } else {
                                log::warn!("[deposit] realm SKIPPED for {} (all MUL/DIV failed)",
                                    item_code);
                                old_b
                            }
                        }
                    }
                } else {
                    // MUL 失败，尝试 DIV: realm = (amount >> shift) + base
                    let mut best: Option<(u8, u8)> = None;
                    for shift in 1u8..=7u8 {
                        let b = old_b as i16 - ((old_amt as i16) >> shift);
                        if b >= 0 && b < (1i16 << shift) {
                            best = Some((shift, b as u8));
                            break;
                        }
                    }
                    if let Some((shift, base)) = best {
                        ((new_amount >> shift) + base as u32) as u8
                    } else {
                        log::warn!("[deposit] realm patch SKIPPED: can't find encoding for {} (old_amt={} realm=0x{:02x})",
                            item_code, old_amt, old_b);
                        // Keep original — game may still be functional with px/py-only update
                        old_b
                    }
                };
                let jm_off = 4 + (target_start_bit / 8) + CORE_BYTES + 15;
                if jm_off < new_jm.len() && new_jm[jm_off] != new_b {
                    new_jm[jm_off] = new_b;
                    log::info!("[deposit] step5: realm patched at +{}B: 0x{:02x}->0x{:02x} (amt {}->{} step={} base_mul={})",
                        realm_off, old_b, new_b, source_pi.item.amount, new_amount, step, base_mul);
                }
            }
        }
        // Patch chest_stackable trailer (non-compact stackable items only, simple=false).
        // The last 2 bytes of the item encode amount as u16 LE = amount * 32 + base.
        // Low byte at new_jm[4+end_byte-1], high byte at new_jm[4+end_byte].
        if page.is_stackable && start_byte > 0 && !source_pi.item.flags.simple_item() {
            let new_amount = source_pi.item.amount - actual_qty;
            if 4 + end_byte < item_data.len() {
                let old_trailer = u16::from_le_bytes([item_data[4 + end_byte - 1], item_data[4 + end_byte]]);
                let old_amt = source_pi.item.amount;
                let base = old_trailer as i32 - old_amt as i32 * 32;
                if base >= 0 && base < 65536 {
                    let new_trailer = (new_amount as i32 * 32 + base) as u16;
                    let lo = (new_trailer & 0xFF) as u8;
                    let hi = (new_trailer >> 8) as u8;
                    let jm_lo = 4 + end_byte - 1;
                    let jm_hi = 4 + end_byte;
                    if jm_lo < new_jm.len() && new_jm[jm_lo] != lo {
                        new_jm[jm_lo] = lo;
                    }
                    if jm_hi < new_jm.len() && new_jm[jm_hi] != hi {
                        new_jm[jm_hi] = hi;
                    }
                    log::info!("[deposit] trailer patched: 0x{old_trailer:04x}->0x{new_trailer:04x} (base={base} amt {old_amt}->{new_amount})");
                }
            }
        }
        let new_count = if is_mod_stash {
            old_count
        } else if actual_qty >= source_pi.item.amount {
            old_count.saturating_sub(1)
        } else {
            old_count
        };
        if new_count == 0 {
            new_jm.truncate(4);
            new_jm[2..4].copy_from_slice(&(0u16).to_le_bytes());
        } else {
            new_jm[2..4].copy_from_slice(&(new_count as u16).to_le_bytes());
        }
        let mut page_data = page.data[..64].to_vec();
        page_data.extend_from_slice(&new_jm);
        let new_size = page_data.len() as u32;
        page_data[16..20].copy_from_slice(&new_size.to_le_bytes());
        log::info!("[deposit] step5: page_data={}B, items {}->{} ({:.2?})", page_data.len(), old_count, new_count, _t0.elapsed());
        page_data
    };
    let mut updated_pages = file.pages.clone();
    if let Some(p) = updated_pages.get_mut(page_index) {
        p.data = updated_page_data;
    }

    let final_data = crate::protocol::d2i::page::reassemble_pages(&updated_pages, &file.tail);
    log::info!("[deposit] step6: total reassembled d2i={}B, preparing backup... ({:.2?})", final_data.len(), _t0.elapsed());
    // Compute expected post-write count from the original parsed page so the
    // verify block (which lives outside the closure that built new_jm) can
    // check the new count without re-parsing.
    let original_page = file.pages.get(page_index).expect("deposit: page already validated above");
    let original_jm = &original_page.data[64..];
    let old_count = if original_jm.len() >= 4 {
        u16::from_le_bytes([original_jm[2], original_jm[3]]) as usize
    } else {
        0
    };
    let expected_count = if is_mod_stash {
        old_count
    } else if quantity >= source_pi.item.amount {
        old_count.saturating_sub(1)
    } else {
        old_count
    };
    let save_folder: String = {
        let db = state.db.lock().map_err(|e| format!("DB lock: {}", e))?;
        db.get_config("save_folder").ok().flatten().unwrap_or_default()
    };
    let backup_root = if save_folder.is_empty() {
        std::path::Path::new(&stash_path).parent()
            .map(|p| p.to_path_buf())
            .unwrap_or_else(|| std::path::PathBuf::from("."))
    } else {
        std::path::PathBuf::from(&save_folder)
    };
    let auto_dir = backup_root.join("marketplace_backups").join("auto");
    let _ = std::fs::create_dir_all(&auto_dir);
    let ts = chrono::Local::now().format("%Y%m%d_%H%M%S");
    let stash_filename = std::path::Path::new(&stash_path)
        .file_name().unwrap().to_string_lossy();
    let backup_name = format!("{}.deposit_{}.bak", stash_filename, ts);
    let backup_path = auto_dir.join(&backup_name);
    std::fs::copy(&stash_path, &backup_path)
        .map_err(|e| { log::error!("[deposit] auto-backup FAILED: {}", e); format!("Failed to create backup: {}", e) })?;
    std::fs::write(&stash_path, &final_data)
        .map_err(|e| { log::error!("[deposit] step7 fs::write FAILED: {}", e); format!("Failed to write stash: {}", e) })?;

    // Verify: read back the stash we just wrote and confirm the target item
    // is actually GONE from the source page. Mirror of the withdraw verify —
    // without this, a corrupt write would silently leave the item removed
    // from the d2i file while we still add it to SQLite, losing the item.
    {
        let verify_bytes = match std::fs::read(&stash_path) {
            Ok(b) => b,
            Err(e) => {
                let _ = restore_stash_from_backup(&stash_path, &backup_path);
                return Err(format!("[deposit] verify: read back failed: {}", e));
            }
        };
        let verify_file = match crate::protocol::d2i::parser::parse_file(&verify_bytes) {
            Ok(f) => f,
            Err(e) => {
                let _ = restore_stash_from_backup(&stash_path, &backup_path);
                return Err(format!("[deposit] verify: parse failed: {}", e));
            }
        };
        let verify_page = match verify_file.pages.get(page_index) {
            Some(p) => p,
            None => {
                let _ = restore_stash_from_backup(&stash_path, &backup_path);
                return Err(format!("[deposit] verify: target page {} missing after write", page_index));
            }
        };
        let verify_jm = &verify_page.data[64..];
        let verify_count = if verify_jm.len() >= 4 {
            u16::from_le_bytes([verify_jm[2], verify_jm[3]]) as usize
        } else {
            0
        };
        if verify_count != expected_count {
            let _ = restore_stash_from_backup(&stash_path, &backup_path);
            return Err(format!(
                "[deposit] verify: page {} has {} items, expected {} (item not removed). Restored from backup.",
                page_index, verify_count, expected_count
            ));
        }
        log::info!("[deposit] step6b verify OK: page {} now has {} items (was {})", page_index, verify_count, old_count);
    }

    let (inv_width, inv_height) = crate::protocol::d2i::legacy::item::get_item_inventory_size(&item_code);
    let stat_lists_value = serde_json::to_value(&source_pi.item.stat_lists).unwrap_or(serde_json::Value::Array(Vec::new()));
    let item_json = serde_json::json!({
        "item_type": source_pi.item.code,
        "quality": source_pi.item.quality.as_u8(),
        "amount": actual_qty,
        "simple_item": source_pi.item.flags.simple_item(),
        "identified": source_pi.item.flags.identified(),
        "socketed": source_pi.item.flags.socketed(),
        "ethereal": source_pi.item.flags.ethereal(),
        "position_x": source_pi.item.x,
        "position_y": source_pi.item.y,
        "inv_width": inv_width,
        "inv_height": inv_height,
        "stat_lists": stat_lists_value,
        "socketed_items": source_pi.item.socketed_items,
    });
    let kind = if crate::protocol::d2i::legacy::game_data_loader::is_grimoire_offhand(&item_code) {
        "shield".to_string()
    } else {
        crate::protocol::d2i::legacy::constants::ITEM_CODE_MAP.iter()
            .find(|(c, _, _, _)| *c == item_code)
            .map(|(_, _, k, _)| k.to_string())
            .unwrap_or_else(|| { log::warn!("[deposit] step8: item_code '{}' NOT FOUND in ITEM_CODE_MAP, defaulting to 'misc'", item_code); "misc".to_string() })
    };
    let quality_str = match source_pi.item.quality {
        crate::protocol::common::ItemQuality::Unique => "unique",
        crate::protocol::common::ItemQuality::Rare => "rare",
        crate::protocol::common::ItemQuality::Set => "set",
        crate::protocol::common::ItemQuality::Magic => "magic",
        crate::protocol::common::ItemQuality::Superior => "superior",
        crate::protocol::common::ItemQuality::Low => "low",
        _ => "normal",
    };
    log::info!("[deposit] step7-9: item_kind={} quality={} ({:.2?})", kind, quality_str, _t0.elapsed());
    let db = state.db.lock().map_err(|e| { log::error!("[deposit] step10 db.lock FAILED: {}", e); e.to_string() })?;
    log::info!("[deposit] step10: db locked ({:.2?})", _t0.elapsed());
    let wh_language = db.get_config("language").ok().flatten().unwrap_or_else(|| "enUS".to_string());
    let _wh_game_root = db.get_config("game_root").ok().flatten().unwrap_or_default();
    let wh_active_mod = db.get_config("active_mod").ok().flatten().unwrap_or_default();
    let wh_game_version = db.get_config("game_version").ok().flatten().unwrap_or_default();
    let wh_profile_id = crate::commands::config::get_active_profile_id(&db).unwrap_or(0);
    let wh_profile_key = crate::commands::config::get_active_profile_key(&db).unwrap_or_default();
    log::info!("[deposit] step10: profile_id={} profile_key='{}' lang='{}' mod='{}' version='{}' ({:.2?})",
        wh_profile_id, wh_profile_key, wh_language, wh_active_mod, wh_game_version, _t0.elapsed());
    let target_page_name = match page_name {
        Some(page_name) => validate_page_name(&page_name)?,
        None => db
            .warehouse_get_code_default(&item_code)
            .map_err(|e| e.to_string())?
            .unwrap_or_else(|| DEFAULT_WAREHOUSE_PAGE.to_string()),
    };
    let warehoused = WarehousedItem {
        id: uuid::Uuid::new_v4().to_string(),
        item_code: item_code.clone(),
        item_name: String::new(),
        item_kind: kind.clone(),
        quality: Some(quality_str.to_string()),
        simple_item: source_pi.item.flags.simple_item(),
        quantity: actual_qty,
        profile_key: wh_profile_key,
        game_version: wh_game_version.clone(),
        mod_name: wh_active_mod.clone(),
        raw_item_bits: raw_bits,
        raw_bit_length,
        item_json: item_json.to_string(),
        stash_name: Some(stash_path.clone()),
        imported_at: chrono::Utc::now().to_rfc3339(),
        page_name: target_page_name.clone(),
        tags: String::new(),
        notes: String::new(),
        source_character: None,
        source_save_path: None,
        slot_equipped: None,
        page_index: page_index as i32,
        position_x: position_x as i32,
        position_y: position_y as i32,
        inv_width: inv_width as i32,
        inv_height: inv_height as i32,
    };
    let localized_name = if wh_profile_id > 0 {
        log::info!("[deposit] step10b: resolving NameResolver ({:.2?})", _t0.elapsed());
        let quality_u8 = match source_pi.item.quality {
            crate::protocol::common::ItemQuality::Unique => Some(7),
            crate::protocol::common::ItemQuality::Set => Some(5),
            crate::protocol::common::ItemQuality::Rare => Some(6),
            crate::protocol::common::ItemQuality::Magic => Some(4),
            crate::protocol::common::ItemQuality::Superior => Some(3),
            crate::protocol::common::ItemQuality::Low => Some(1),
            _ => None,
        };
        let resolver = crate::resource::get_cached_resolver(db.get_connection(), wh_profile_id);
        resolver.resolve(db.get_connection(), &item_code, quality_u8, None, None, &wh_language).display_name
    } else {
        item_code.clone()
    };
    log::info!("[deposit] step10b: resolved name='{}' ({:.2?})", localized_name, _t0.elapsed());
    let named_item = WarehousedItem {
        item_name: localized_name,
        ..warehoused
    };
    db.warehouse_add(&named_item).map_err(|e| { log::error!("[deposit] step10c warehouse_add FAILED: {}", e); e.to_string() })?;
    log::info!("[deposit] step10c: warehouse_add OK, id={} ({:.2?})", named_item.id, _t0.elapsed());
    drop(db);
    if let Err(e) = std::fs::write(&stash_path, &final_data) {
        log::error!("[deposit] step11 write FAILED: {}", e);
        let mut rollback_notes: Vec<String> = Vec::new();
        match state.db.lock() {
            Ok(db) => {
                let remove_result = if named_item.profile_key.is_empty() {
                    db.warehouse_remove(&named_item.id)
                } else {
                    db.warehouse_remove_in_profile(&named_item.profile_key, &named_item.id)
                };
                match remove_result {
                    Ok(true) => {}
                    Ok(false) => rollback_notes.push(format!("warehouse row {} was not removed during rollback", named_item.id)),
                    Err(remove_err) => rollback_notes.push(format!("failed to remove warehouse row during rollback: {}", remove_err)),
                }
            }
            Err(lock_err) => rollback_notes.push(format!("failed to lock db during rollback: {}", lock_err)),
        }
        if let Err(restore_err) = restore_stash_from_backup(&stash_path, &backup_path) {
            rollback_notes.push(restore_err);
        }
        let rollback_tail = if rollback_notes.is_empty() {
            String::new()
        } else {
            format!(" ({})", rollback_notes.join("; "))
        };
        return Err(format!("Failed to write stash, deposit rolled back: {}{}", e, rollback_tail));
    }
    log::info!("[deposit] step11: write OK ({:.2?})", _t0.elapsed());
    let db = state.db.lock().map_err(|e| e.to_string())?;
    if let Err(e) = db.add_transaction("warehouse_deposit", None, 0,
        &format!("Deposited {} x{} to warehouse page {}", item_code, actual_qty, target_page_name)) {
        log::warn!("[deposit] step12 add_transaction FAILED: {}", e);
    } else {
        log::info!("[deposit] step12: transaction OK, TOTAL={:.2?}", _t0.elapsed());
    }
    Ok(())
}

/// Detect whether Diablo II: Resurrected (or its mod loader) is currently
/// running. D2R holds the shared stash in memory and writes its in-memory
/// version back on exit, which would silently overwrite any change we make
/// from this app. Refuse withdraw/deposit operations in that case so the
/// user can quit the game first. Both `D2R.exe` and `D2RLoader.exe` (used
/// by most mod managers) are checked.
fn is_d2r_running() -> bool {
    let candidates: &[&str] = if cfg!(target_os = "windows") {
        &["D2R.exe", "D2RLoader.exe"]
    } else {
        // macOS / Linux: process names are case-sensitive under pgrep -x.
        &["D2R", "D2RLoader"]
    };
    #[cfg(target_os = "windows")]
    {
        for exe in candidates {
            // /NH strips the header row, /FO CSV normalises quoting.
            let output = std::process::Command::new("tasklist")
                .args(["/FI", &format!("IMAGENAME eq {}", exe), "/NH", "/FO", "CSV"])
                .output();
            if let Ok(out) = output {
                let stdout = String::from_utf8_lossy(&out.stdout);
                // CSV row starts with the image name; presence => running.
                if stdout.to_ascii_lowercase().contains(&exe.to_ascii_lowercase()) {
                    return true;
                }
            }
        }
        false
    }
    #[cfg(not(target_os = "windows"))]
    {
        for name in candidates {
            let output = std::process::Command::new("pgrep")
                .args(["-lx", name])
                .output();
            if let Ok(out) = output {
                if out.status.success() && !out.stdout.is_empty() {
                    return true;
                }
            }
        }
        false
    }
}

/// Withdraw a warehoused item back to the stash file.
///
/// `quantity`: 可选。None/0 = 全量(老行为);1..item.quantity = 部分取回,
/// stash 会得到一份 amount=N 的新 item,DB 里 quantity 减 N(raw_bits 重编码)。
#[tauri::command]
pub fn warehouse_withdraw(
    state: State<AppState>,
    item_id: String,
    stash_path: String,
    page_index: usize,
    position_x: u8,
    position_y: u8,
    quantity: Option<u32>,
) -> Result<(), String> {
    if is_d2r_running() {
        return Err("检测到 D2R 正在运行 (D2R.exe 或 D2RLoader.exe)。请先关闭游戏再取出物品:游戏退出时会把内存中的共享仓库版本写回磁盘,覆盖你刚写入的内容。".into());
    }
    warehouse_withdraw_inner(&state, item_id, stash_path, page_index, position_x, position_y, quantity)
}

/// Validate that the target (x, y, w, h) is within the 16x16 page bounds and
/// does not overlap any existing item on the page. Returns Err with a
/// descriptive message otherwise. Exposed so tests (and any future callers)
/// can reuse the same validation logic without performing a full withdraw.
pub fn check_withdraw_position(
    stash_data: &[u8],
    page_index: usize,
    position_x: u8,
    position_y: u8,
    inv_w: u8,
    inv_h: u8,
) -> Result<(), String> {
    // Bounds check (T16)
    if position_x.saturating_add(inv_w) > 16 || position_y.saturating_add(inv_h) > 16 {
        return Err(format!(
            "Position out of bounds: ({},{}) with size {}x{} exceeds 16x16 stash page",
            position_x, position_y, inv_w, inv_h
        ));
    }

    let file = crate::protocol::d2i::parser::parse_file(stash_data)
        .map_err(|e| format!("Failed to parse stash: {}", e))?;
    let page = file.pages.get(page_index)
        .ok_or_else(|| format!("Page {} not found", page_index))?;

    // Collision check (T17) — only for non-stackable pages.
    // Stackable pages use position to encode amount (not grid position),
    // so collision is not meaningful and a position like (0,0) would
    // always be "occupied" by an item with amount=0 (px=0, py=0).
    if !page.is_stackable {
        let page_items: Vec<&crate::protocol::d2i::parser::ParsedItem> = file.items.iter()
            .filter(|pi| pi.page_index == page_index)
            .collect();
        for existing in &page_items {
            let (ew, eh) = crate::protocol::d2i::legacy::item::get_item_inventory_size(&existing.item.code);
            let ex = existing.item.x;
            let ey = existing.item.y;
            let overlap_x = position_x < ex.saturating_add(ew) && ex < position_x.saturating_add(inv_w);
            let overlap_y = position_y < ey.saturating_add(eh) && ey < position_y.saturating_add(inv_h);
            if overlap_x && overlap_y {
                return Err(format!(
                    "Target cell ({},{}) is occupied by {} at ({},{}) size {}x{}. Choose an empty cell.",
                    position_x, position_y, existing.item.code, ex, ey, ew, eh
                ));
            }
        }
    }
    Ok(())
}

/// Testable inner function: does the actual withdraw work without tauri::State wrapper.
///
/// `quantity` 语义:
/// - `None` 或 `0` → 全量取回(老行为),DB 删除该 row。
/// - `1..item.quantity` → 部分取回。stash 写入 amount=N 的新 item,
///   DB row 保留但 quantity 减 N,raw_item_bits 重编码新 amount。
/// - `>= item.quantity` → 走全量路径。
pub fn warehouse_withdraw_inner(
    state: &AppState,
    item_id: String,
    stash_path: String,
    page_index: usize,
    position_x: u8,
    position_y: u8,
    quantity: Option<u32>,
) -> Result<(), String> {
    // 1. Get the warehoused item from DB
    let db = state.db.lock().map_err(|e| e.to_string())?;
    let active_profile_key = crate::commands::config::get_active_profile_key(&db).unwrap_or_default();
    let warehouse_item = db.warehouse_get_in_profile(&active_profile_key, &item_id)
        .map_err(|e| e.to_string())?
        .ok_or_else(|| "Warehouse item not found".to_string())?;
    drop(db);

    // 1a. 解析 requested_quantity:None/0 → 全量;>item.quantity → 全量;<1 → Err。
    let max_qty = warehouse_item.quantity.max(1);
    let requested = match quantity {
        None | Some(0) => max_qty,
        Some(n) if n >= max_qty => max_qty,
        Some(n) if n < 1 => return Err("quantity 必须 >= 1".to_string()),
        Some(n) => n,
    };
    let is_partial = requested < max_qty;

    // 2.5 检查 raw_item_bits 是否有效
    if warehouse_item.raw_item_bits.is_empty() {
        return Err(format!(
            "[withdraw] 物品 {} ({}) 没有原始比特数据,无法取回共享仓库。\
            该物品由角色提取入库,需重新提取才能取回。",
            warehouse_item.item_code, warehouse_item.item_name
        ));
    }

    // 2. Determine withdrawn item's dimensions from item_json
    //    Defaults: 1x1 (covers runes/gems/keys which are always 1x1)
    let (inv_w, inv_h) = serde_json::from_str::<serde_json::Value>(&warehouse_item.item_json)
        .ok().map(|j| (
            j.get("inv_width").and_then(|v| v.as_u64()).unwrap_or(1) as u8,
            j.get("inv_height").and_then(|v| v.as_u64()).unwrap_or(1) as u8,
        ))
        .unwrap_or((1, 1));

    let stash_file = crate::core::MmapFile::open(&stash_path)
        .map_err(|e| format!("Failed to read stash: {}", e))?;
    let stash_data: &[u8] = stash_file.as_slice();

    // 3. Bounds + collision check (T16 + T17)
    check_withdraw_position(stash_data, page_index, position_x, position_y, inv_w, inv_h)?;

    let file = crate::protocol::d2i::parser::parse_file(stash_data)
        .map_err(|e| format!("Failed to parse stash: {}", e))?;

    let page = file.pages.get(page_index)
        .ok_or_else(|| format!("Page {} not found", page_index))?;
    log::info!("[withdraw] DEBUG page: index={} data.len={} page_header_size={}",
        page.index, page.data.len(),
        u32::from_le_bytes([page.data[16], page.data[17], page.data[18], page.data[19]]));
    let item_data = &page.data[64..];
    let old_count = u16::from_le_bytes([item_data[2], item_data[3]]) as usize;
    // Count of main items (after socket association) — the JM header count
    // may include socketed sub-items, so we need the post-absorption count
    // for the pre-write verify to match parse_file's output.
    let _main_count: usize = file.items.iter()
        .filter(|pi| pi.page_index == page_index)
        .count();

    // Release the mmap now that we've copied everything we need. Required
    // on Windows where an active mmap blocks subsequent std::fs::write
    // with os error 1224 ("请求的操作无法在使用用户映射区域打开的文件上执行").
    drop(stash_file);

    // 堆叠页: 合并到已有堆叠, 避免 app 显示 > 游戏实际数量。
    let merge_target = if page.is_stackable {
        let page_items: Vec<&crate::protocol::d2i::parser::ParsedItem> = file.items.iter()
            .filter(|pi| pi.page_index == page_index)
            .collect();
        page_items.iter().find(|pi| pi.item.code == warehouse_item.item_code).map(|&existing| {
            let new_amount = (existing.item.amount + requested).min(99);
            (existing.raw_bit_offset, existing.raw_bit_length, new_amount)
        })
    } else {
        None
    };
    if let Some((_, _, na)) = &merge_target {
        log::info!("[withdraw] step4: stackable merge, code={} new_amount={}", warehouse_item.item_code, na);
    }
    // 4. Build new JM data: existing items + withdrawn item
    let mut new_jm = Vec::with_capacity(item_data.len() + 256);
    new_jm.extend_from_slice(b"JM");
    new_jm.extend_from_slice(&[0, 0]); // count placeholder

    // Copy all existing items (raw JM data after header, byte 4 onward)
    if item_data.len() > 4 {
        new_jm.extend_from_slice(&item_data[4..]);
    }
    // Build item bits for the withdrawn item
    let raw_bits = &warehouse_item.raw_item_bits;
    let clean_bits = if raw_bits.len() >= 4 && &raw_bits[0..2] == b"JM" {
        log::info!("[withdraw] step4: stripped JM header from stored bits (old format)");
        &raw_bits[4..]
    } else {
        raw_bits.as_slice()
    };

    let (new_count, item_bits) = if let Some((raw_bit_off, raw_bit_len, new_amount)) = merge_target {
        // Mod stash merge: modify existing item's position (encodes qty) in-place
        let start_byte = (raw_bit_off / 8) as usize;
        let end_byte = ((raw_bit_off + raw_bit_len).div_ceil(8)) as usize;
        let payload_start = 4 + start_byte;
        let payload_end = 4 + end_byte;
        if payload_end <= new_jm.len() && start_byte < end_byte {
            let px = (new_amount & 0x0F) as u8;
            let py = ((new_amount >> 4) & 0x0F) as u8;
            let modified = update_item_position(&new_jm[payload_start..payload_end], px, py, Some(new_amount as u32));
            eprintln!("[DBG] update_item_position: px={} py={} slice5_before=0x{:02x}", px, py, new_jm[payload_start+5]);
            new_jm.splice(payload_start..payload_end, modified);
        }
            eprintln!("[DBG] splice done: new_jm[payload_start+5]=0x{:02x} new_jm[payload_start+6]=0x{:02x}",
                new_jm[payload_start+5], new_jm[payload_start+6]);
        // Patch realm byte for compact items (runes/gems)
        if page.is_stackable && warehouse_item.simple_item {
            const CORE_BYTES: usize = 10;
            let realm_off = 4 + start_byte + CORE_BYTES + 15;
            if realm_off < new_jm.len() {
                let old_b = new_jm[realm_off];
                let old_amt = (new_amount - requested) as u8;
                let step = [128u8, 64, 32, 16, 8, 4, 2, 1].into_iter()
                    .find(|&s| old_b as u16 > old_amt as u16 * s as u16)
                    .unwrap_or(1);
                let base_mul = old_b as i16 - old_amt as i16 * step as i16;
                let new_b = if base_mul >= 0 && base_mul < 256 {
                    let mul_result = base_mul + new_amount as i16 * step as i16;
                    if mul_result <= 255 {
                        mul_result as u8
                    } else {
                        // MUL 溢出: 尝试更小的 step
                        let mut found = None;
                        let mut try_step = step;
                        while try_step > 1 {
                            try_step /= 2;
                            let b = old_b as i16 - old_amt as i16 * try_step as i16;
                            if b >= 0 {
                                let r = b + new_amount as i16 * try_step as i16;
                                if r <= 255 {
                                    found = Some((try_step, b as u8, r as u8));
                                    break;
                                }
                            }
                        }
                        if let Some((s, _base, r)) = found {
                            log::info!("[withdraw] realm MUL overflow: step {}->{} result={}", step, s, r);
                            r
                        } else {
                            // 全部 MUL 失败，尝试 DIV
                            let mut best: Option<(u8, u8)> = None;
                            for shift in 1u8..=7u8 {
                                let b = old_b as i16 - ((old_amt as i16) >> shift);
                                if b >= 0 && b < (1i16 << shift) {
                                    best = Some((shift, b as u8));
                                    break;
                                }
                            }
                            if let Some((shift, base)) = best {
                                ((new_amount >> shift) + base as u32) as u8
                            } else {
                                log::warn!("[withdraw] realm SKIPPED for {} (all MUL/DIV failed)",
                                    warehouse_item.item_code);
                                old_b
                            }
                        }
                    }
                } else {
                    let mut best: Option<(u8, u8)> = None;
                    for shift in 1u8..=7u8 {
                        let b = old_b as i16 - ((old_amt as i16) >> shift);
                        if b >= 0 && b < (1i16 << shift) {
                            best = Some((shift, b as u8));
                            break;
                        }
                    }
                    if let Some((shift, base)) = best {
                        ((new_amount >> shift) + base as u32) as u8
                    } else {
                        log::warn!("[withdraw] realm SKIPPED for {} (old_amt={} realm=0x{:02x})",
                            warehouse_item.item_code, old_amt, old_b);
                        old_b
                    }
                };
                if new_jm[realm_off] != new_b {
                    new_jm[realm_off] = new_b;
                    log::info!("[withdraw] realm patched at +{}B: 0x{:02x}->0x{:02x} (amt {}->{} step={} base_mul={})",
                        realm_off, old_b, new_b, old_amt, new_amount, step, base_mul);
                }
            }
        }
        // Patch chest_stackable trailer for non-compact items
        if page.is_stackable && !warehouse_item.simple_item
            && 4 + end_byte < new_jm.len() {
                let old_trailer = u16::from_le_bytes([new_jm[4 + end_byte - 1], new_jm[4 + end_byte]]);
                let base = old_trailer as i32 - (new_amount - requested) as i32 * 32;
                if base >= 0 && base < 65536 {
                    let new_trailer = (new_amount as i32 * 32 + base) as u16;
                    new_jm[4 + end_byte - 1] = (new_trailer & 0xFF) as u8;
                    new_jm[4 + end_byte] = (new_trailer >> 8) as u8;
                    log::info!("[withdraw] trailer patched: 0x{old_trailer:04x}->0x{new_trailer:04x} (base={base} amt {}->{})",
                        new_amount - requested, new_amount);
                }
        }
        log::info!("[withdraw] step4: stackable merged code={} -> amount={} (count unchanged={})",
            warehouse_item.item_code, new_amount, old_count);
        (old_count, Vec::new())
    } else {
        // Standard path: append new item
        let ib = if page.is_stackable {
            if is_partial {
                // 部分取回:把 amount 重编码为 `requested`。
                // amount 8-bit 编码 (py << 4) | px。
                let new_amount = requested;
                let px = (new_amount & 0x0F) as u8;
                let py = ((new_amount >> 4) & 0x0F) as u8;
                log::info!(
                    "[withdraw] step4: stackable partial, raw_bits={}B, re-encoding amount {} -> {}",
                    clean_bits.len(), warehouse_item.quantity, new_amount
                );
                update_item_position(clean_bits, px, py, Some(requested))
            } else {
                log::info!("[withdraw] step4: stackable page, raw_bits={}B, keeping original", clean_bits.len());
                clean_bits.to_vec()
            }
        } else {
            // Non-stackable page: 直接用原始 raw bits（含完整 stat + 镶嵌子物品），
            // 仅 patch 头部字段（mode→Stored / loc→None / px / py / pg→SharedStash）。
            // ★ 不做 JSON 重编码：encode 逻辑不完整（stat 会被清空、多数字段位含义未覆盖），
            //   会导致物品属性丢失甚至进游戏崩溃。
            {
                // 先校验 raw bits 能解析为预期物品，再原样复制写入。
                let mut probe = Vec::with_capacity(clean_bits.len() + 4);
                probe.extend_from_slice(b"JM");
                probe.extend_from_slice(&[1u8, 0]);
                probe.extend_from_slice(clean_bits);
                let parsed_flat = crate::protocol::d2i::parser::parse_item_stream_sequential(
                    &probe, page_index, false
                );
                let parsed = crate::protocol::d2i::parser::associate_socketed_items(&parsed_flat);
                match parsed.first() {
                    Some(pi) if pi.item.code == warehouse_item.item_code => {
                        log::info!("[withdraw] verified raw bits as {} ({} sockets), patching position only",
                            pi.item.code, pi.item.socketed_items.len());
                        update_item_position(clean_bits, position_x, position_y, None)
                    }
                    _ => {
                        log::warn!("[withdraw] could not parse clean_bits, using update_item_position");
                        update_item_position(clean_bits, position_x, position_y, None)
                    }
                }
            }
        };
        log::info!("[withdraw] step4: pos=({},{}), raw_bits={}B item_bits={}B",
            position_x, position_y, clean_bits.len(), ib.len());
        // Count actual items in the bitstream — for non-stackable pages,
        // only count the PARENT item, not socketed sub-items (game expects
        // JM count = main items only)
        let parent_count = if page.is_stackable { 1 } else {
            let all = count_items_in_jm_stream(&ib);
            // ib can contain 1 parent + N sockets. Only count the parent.
            log::info!("[withdraw] ib has {} items, counting as 1 (parent only)", all);
            1
        };
        (old_count + parent_count, ib)
    };

    // Append withdrawn item bits (empty vec for merge case)
    log::info!("[withdraw] build_new_jm: item_data={}B [4..]={}B item_bits={}B pre_append_new_jm={}B",
        item_data.len(), item_data[4..].len(), item_bits.len(), new_jm.len());
    // ★ DUMP item_bits and new_jm tail for comparison
    if !item_bits.is_empty() {
        new_jm.extend_from_slice(&item_bits);
    }
    new_jm[2..4].copy_from_slice(&(new_count as u16).to_le_bytes());



    // Build page data (header + new JM) and verify it parses correctly
    // BEFORE touching the d2i file. Uses parse_jm_page (same path as
    // parse_file) to catch assembly errors.
    // Build page header from scratch — do NOT copy from page.data[..64] because
    // page.data may have been truncated by earlier stash-service writes.
    // The page header fields (magic, unknown1-3, etc.) are reconstructed from
    // the original page metadata so we get a consistent 64-byte header.
    let mut page_header = page.data[..64.min(page.data.len())].to_vec();
    if page_header.len() < 64 {
        page_header.resize(64, 0);
    }
    let mut page_data = page_header;
    page_data.extend_from_slice(&new_jm);
    let new_size = page_data.len() as u32;
    page_data[16..20].copy_from_slice(&new_size.to_le_bytes());
    log::info!("[withdraw] step5: page_data={}B (header={}+jm={}), items {}->{}", 
        page_data.len(), 64, new_jm.len(), old_count, new_count);

    // Pre-write verification: only for non-merge path (item_bits is non-empty).
    // Merge path modifies existing item in-place; no new bits to verify.
    if !item_bits.is_empty() {
        let mut verify_bits = Vec::with_capacity(item_bits.len() + 4);
        verify_bits.extend_from_slice(b"JM");
        verify_bits.extend_from_slice(&[1u8, 0]);
        verify_bits.extend_from_slice(&item_bits);
        let parsed = crate::protocol::d2i::parser::parse_item_stream_sequential(
            &verify_bits, page_index, page.is_stackable
        );
        let first_code = parsed.first().map(|p| p.item.code.as_str()).unwrap_or("(none)");
        if parsed.is_empty() || first_code != warehouse_item.item_code {
            return Err(format!(
                "[withdraw] step4.5 pre-write verify FAILED: adjusted bits parse as '{}' ({} items), \
                 expected '{}'. d2i file NOT modified, warehouse item NOT removed.",
                first_code, parsed.len(), warehouse_item.item_code
            ));
        }
        log::info!(
            "[withdraw] step4.5 pre-write verify OK: {} items, first code='{}'",
            parsed.len(), first_code
        );
    }
    // 5. Write stash back with auto-backup (consistent path with settings UI)
    let save_folder: String = {
        let db = state.db.lock().map_err(|e| format!("DB lock: {}", e))?;
        db.get_config("save_folder").ok().flatten().unwrap_or_default()
    };
    let backup_root = if save_folder.is_empty() {
        std::path::Path::new(&stash_path).parent()
            .map(|p| p.to_path_buf())
            .unwrap_or_else(|| std::path::PathBuf::from("."))
    } else {
        std::path::PathBuf::from(&save_folder)
    };
    let auto_dir = backup_root.join("marketplace_backups").join("auto");
    let _ = std::fs::create_dir_all(&auto_dir);
    let ts = chrono::Local::now().format("%Y%m%d_%H%M%S");
    let stash_filename = std::path::Path::new(&stash_path)
        .file_name().unwrap().to_string_lossy();
    let backup_name = format!("{}.withdraw_{}.bak", stash_filename, ts);
    let backup_path = auto_dir.join(&backup_name);
    std::fs::copy(&stash_path, &backup_path)
        .map_err(|e| format!("Failed to create backup: {}", e))?;

    let mut updated_pages = file.pages.clone();
    if let Some(p) = updated_pages.get_mut(page_index) {
        p.data = page_data;
    }

    let final_data = crate::protocol::d2i::page::reassemble_pages(&updated_pages, &file.tail);
    log::info!(
        "[withdraw] write: page_data={}B final={}B expected_page_size={}",
        final_data.len(), // actually total file size
        updated_pages[page_index].data.len(),
        u32::from_le_bytes([updated_pages[page_index].data[16], updated_pages[page_index].data[17],
                            updated_pages[page_index].data[18], updated_pages[page_index].data[19]])
    );
    std::fs::write(&stash_path, &final_data)
        .map_err(|e| format!("Failed to write stash: {}", e))?;

    // ★ DEBUG: log the page_size field (bytes 16-20) of our written data vs raw file
    {
        let raw = std::fs::read(&stash_path).unwrap_or_default();
        let written_ps = u32::from_le_bytes([final_data[16], final_data[17], final_data[18], final_data[19]]);
        let raw_ps = if raw.len() > 20 { u32::from_le_bytes([raw[16], raw[17], raw[18], raw[19]]) } else { 0 };
        let written_jm_count = if final_data.len() > 0x43 { u16::from_le_bytes([final_data[0x42], final_data[0x43]]) } else { 0 };
        let raw_jm_count = if raw.len() > 0x43 { u16::from_le_bytes([raw[0x42], raw[0x43]]) } else { 0 };
        log::info!("[withdraw] DEBUG verify: written_page_size={} raw_page_size={} written_jm_count={} raw_jm_count={}",
            written_ps, raw_ps, written_jm_count, raw_jm_count);
        // Also check if the page 0 data is actually 806 bytes
        log::info!("[withdraw] DEBUG page0_len: in_write_buffer={}B on_disk={}B",
            final_data.len().min(806), raw.len().min(806));
        // ★ CRITICAL: log the last 30 bytes of the JM section (should contain new item)
        let jm_end = 64 + new_jm.len();
        if final_data.len() >= jm_end {
            let tail_start = jm_end.saturating_sub(60);
            log::info!("[withdraw] DEBUG new_jm tail bytes (last 60B at offset {}): {:02x?}",
                tail_start, &final_data[tail_start..jm_end]);
        }
        if raw.len() >= jm_end {
            let tail_start = jm_end.saturating_sub(60);
            log::info!("[withdraw] DEBUG on_disk tail bytes (last 60B at offset {}): {:02x?}",
                tail_start, &raw[tail_start..jm_end]);
        }
    }

    // Diagnostic: read back and compare page header with what we wrote
    {
        let read_back = std::fs::read(&stash_path)
            .map_err(|e| format!("Failed to read back stash: {}", e))?;
        let read_page_size = if read_back.len() > 20 {
            u32::from_le_bytes([read_back[16], read_back[17], read_back[18], read_back[19]])
        } else { 0 };
        log::info!(
            "[withdraw] write verify: written={}B read_back={}B read_page_size={} written_page_size={}",
            final_data.len(), read_back.len(), read_page_size,
            updated_pages[page_index].data.len()
        );
        if final_data.len() != read_back.len() {
            log::error!("[withdraw] FILE SIZE MISMATCH! written={} read_back={}",
                final_data.len(), read_back.len());
        }
        if read_back.len() > 64 && final_data.len() > 64 {
            let match_64 = final_data[..64] == read_back[..64];
            let match_all = final_data == read_back;
            log::info!(
                "[withdraw] write compare: header_64={} full={}",
                if match_64 { "MATCH" } else { "DIFFER" },
                if match_all { "MATCH" } else { "DIFFER" }
            );
            if !match_64 {
                log::info!("[withdraw] written header: {:02x?}", &final_data[..64]);
                log::info!("[withdraw] readback header: {:02x?}", &read_back[..64]);
            }
            if !match_all && match_64 {
                // Header matches but body differs — find first differing byte
                for i in 64..final_data.len().min(read_back.len()) {
                    if final_data[i] != read_back[i] {
                        log::info!("[withdraw] first diff at byte {}: written={:02x} read={:02x}", i, final_data[i], read_back[i]);
                        break;
                    }
                }
            }
        }
    }


    // Verify: read back the stash we just wrote and confirm the new item is
    // actually present on the target page. Catches "wrote the file but the
    // content is wrong" cases (e.g. silent corruption, partial flush, lock
    // held by another process). On failure restore from backup.
    {
        let verify_bytes = match std::fs::read(&stash_path) {
            Ok(b) => b,
            Err(e) => {
                let _ = restore_stash_from_backup(&stash_path, &backup_path);
                return Err(format!("Failed to read back stash for verify: {}", e));
            }
        };
        let verify_file = match crate::protocol::d2i::parser::parse_file(&verify_bytes) {
            Ok(f) => f,
            Err(e) => {
                let _ = restore_stash_from_backup(&stash_path, &backup_path);
                return Err(format!("Stash wrote but verify parse failed: {}", e));
            }
        };
        let verify_page = match verify_file.pages.get(page_index) {
            Some(p) => p,
            None => {
                let _ = restore_stash_from_backup(&stash_path, &backup_path);
                return Err(format!("Stash verify: target page {} missing after write", page_index));
            }
        };
        let verify_jm = &verify_page.data[64..];
        let verify_count = if verify_jm.len() >= 4 {
            u16::from_le_bytes([verify_jm[2], verify_jm[3]]) as usize
        } else {
            0
        };
        if verify_count != new_count {
            let _ = restore_stash_from_backup(&stash_path, &backup_path);
            return Err(format!(
                "Stash verify: page {} has count {}, expected {} (item not added). Restored from backup.",
                page_index, verify_count, new_count
            ));
        }
        // Parsed item count check. Pre-write verify already confirmed the data
        // is parseable; a post-write mismatch suggests file-system-level
        // divergence (e.g. antivirus, slow flush). JM count is correct and data
        // was verified before writing — log warning but do not restore backup.
        let parsed_on_page = verify_file.items.iter()
            .filter(|pi| pi.page_index == page_index)
            .count();
        if parsed_on_page < new_count {
            log::warn!(
                "[withdraw] step6 parsed count mismatch: page {} has {} parsed, expected {} \
                 (JM count={}). Pre-write verify OK. Keeping d2i file.",
                page_index, parsed_on_page, new_count, verify_count
            );
        }
        log::info!("[withdraw] step6 verify OK: page {} has {} items (JM) / {} (parsed)", page_index, verify_count, parsed_on_page);
    }

    // 6. Update warehouse DB: partial 路径更新 quantity + raw_bits,full 路径删除行。
    let db = state.db.lock().map_err(|e| {
        let _ = restore_stash_from_backup(&stash_path, &backup_path);
        e.to_string()
    })?;
    let active_profile_key = crate::commands::config::get_active_profile_key(&db).unwrap_or_default();
    if is_partial {
        // Partial:DB 行保留,quantity 减 requested,raw_item_bits 重编码。
        let remaining = max_qty - requested;
        let px = (remaining & 0x0F) as u8;
        let py = ((remaining >> 4) & 0x0F) as u8;
        let new_db_bits = update_item_position(&warehouse_item.raw_item_bits, px, py, Some(remaining as u32));
        let updated = match db.warehouse_partial_withdraw(&item_id, remaining, &new_db_bits) {
            Ok(u) => u,
            Err(e) => {
                drop(db);
                let restore_result = restore_stash_from_backup(&stash_path, &backup_path);
                return Err(match restore_result {
                    Ok(()) => format!("Failed to update warehouse item after partial withdraw, stash restored: {}", e),
                    Err(restore_err) => format!("Failed to update warehouse item after partial withdraw: {}; additionally {}", e, restore_err),
                });
            }
        };
        if !updated {
            drop(db);
            let restore_result = restore_stash_from_backup(&stash_path, &backup_path);
            return Err(match restore_result {
                Ok(()) => "Warehouse item not found in active profile (partial), stash restored".to_string(),
                Err(restore_err) => format!("Warehouse item not found in active profile (partial) and stash restore failed: {}", restore_err),
            });
        }
        log::info!(
            "[withdraw] step6: partial OK, DB quantity {} -> {} (raw_bits re-encoded)",
            warehouse_item.quantity, remaining
        );
    } else {
        // Full withdraw:删除 DB 行(老行为)。
        let removed = match db.warehouse_remove_in_profile(&active_profile_key, &item_id) {
            Ok(removed) => removed,
            Err(e) => {
                drop(db);
                let restore_result = restore_stash_from_backup(&stash_path, &backup_path);
                return Err(match restore_result {
                    Ok(()) => format!("Failed to remove warehouse item after writing stash, stash restored: {}", e),
                    Err(restore_err) => format!("Failed to remove warehouse item after writing stash: {}; additionally {}", e, restore_err),
                });
            }
        };
        if !removed {
            drop(db);
            let restore_result = restore_stash_from_backup(&stash_path, &backup_path);
            return Err(match restore_result {
                Ok(()) => "Warehouse item not found in active profile, stash restored from backup".to_string(),
                Err(restore_err) => format!("Warehouse item not found in active profile and stash restore failed: {}", restore_err),
            });
        }
    }
    if let Err(e) = db.add_transaction("warehouse_withdraw", None, 0,
        &format!(
            "Withdrew {} {} from warehouse ({} left)",
            warehouse_item.item_code, requested, max_qty.saturating_sub(requested)
        )) {
        log::warn!("[withdraw] add_transaction FAILED: {}", e);
    }

    Ok(())
}

/// Remove a warehouse item (without restoring to stash)
#[tauri::command]
pub fn warehouse_remove(state: State<AppState>, item_id: String) -> Result<(), String> {
    let db = state.db.lock().map_err(|e| e.to_string())?;
    let active_profile_key = crate::commands::config::get_active_profile_key(&db).unwrap_or_default();
    let removed = db.warehouse_remove_in_profile(&active_profile_key, &item_id).map_err(|e| e.to_string())?;
    if !removed {
        return Err("Warehouse item not found in active profile".to_string());
    }
    db.add_transaction("warehouse_remove", None, 0, "Removed from warehouse")
        .map_err(|e| e.to_string())?;
    Ok(())
}

/// Unified warehouse search — replaces warehouse_list / warehouse_list_by_*.
/// Only non-None filters are applied; omit all filters to return everything.
#[tauri::command]
pub fn warehouse_backfill_dims(
    state: State<AppState>,
) -> Result<usize, String> {
    warehouse_backfill_dims_inner(&state)
}

pub fn warehouse_backfill_dims_inner(state: &AppState) -> Result<usize, String> {
    let db = state.db.lock().map_err(|e| format!("DB lock poisoned: {}", e))?;
    db.warehouse_backfill_dims().map_err(|e| format!("backfill failed: {}", e))
}

#[tauri::command]
pub fn warehouse_search(
    state: State<AppState>,
    source_character: Option<String>,
    item_kind: Option<String>,
    equipment_slot: Option<String>,
    quality: Option<String>,
    search_text: Option<String>,
    page_name: Option<String>,
    limit: Option<i64>,
    offset: Option<i64>,
) -> Result<Vec<crate::commands::warehouse::WarehouseItemResult>, String> {
    let db = state.db.lock().map_err(|e| e.to_string())?;
    let repos = db.repos();
    let active_profile_key = crate::commands::config::get_active_profile_key(&db).unwrap_or_default();
    let filters = crate::database::repository::warehouse_repo::WarehouseFilters {
        profile_key: (!active_profile_key.is_empty()).then_some(active_profile_key),
        source_character,
        item_kind,
        equipment_slot,
        quality,
        search_text,
        page_name,
        limit,
        offset,
    };
    let items = repos.warehouse.search(&filters).map_err(|e| e.to_string())?;
    // Convert to frontend-friendly format (same as existing warehouse_list paths)
    let result: Vec<crate::commands::warehouse::WarehouseItemResult> = crate::commands::warehouse::localize_warehouse_items(&db, items);
    Ok(result)
}

// ── Default page (per-code + per-item override) ─────────────
//
// Two-layer fallback: per-item override (warehouse_items.override_default_page)
// → per-code default (warehouse_default_pages.page_name). The frontend renders
// the resolved value via `warehouse_resolve_default` and mutates either layer
// with the four *_default commands below. `warehouse_deposit` (above) consults
// `warehouse_get_code_default` when no explicit page_name is supplied.

#[tauri::command]
pub fn warehouse_set_code_default(
    state: State<AppState>,
    item_code: String,
    page_name: String,
) -> Result<(), String> {
    let trimmed_item_code = item_code.trim().to_string();
    if trimmed_item_code.is_empty() {
        return Err("物品 code 不能为空".to_string());
    }
    let validated_page = validate_page_name(&page_name)?;
    let db = state.db.lock().map_err(|e| e.to_string())?;
    db.warehouse_set_code_default(&trimmed_item_code, &validated_page)
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub fn warehouse_clear_code_default(
    state: State<AppState>,
    item_code: String,
) -> Result<bool, String> {
    let trimmed_item_code = item_code.trim().to_string();
    if trimmed_item_code.is_empty() {
        return Err("物品 code 不能为空".to_string());
    }
    let db = state.db.lock().map_err(|e| e.to_string())?;
    db.warehouse_clear_code_default(&trimmed_item_code)
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub fn warehouse_set_item_default(
    state: State<AppState>,
    item_id: String,
    page_name: String,
) -> Result<bool, String> {
    let validated_page = validate_page_name(&page_name)?;
    let db = state.db.lock().map_err(|e| e.to_string())?;
    db.warehouse_set_item_default(&item_id, &validated_page)
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub fn warehouse_clear_item_default(
    state: State<AppState>,
    item_id: String,
) -> Result<bool, String> {
    let db = state.db.lock().map_err(|e| e.to_string())?;
    db.warehouse_clear_item_default(&item_id)
        .map_err(|e| e.to_string())
}

/// Resolve the default page for an item, returning all three layers so the
/// frontend can show "code: 符文页, override: (无), effective: 符文页".
/// `item_id` is optional — stash items don't have one yet, so only the
/// per-code layer applies.
#[tauri::command]
pub fn warehouse_resolve_default(
    state: State<AppState>,
    item_code: String,
    item_id: Option<String>,
) -> Result<DefaultPageInfo, String> {
    let db = state.db.lock().map_err(|e| e.to_string())?;
    let code_default = db
        .warehouse_get_code_default(&item_code)
        .map_err(|e| e.to_string())?;
    let item_default = match item_id.as_deref() {
        Some(id) => db
            .warehouse_get_item_default(id)
            .map_err(|e| e.to_string())?,
        None => None,
    };
    let effective = item_default.as_ref().or(code_default.as_ref()).cloned();
    Ok(DefaultPageInfo {
        item_code,
        code_default,
        item_default,
        effective,
    })
}
