/// Auto-generated from game TXT files (D2R 3.2-92777 + D2RMM)

/// Map of item type codes to their display metadata
/// Format: (code, name, kind, icon_path)
#[rustfmt::skip]
pub const ITEM_CODE_MAP: &[(&str, &str, &str, &str)] = &[
  ("0sc", "Scroll of Knowledge", "misc", "/assets/img/items/0sc.webp"),
  ("2ax", "Double Axe", "weapon", "/assets/img/items/2ax.webp"),
  ("2hs", "Two-Handed Sword", "weapon", "/assets/img/items/2hs.webp"),
  ("6bs", "Shillelagh", "weapon", "/assets/img/items/6bs.webp"),
  ("6cb", "Great Bow", "weapon", "/assets/img/items/6cb.webp"),
  ("6cs", "Elder Staff", "weapon", "/assets/img/items/6cs.webp"),
  ("6hb", "Blade Bow", "weapon", "/assets/img/items/6hb.webp"),
  ("6hx", "Colossus Crossbow", "weapon", "/assets/img/items/6hx.webp"),
  ("6l7", "Crusader Bow", "weapon", "/assets/img/items/6l7.webp"),
  ("6lb", "Shadow Bow", "weapon", "/assets/img/items/6lb.webp"),
  ("6ls", "Stalagmite", "weapon", "/assets/img/items/6ls.webp"),
  ("6lw", "Hydra Bow", "weapon", "/assets/img/items/6lw.webp"),
  ("6lx", "Pellet Bow", "weapon", "/assets/img/items/6lx.webp"),
  ("6mx", "Gorgon Crossbow", "weapon", "/assets/img/items/6mx.webp"),
  ("6rx", "Demon Crossbow", "weapon", "/assets/img/items/6rx.webp"),
  ("6s7", "Diamond Bow", "weapon", "/assets/img/items/6s7.webp"),
  ("6sb", "Spider Bow", "weapon", "/assets/img/items/6sb.webp"),
  ("6ss", "Walking Stick", "weapon", "/assets/img/items/6ss.webp"),
  ("6sw", "Ward Bow", "weapon", "/assets/img/items/6sw.webp"),
  ("6ws", "Archon Staff", "weapon", "/assets/img/items/6ws.webp"),
  ("72a", "Ettin Axe", "weapon", "/assets/img/items/72a.webp"),
  ("72h", "Legend Sword", "weapon", "/assets/img/items/72h.webp"),
  ("7ar", "Suwayyah", "weapon", "/assets/img/items/7ar.webp"),
  ("7ax", "Small Crescent", "weapon", "/assets/img/items/7ax.webp"),
  ("7b7", "Champion Sword", "weapon", "/assets/img/items/7b7.webp"),
  ("7b8", "Winged Axe", "weapon", "/assets/img/items/7b8.webp"),
  ("7ba", "Silver-edged Axe", "weapon", "/assets/img/items/7ba.webp"),
  ("7bk", "Winged Knife", "weapon", "/assets/img/items/7bk.webp"),
  ("7bl", "Legend Spike", "weapon", "/assets/img/items/7bl.webp"),
  ("7br", "Mancatcher", "weapon", "/assets/img/items/7br.webp"),
  ("7bs", "Conquest Sword", "weapon", "/assets/img/items/7bs.webp"),
  ("7bt", "Decapitator", "weapon", "/assets/img/items/7bt.webp"),
  ("7bw", "Lich Wand", "weapon", "/assets/img/items/7bw.webp"),
  ("7cl", "Truncheon", "weapon", "/assets/img/items/7cl.webp"),
  ("7cm", "Highland Blade", "weapon", "/assets/img/items/7cm.webp"),
  ("7cr", "Phase Blade", "weapon", "/assets/img/items/7cr.webp"),
  ("7cs", "Battle Cestus", "weapon", "/assets/img/items/7cs.webp"),
  ("7dg", "Bone Knife", "weapon", "/assets/img/items/7dg.webp"),
  ("7di", "Mithral Point", "weapon", "/assets/img/items/7di.webp"),
  ("7fb", "Colossal Sword", "weapon", "/assets/img/items/7fb.webp"),
  ("7fc", "Hydra Edge", "weapon", "/assets/img/items/7fc.webp"),
  ("7fl", "Scourge", "weapon", "/assets/img/items/7fl.webp"),
  ("7ga", "Champion Axe", "weapon", "/assets/img/items/7ga.webp"),
  ("7gd", "Colossus Blade", "weapon", "/assets/img/items/7gd.webp"),
  ("7gi", "Glorious Axe", "weapon", "/assets/img/items/7gi.webp"),
  ("7gl", "Ghost Glaive", "weapon", "/assets/img/items/7gl.webp"),
  ("7gm", "Thunder Maul", "weapon", "/assets/img/items/7gm.webp"),
  ("7gs", "Balrog Blade", "weapon", "/assets/img/items/7gs.webp"),
  ("7gw", "Unearthed Wand", "weapon", "/assets/img/items/7gw.webp"),
  ("7h7", "Great Poleaxe", "weapon", "/assets/img/items/7h7.webp"),
  ("7ha", "Tomahawk", "weapon", "/assets/img/items/7ha.webp"),
  ("7ja", "Hyperion Javelin", "weapon", "/assets/img/items/7ja.webp"),
  ("7kr", "Fanged Knife", "weapon", "/assets/img/items/7kr.webp"),
  ("7la", "Feral Axe", "weapon", "/assets/img/items/7la.webp"),
  ("7ls", "Cryptic Sword", "weapon", "/assets/img/items/7ls.webp"),
  ("7lw", "Feral Claws", "weapon", "/assets/img/items/7lw.webp"),
  ("7m7", "Ogre Maul", "weapon", "/assets/img/items/7m7.webp"),
  ("7ma", "Reinforced Mace", "weapon", "/assets/img/items/7ma.webp"),
  ("7mp", "War Spike", "weapon", "/assets/img/items/7mp.webp"),
  ("7mt", "Devil Star", "weapon", "/assets/img/items/7mt.webp"),
  ("7o7", "Ogre Axe", "weapon", "/assets/img/items/7o7.webp"),
  ("7p7", "War Pike", "weapon", "/assets/img/items/7p7.webp"),
  ("7pa", "Cryptic Axe", "weapon", "/assets/img/items/7pa.webp"),
  ("7pi", "Stygian Pilum", "weapon", "/assets/img/items/7pi.webp"),
  ("7qr", "Scissors Suwayyah", "weapon", "/assets/img/items/7qr.webp"),
  ("7qs", "Seraph Rod", "weapon", "/assets/img/items/7qs.webp"),
  ("7s7", "Balrog Spear", "weapon", "/assets/img/items/7s7.webp"),
  ("7s8", "Thresher", "weapon", "/assets/img/items/7s8.webp"),
  ("7sb", "Elegant Blade", "weapon", "/assets/img/items/7sb.webp"),
  ("7sc", "Mighty Scepter", "weapon", "/assets/img/items/7sc.webp"),
  ("7sm", "Ataghan", "weapon", "/assets/img/items/7sm.webp"),
  ("7sp", "Tyrant Club", "weapon", "/assets/img/items/7sp.webp"),
  ("7sr", "Hyperion Spear", "weapon", "/assets/img/items/7sr.webp"),
  ("7ss", "Falcata", "weapon", "/assets/img/items/7ss.webp"),
  ("7st", "Ghost Spear", "weapon", "/assets/img/items/7st.webp"),
  ("7ta", "Flying Axe", "weapon", "/assets/img/items/7ta.webp"),
  ("7tk", "Flying Knife", "weapon", "/assets/img/items/7tk.webp"),
  ("7tr", "Stygian Pike", "weapon", "/assets/img/items/7tr.webp"),
  ("7ts", "Winged Harpoon", "weapon", "/assets/img/items/7ts.webp"),
  ("7tw", "Runic Talons", "weapon", "/assets/img/items/7tw.webp"),
  ("7vo", "Colossus Voulge", "weapon", "/assets/img/items/7vo.webp"),
  ("7wa", "Berserker Axe", "weapon", "/assets/img/items/7wa.webp"),
  ("7wb", "Wrist Sword", "weapon", "/assets/img/items/7wb.webp"),
  ("7wc", "Giant Thresher", "weapon", "/assets/img/items/7wc.webp"),
  ("7wd", "Mythical Sword", "weapon", "/assets/img/items/7wd.webp"),
  ("7wh", "Legendary Mallet", "weapon", "/assets/img/items/7wh.webp"),
  ("7wn", "Polished Wand", "weapon", "/assets/img/items/7wn.webp"),
  ("7ws", "Caduceus", "weapon", "/assets/img/items/7ws.webp"),
  ("7xf", "War Fist", "weapon", "/assets/img/items/7xf.webp"),
  ("7yw", "Ghost Wand", "weapon", "/assets/img/items/7yw.webp"),
  ("8bs", "Gothic Staff", "weapon", "/assets/img/items/8bs.webp"),
  ("8cb", "Double Bow", "weapon", "/assets/img/items/8cb.webp"),
  ("8cs", "Cedar Staff", "weapon", "/assets/img/items/8cs.webp"),
  ("8hb", "Razor Bow", "weapon", "/assets/img/items/8hb.webp"),
  ("8hx", "Ballista", "weapon", "/assets/img/items/8hx.webp"),
  ("8l8", "Long Siege Bow", "weapon", "/assets/img/items/8l8.webp"),
  ("8lb", "Cedar Bow", "weapon", "/assets/img/items/8lb.webp"),
  ("8ls", "Quarterstaff", "weapon", "/assets/img/items/8ls.webp"),
  ("8lw", "Gothic Bow", "weapon", "/assets/img/items/8lw.webp"),
  ("8lx", "Arbalest", "weapon", "/assets/img/items/8lx.webp"),
  ("8mx", "Siege Crossbow", "weapon", "/assets/img/items/8mx.webp"),
  ("8rx", "Chu-Ko-Nu", "weapon", "/assets/img/items/8rx.webp"),
  ("8s8", "Short Siege Bow", "weapon", "/assets/img/items/8s8.webp"),
  ("8sb", "Edge Bow", "weapon", "/assets/img/items/8sb.webp"),
  ("8ss", "Jo Staff", "weapon", "/assets/img/items/8ss.webp"),
  ("8sw", "Rune Bow", "weapon", "/assets/img/items/8sw.webp"),
  ("8ws", "Rune Staff", "weapon", "/assets/img/items/8ws.webp"),
  ("92a", "Twin Axe", "weapon", "/assets/img/items/92a.webp"),
  ("92h", "Espandon", "weapon", "/assets/img/items/92h.webp"),
  ("9ar", "Quhab", "weapon", "/assets/img/items/9ar.webp"),
  ("9ax", "Cleaver", "weapon", "/assets/img/items/9ax.webp"),
  ("9b7", "Lochaber Axe", "weapon", "/assets/img/items/9b7.webp"),
  ("9b8", "Hurlbat", "weapon", "/assets/img/items/9b8.webp"),
  ("9b9", "Gothic Sword", "weapon", "/assets/img/items/9b9.webp"),
  ("9ba", "Bearded Axe", "weapon", "/assets/img/items/9ba.webp"),
  ("9bk", "War Dart", "weapon", "/assets/img/items/9bk.webp"),
  ("9bl", "Stilleto", "weapon", "/assets/img/items/9bl.webp"),
  ("9br", "War Fork", "weapon", "/assets/img/items/9br.webp"),
  ("9bs", "Battle Sword", "weapon", "/assets/img/items/9bs.webp"),
  ("9bt", "Tabar", "weapon", "/assets/img/items/9bt.webp"),
  ("9bw", "Tomb Wand", "weapon", "/assets/img/items/9bw.webp"),
  ("9cl", "Cudgel", "weapon", "/assets/img/items/9cl.webp"),
  ("9cm", "Dacian Falx", "weapon", "/assets/img/items/9cm.webp"),
  ("9cr", "Dimensional Blade", "weapon", "/assets/img/items/9cr.webp"),
  ("9cs", "Hand Scythe", "weapon", "/assets/img/items/9cs.webp"),
  ("9dg", "Poignard", "weapon", "/assets/img/items/9dg.webp"),
  ("9di", "Rondel", "weapon", "/assets/img/items/9di.webp"),
  ("9fb", "Zweihander", "weapon", "/assets/img/items/9fb.webp"),
  ("9fc", "Tulwar", "weapon", "/assets/img/items/9fc.webp"),
  ("9fl", "Knout", "weapon", "/assets/img/items/9fl.webp"),
  ("9ga", "Gothic Axe", "weapon", "/assets/img/items/9ga.webp"),
  ("9gd", "Executioner Sword", "weapon", "/assets/img/items/9gd.webp"),
  ("9gi", "Ancient Axe", "weapon", "/assets/img/items/9gi.webp"),
  ("9gl", "Spiculum", "weapon", "/assets/img/items/9gl.webp"),
  ("9gm", "Martel de Fer", "weapon", "/assets/img/items/9gm.webp"),
  ("9gs", "Tusk Sword", "weapon", "/assets/img/items/9gs.webp"),
  ("9gw", "Grave Wand", "weapon", "/assets/img/items/9gw.webp"),
  ("9h9", "Bec-de-Corbin", "weapon", "/assets/img/items/9h9.webp"),
  ("9ha", "Hatchet", "weapon", "/assets/img/items/9ha.webp"),
  ("9ja", "War Javelin", "weapon", "/assets/img/items/9ja.webp"),
  ("9kr", "Cinquedeas", "weapon", "/assets/img/items/9kr.webp"),
  ("9la", "Military Axe", "weapon", "/assets/img/items/9la.webp"),
  ("9ls", "Rune Sword", "weapon", "/assets/img/items/9ls.webp"),
  ("9lw", "Greater Claws", "weapon", "/assets/img/items/9lw.webp"),
  ("9m9", "War Club", "weapon", "/assets/img/items/default_weapon.webp"),
  ("9ma", "Flanged Mace", "weapon", "/assets/img/items/9ma.webp"),
  ("9mp", "Crowbill", "weapon", "/assets/img/items/9mp.webp"),
  ("9mt", "Jagged Star", "weapon", "/assets/img/items/9mt.webp"),
  ("9p9", "Lance", "weapon", "/assets/img/items/9p9.webp"),
  ("9pa", "Partizan", "weapon", "/assets/img/items/9pa.webp"),
  ("9pi", "Great Pilum", "weapon", "/assets/img/items/9pi.webp"),
  ("9qr", "Scissors Quhab", "weapon", "/assets/img/items/9qr.webp"),
  ("9qs", "Holy Water Sprinkler", "weapon", "/assets/img/items/9qs.webp"),
  ("9s8", "Battle Scythe", "weapon", "/assets/img/items/9s8.webp"),
  ("9s9", "Simbilan", "weapon", "/assets/img/items/9s9.webp"),
  ("9sb", "Shamshir", "weapon", "/assets/img/items/9sb.webp"),
  ("9sc", "Rune Scepter", "weapon", "/assets/img/items/9sc.webp"),
  ("9sm", "Cutlass", "weapon", "/assets/img/items/9sm.webp"),
  ("9sp", "Barbed Club", "weapon", "/assets/img/items/9sp.webp"),
  ("9sr", "War Spear", "weapon", "/assets/img/items/9sr.webp"),
  ("9ss", "Gladius", "weapon", "/assets/img/items/9ss.webp"),
  ("9st", "Yari", "weapon", "/assets/img/items/9st.webp"),
  ("9ta", "Francisca", "weapon", "/assets/img/items/9ta.webp"),
  ("9tk", "Battle Dart", "weapon", "/assets/img/items/9tk.webp"),
  ("9tr", "Fuscina", "weapon", "/assets/img/items/9tr.webp"),
  ("9ts", "Harpoon", "weapon", "/assets/img/items/9ts.webp"),
  ("9tw", "Greater Talons", "weapon", "/assets/img/items/9tw.webp"),
  ("9vo", "Bill", "weapon", "/assets/img/items/9vo.webp"),
  ("9wa", "Naga", "weapon", "/assets/img/items/9wa.webp"),
  ("9wb", "Wrist Spike", "weapon", "/assets/img/items/9wb.webp"),
  ("9wc", "Grim Scythe", "weapon", "/assets/img/items/9wc.webp"),
  ("9wd", "Ancient Sword", "weapon", "/assets/img/items/9wd.webp"),
  ("9wh", "Battle Hammer", "weapon", "/assets/img/items/9wh.webp"),
  ("9wn", "Burnt Wand", "weapon", "/assets/img/items/9wn.webp"),
  ("9ws", "Divine Scepter", "weapon", "/assets/img/items/9ws.webp"),
  ("9xf", "Fascia", "weapon", "/assets/img/items/9xf.webp"),
  ("9yw", "Petrified Wand", "weapon", "/assets/img/items/9yw.webp"),
  ("aar", "Ancient Armor", "armor", "/assets/img/items/aar.webp"),
  ("am1", "Stag Bow", "weapon", "/assets/img/items/am1.webp"),
  ("am2", "Reflex Bow", "weapon", "/assets/img/items/am2.webp"),
  ("am3", "Maiden Spear", "weapon", "/assets/img/items/am3.webp"),
  ("am4", "Maiden Pike", "weapon", "/assets/img/items/am4.webp"),
  ("am5", "Maiden Javelin", "weapon", "/assets/img/items/am5.webp"),
  ("am6", "Ashwood Bow", "weapon", "/assets/img/items/am6.webp"),
  ("am7", "Ceremonial Bow", "weapon", "/assets/img/items/am7.webp"),
  ("am8", "Ceremonial Spear", "weapon", "/assets/img/items/am8.webp"),
  ("am9", "Ceremonial Pike", "weapon", "/assets/img/items/am9.webp"),
  ("ama", "Ceremonial Javelin", "weapon", "/assets/img/items/ama.webp"),
  ("amb", "Matriarchal Bow", "weapon", "/assets/img/items/amb.webp"),
  ("amc", "Grand Matron Bow", "weapon", "/assets/img/items/amc.webp"),
  ("amd", "Matriarchal Spear", "weapon", "/assets/img/items/amd.webp"),
  ("ame", "Matriarchal Pike", "weapon", "/assets/img/items/ame.webp"),
  ("amf", "Matriarchal Javelin", "weapon", "/assets/img/items/amf.webp"),
  ("amu", "Amulet", "misc", "/assets/img/items/amu.webp"),
  ("aqv", "Arrows", "misc", "/assets/img/items/aqv.webp"),
  ("ass", "Book of Skill", "misc", "/assets/img/items/ass.webp"),
  ("axe", "Axe", "weapon", "/assets/img/items/axe.webp"),
  ("axf", "Hatchet Hands", "weapon", "/assets/img/items/axf.webp"),
  ("ba1", "Jawbone Cap", "armor", "/assets/img/items/ba1.webp"),
  ("ba2", "Fanged Helm", "armor", "/assets/img/items/ba2.webp"),
  ("ba3", "Horned Helm", "armor", "/assets/img/items/ba3.webp"),
  ("ba4", "Assault Helmet", "armor", "/assets/img/items/ba4.webp"),
  ("ba5", "Avenger Guard", "armor", "/assets/img/items/ba5.webp"),
  ("ba6", "Jawbone Visor", "armor", "/assets/img/items/ba6.webp"),
  ("ba7", "Lion Helm", "armor", "/assets/img/items/ba7.webp"),
  ("ba8", "Rage Mask", "armor", "/assets/img/items/ba8.webp"),
  ("ba9", "Savage Helmet", "armor", "/assets/img/items/ba9.webp"),
  ("baa", "Slayer Guard", "armor", "/assets/img/items/baa.webp"),
  ("bab", "Carnage Helm", "armor", "/assets/img/items/bab.webp"),
  ("bac", "Fury Visor", "armor", "/assets/img/items/bac.webp"),
  ("bad", "Destroyer Helm", "armor", "/assets/img/items/bad.webp"),
  ("bae", "Conqueror Crown", "armor", "/assets/img/items/bae.webp"),
  ("baf", "Guardian Crown", "armor", "/assets/img/items/baf.webp"),
  ("bal", "Balanced Axe", "weapon", "/assets/img/items/bal.webp"),
  ("bar", "Bardiche", "weapon", "/assets/img/items/bar.webp"),
  ("bax", "Broad Axe", "weapon", "/assets/img/items/bax.webp"),
  ("bbb", "Lam Esen's Tome", "misc", "/assets/img/items/bbb.webp"),
  ("bet", "Burning Essence of Terror", "essence", "/assets/img/items/bet.webp"),
  ("bey", "Baal's Eye", "misc", "/assets/img/items/bey.webp"),
  ("bhm", "Bone Helm", "armor", "/assets/img/items/bhm.webp"),
  ("bkd", "Key to the Cairn Stones", "misc", "/assets/img/items/default_misc.webp"),
  ("bkf", "Balanced Knife", "weapon", "/assets/img/items/bkf.webp"),
  ("bks", "Scroll of Inifuss", "misc", "/assets/img/items/default_misc.webp"),
  ("bld", "Blade", "weapon", "/assets/img/items/bld.webp"),
  ("box", "Horadric Cube", "misc", "/assets/img/items/box.webp"),
  ("bpl", "Large Blue Potion", "misc", "/assets/img/items/bpl.webp"),
  ("bps", "Small Blue Potion", "misc", "/assets/img/items/bps.webp"),
  ("brn", "Brandistock", "weapon", "/assets/img/items/brn.webp"),
  ("brs", "Breast Plate", "armor", "/assets/img/items/brs.webp"),
  ("brz", "Brain", "misc", "/assets/img/items/default_misc.webp"),
  ("bsd", "Broad Sword", "weapon", "/assets/img/items/bsd.webp"),
  ("bsh", "Bone Shield", "armor", "/assets/img/items/bsh.webp"),
  ("bst", "Battle Staff", "weapon", "/assets/img/items/bst.webp"),
  ("bsw", "Bastard Sword", "weapon", "/assets/img/items/bsw.webp"),
  ("btl", "Blade Talons", "weapon", "/assets/img/items/default_weapon.webp"),
  ("btx", "Battle Axe", "weapon", "/assets/img/items/btx.webp"),
  ("buc", "Buckler", "armor", "/assets/img/items/buc.webp"),
  ("bwn", "Bone Wand", "weapon", "/assets/img/items/bwn.webp"),
  ("cap", "Cap", "armor", "/assets/img/items/cap.webp"),
  ("cbw", "Composite Bow", "weapon", "/assets/img/items/cbw.webp"),
  ("ceh", "Charged Essense of Hatred", "essence", "/assets/img/items/ceh.webp"),
  ("ces", "Cestus", "weapon", "/assets/img/items/default_weapon.webp"),
  ("chn", "Chain Mail", "armor", "/assets/img/items/chn.webp"),
  ("ci0", "Circlet", "armor", "/assets/img/items/ci0.webp"),
  ("ci1", "Coronet", "armor", "/assets/img/items/ci1.webp"),
  ("ci2", "Tiara", "armor", "/assets/img/items/ci2.webp"),
  ("ci3", "Diadem", "armor", "/assets/img/items/ci3.webp"),
  ("cjw", "Colossal Jewel", "misc", "/assets/img/items/default_misc.webp"),
  ("clb", "Club", "weapon", "/assets/img/items/clb.webp"),
  ("clm", "Claymore", "weapon", "/assets/img/items/clm.webp"),
  ("clw", "Claws", "weapon", "/assets/img/items/clw.webp"),
  ("cm1", "Small Charm", "misc", "/assets/img/items/default_misc.webp"),
  ("cm2", "Large Charm", "misc", "/assets/img/items/default_misc.webp"),
  ("cm3", "Grand Charm", "misc", "/assets/img/items/default_misc.webp"),
  ("cqv", "Bolts", "misc", "/assets/img/items/cqv.webp"),
  ("crn", "Crown", "armor", "/assets/img/items/crn.webp"),
  ("crs", "Crystal Sword", "weapon", "/assets/img/items/crs.webp"),
  ("cst", "Gnarled Staff", "weapon", "/assets/img/items/cst.webp"),
  ("d33", "Decoy Gidbinn", "weapon", "/assets/img/items/d33.webp"),
  ("dgr", "Dagger", "weapon", "/assets/img/items/dgr.webp"),
  ("dhn", "Diablo's Horn", "misc", "/assets/img/items/default_misc.webp"),
  ("dir", "Dirk", "weapon", "/assets/img/items/dir.webp"),
  ("dr1", "Wolf Head", "armor", "/assets/img/items/dr1.webp"),
  ("dr2", "Hawk Helm", "armor", "/assets/img/items/dr2.webp"),
  ("dr3", "Antlers", "armor", "/assets/img/items/dr3.webp"),
  ("dr4", "Falcon Mask", "armor", "/assets/img/items/dr4.webp"),
  ("dr5", "Spirit Mask", "armor", "/assets/img/items/dr5.webp"),
  ("dr6", "Alpha Helm", "armor", "/assets/img/items/default_armor.webp"),
  ("dr7", "Griffon Headress", "armor", "/assets/img/items/default_armor.webp"),
  ("dr8", "Hunter's Guise", "armor", "/assets/img/items/default_armor.webp"),
  ("dr9", "Sacred Feathers", "armor", "/assets/img/items/default_armor.webp"),
  ("dra", "Totemic Mask", "armor", "/assets/img/items/default_armor.webp"),
  ("drb", "Blood Spirit", "armor", "/assets/img/items/default_armor.webp"),
  ("drc", "Sun Spirit", "armor", "/assets/img/items/default_armor.webp"),
  ("drd", "Earth Spirit", "armor", "/assets/img/items/default_armor.webp"),
  ("dre", "Sky Spirit", "armor", "/assets/img/items/default_armor.webp"),
  ("drf", "Dream Spirit", "armor", "/assets/img/items/default_armor.webp"),
  ("ear", "Ear", "misc", "/assets/img/items/ear.webp"),
  ("elx", "Elixir", "misc", "/assets/img/items/default_misc.webp"),
  ("eyz", "Eye", "misc", "/assets/img/items/default_misc.webp"),
  ("fed", "Festering Essence of Destruction", "essence", "/assets/img/items/fed.webp"),
  ("fhl", "Full Helm", "armor", "/assets/img/items/fhl.webp"),
  ("fla", "Flail", "weapon", "/assets/img/items/fla.webp"),
  ("flb", "Flamberge", "weapon", "/assets/img/items/flb.webp"),
  ("flc", "Falchion", "weapon", "/assets/img/items/flc.webp"),
  ("fld", "Field Plate", "armor", "/assets/img/items/fld.webp"),
  ("flg", "Flag", "misc", "/assets/img/items/default_misc.webp"),
  ("fng", "Fang", "misc", "/assets/img/items/default_misc.webp"),
  ("ful", "Full Plate Mail", "armor", "/assets/img/items/ful.webp"),
  ("g33", "The Gidbinn", "weapon", "/assets/img/items/g33.webp"),
  ("g34", "The Golden Bird", "misc", "/assets/img/items/default_misc.webp"),
  ("gax", "Great Axe", "weapon", "/assets/img/items/gax.webp"),
  ("gcb", "Chipped Sapphire", "gem", "/assets/img/items/default_gem.webp"),
  ("gcg", "Chipped Emerald", "gem", "/assets/img/items/default_gem.webp"),
  ("gcr", "Chipped Ruby", "gem", "/assets/img/items/default_gem.webp"),
  ("gcv", "Chipped Amethyst", "gem", "/assets/img/items/gcv.webp"),
  ("gcw", "Chipped Diamond", "gem", "/assets/img/items/default_gem.webp"),
  ("gcy", "Chipped Topaz", "gem", "/assets/img/items/default_gem.webp"),
  ("gfb", "Flawed Sapphire", "gem", "/assets/img/items/default_gem.webp"),
  ("gfg", "Flawed Emerald", "gem", "/assets/img/items/default_gem.webp"),
  ("gfr", "Flawed Ruby", "gem", "/assets/img/items/default_gem.webp"),
  ("gfv", "Flawed Amethyst", "gem", "/assets/img/items/default_gem.webp"),
  ("gfw", "Flawed Diamond", "gem", "/assets/img/items/default_gem.webp"),
  ("gfy", "Flawed Topaz", "gem", "/assets/img/items/default_gem.webp"),
  ("ghm", "Great Helm", "armor", "/assets/img/items/ghm.webp"),
  ("gis", "Giant Sword", "weapon", "/assets/img/items/gis.webp"),
  ("gix", "Giant Axe", "weapon", "/assets/img/items/gix.webp"),
  ("glb", "Flawless Sapphire", "gem", "/assets/img/items/default_gem.webp"),
  ("gld", "Gold", "misc", "/assets/img/items/gld.webp"),
  ("glg", "Flawless Emerald", "gem", "/assets/img/items/default_gem.webp"),
  ("glr", "Flawless Ruby", "gem", "/assets/img/items/default_gem.webp"),
  ("glv", "Glaive", "weapon", "/assets/img/items/glv.webp"),
  ("glw", "Flawless Diamond", "gem", "/assets/img/items/default_gem.webp"),
  ("gly", "Flawless Topaz", "gem", "/assets/img/items/default_gem.webp"),
  ("gma", "Great Maul", "weapon", "/assets/img/items/gma.webp"),
  ("gpb", "Perfect Sapphire", "gem", "/assets/img/items/default_gem.webp"),
  ("gpg", "Perfect Emerald", "gem", "/assets/img/items/default_gem.webp"),
  ("gpl", "Strangling Gas Potion", "weapon", "/assets/img/items/gpl.webp"),
  ("gpm", "Choking Gas Potion", "weapon", "/assets/img/items/gpm.webp"),
  ("gpr", "Perfect Ruby", "gem", "/assets/img/items/default_gem.webp"),
  ("gps", "Rancid Gas Potion", "weapon", "/assets/img/items/gps.webp"),
  ("gpv", "Perfect Amethyst", "gem", "/assets/img/items/default_gem.webp"),
  ("gpw", "Perfect Diamond", "gem", "/assets/img/items/default_gem.webp"),
  ("gpy", "Perfect Topaz", "gem", "/assets/img/items/default_gem.webp"),
  ("gsb", "Sapphire", "gem", "/assets/img/items/gsb.webp"),
  ("gsc", "Grand Scepter", "weapon", "/assets/img/items/gsc.webp"),
  ("gsd", "Great Sword", "weapon", "/assets/img/items/gsd.webp"),
  ("gsg", "Emerald", "gem", "/assets/img/items/gsg.webp"),
  ("gsr", "Ruby", "gem", "/assets/img/items/gsr.webp"),
  ("gsv", "Amethyst", "gem", "/assets/img/items/gsv.webp"),
  ("gsw", "Diamond", "gem", "/assets/img/items/gsw.webp"),
  ("gsy", "Topaz", "gem", "/assets/img/items/gsy.webp"),
  ("gth", "Gothic Plate", "armor", "/assets/img/items/gth.webp"),
  ("gts", "Gothic Shield", "armor", "/assets/img/items/gts.webp"),
  ("gwn", "Grim Wand", "weapon", "/assets/img/items/gwn.webp"),
  ("gzv", "Flawless Amethyst", "gem", "/assets/img/items/default_gem.webp"),
  ("hal", "Halberd", "weapon", "/assets/img/items/hal.webp"),
  ("hax", "Hand Axe", "weapon", "/assets/img/items/hax.webp"),
  ("hbl", "Plated Belt", "armor", "/assets/img/items/hbl.webp"),
  ("hbt", "Greaves", "armor", "/assets/img/items/hbt.webp"),
  ("hbw", "Hunter's Bow", "weapon", "/assets/img/items/hbw.webp"),
  ("hdm", "Horadric Malus", "weapon", "/assets/img/items/default_weapon.webp"),
  ("hfh", "Hellforge Hammer", "weapon", "/assets/img/items/hfh.webp"),
  ("hgl", "Gauntlets", "armor", "/assets/img/items/hgl.webp"),
  ("hla", "Hard Leather Armor", "armor", "/assets/img/items/hla.webp"),
  ("hlm", "Helm", "armor", "/assets/img/items/hlm.webp"),
  ("hp1", "Minor Healing Potion", "misc", "/assets/img/items/hp1.webp"),
  ("hp2", "Light Healing Potion", "misc", "/assets/img/items/hp2.webp"),
  ("hp3", "Healing Potion", "misc", "/assets/img/items/hp3.webp"),
  ("hp4", "Greater Healing Potion", "misc", "/assets/img/items/hp4.webp"),
  ("hp5", "Super Healing Potion", "misc", "/assets/img/items/hp5.webp"),
  ("hpf", "Full Healing Potion", "misc", "/assets/img/items/hpf.webp"),
  ("hpo", "Healing Potion", "misc", "/assets/img/items/hpo.webp"),
  ("hrb", "Herb", "misc", "/assets/img/items/hrb.webp"),
  ("hrn", "Horn", "misc", "/assets/img/items/default_misc.webp"),
  ("hrt", "Heart", "misc", "/assets/img/items/hrt.webp"),
  ("hst", "Horadric Staff", "weapon", "/assets/img/items/hst.webp"),
  ("hxb", "Heavy Crossbow", "weapon", "/assets/img/items/hxb.webp"),
  ("ibk", "Tome of Identify", "misc", "/assets/img/items/default_misc.webp"),
  ("ice", "Malah's Potion", "misc", "/assets/img/items/default_misc.webp"),
  ("isc", "Scroll of Identify", "misc", "/assets/img/items/default_misc.webp"),
  ("j34", "A Jade Figurine", "misc", "/assets/img/items/default_misc.webp"),
  ("jav", "Javelin", "weapon", "/assets/img/items/jav.webp"),
  ("jaw", "Jawbone", "misc", "/assets/img/items/jaw.webp"),
  ("jew", "Jewel", "misc", "/assets/img/items/default_misc.webp"),
  ("key", "Key", "key", "/assets/img/items/key.webp"),
  ("kit", "Kite Shield", "armor", "/assets/img/items/kit.webp"),
  ("kri", "Kriss", "weapon", "/assets/img/items/default_weapon.webp"),
  ("ktr", "Katar", "weapon", "/assets/img/items/ktr.webp"),
  ("lax", "Large Axe", "weapon", "/assets/img/items/lax.webp"),
  ("lbb", "Long Battle Bow", "weapon", "/assets/img/items/lbb.webp"),
  ("lbl", "Sash", "armor", "/assets/img/items/lbl.webp"),
  ("lbt", "Boots", "armor", "/assets/img/items/lbt.webp"),
  ("lbw", "Long Bow", "weapon", "/assets/img/items/lbw.webp"),
  ("lea", "Leather Armor", "armor", "/assets/img/items/lea.webp"),
  ("leg", "Wirt's Leg", "weapon", "/assets/img/items/leg.webp"),
  ("lgl", "Leather Gloves", "armor", "/assets/img/items/lgl.webp"),
  ("lrg", "Large Shield", "armor", "/assets/img/items/lrg.webp"),
  ("lsd", "Long Sword", "weapon", "/assets/img/items/lsd.webp"),
  ("lst", "Long Staff", "weapon", "/assets/img/items/lst.webp"),
  ("ltp", "Light Plate", "armor", "/assets/img/items/ltp.webp"),
  ("luv", "The Black Tower Key", "key", "/assets/img/items/default_key.webp"),
  ("lwb", "Long War Bow", "weapon", "/assets/img/items/lwb.webp"),
  ("lxb", "Light Crossbow", "weapon", "/assets/img/items/lxb.webp"),
  ("mac", "Mace", "weapon", "/assets/img/items/mac.webp"),
  ("mau", "Maul", "weapon", "/assets/img/items/mau.webp"),
  ("mbl", "Belt", "armor", "/assets/img/items/mbl.webp"),
  ("mbr", "Mephisto's Brain", "misc", "/assets/img/items/default_misc.webp"),
  ("mbt", "Chain Boots", "armor", "/assets/img/items/mbt.webp"),
  ("mgl", "Chain Gloves", "armor", "/assets/img/items/mgl.webp"),
  ("mp1", "Minor Mana Potion", "misc", "/assets/img/items/mp1.webp"),
  ("mp2", "Light Mana Potion", "misc", "/assets/img/items/mp2.webp"),
  ("mp3", "Mana Potion", "misc", "/assets/img/items/mp3.webp"),
  ("mp4", "Greater Mana Potion", "misc", "/assets/img/items/mp4.webp"),
  ("mp5", "Super Mana Potion", "misc", "/assets/img/items/mp5.webp"),
  ("mpf", "Full Mana Potion", "misc", "/assets/img/items/mpf.webp"),
  ("mpi", "Military Pick", "weapon", "/assets/img/items/mpi.webp"),
  ("mpo", "Mana Potion", "misc", "/assets/img/items/mpo.webp"),
  ("msf", "Staff of Kings", "weapon", "/assets/img/items/msf.webp"),
  ("msk", "Mask", "armor", "/assets/img/items/msk.webp"),
  ("mss", "Mephisto's Soulstone", "misc", "/assets/img/items/mss.webp"),
  ("mst", "Morning Star", "weapon", "/assets/img/items/mst.webp"),
  ("mxb", "Crossbow", "weapon", "/assets/img/items/mxb.webp"),
  ("ne1", "Preserved Head", "armor", "/assets/img/items/ne1.webp"),
  ("ne2", "Zombie Head", "armor", "/assets/img/items/ne2.webp"),
  ("ne3", "Unraveller Head", "armor", "/assets/img/items/ne3.webp"),
  ("ne4", "Gargoyle Head", "armor", "/assets/img/items/ne4.webp"),
  ("ne5", "Demon Head", "armor", "/assets/img/items/ne5.webp"),
  ("ne6", "Mummified Trophy", "armor", "/assets/img/items/default_armor.webp"),
  ("ne7", "Fetish Trophy", "armor", "/assets/img/items/default_armor.webp"),
  ("ne8", "Sexton Trophy", "armor", "/assets/img/items/default_armor.webp"),
  ("ne9", "Cantor Trophy", "armor", "/assets/img/items/default_armor.webp"),
  ("nea", "Heirophant Trophy", "armor", "/assets/img/items/default_armor.webp"),
  ("neb", "Minion Skull", "armor", "/assets/img/items/default_armor.webp"),
  ("ned", "Overseer Skull", "armor", "/assets/img/items/default_armor.webp"),
  ("nee", "Succubus Skull", "armor", "/assets/img/items/default_armor.webp"),
  ("nef", "Bloodlord Skull", "armor", "/assets/img/items/default_armor.webp"),
  ("neg", "Hellspawn Skull", "armor", "/assets/img/items/default_armor.webp"),
  ("ob1", "Eagle Orb", "weapon", "/assets/img/items/ob1.webp"),
  ("ob2", "Sacred Globe", "weapon", "/assets/img/items/ob2.webp"),
  ("ob3", "Smoked Sphere", "weapon", "/assets/img/items/ob3.webp"),
  ("ob4", "Clasped Orb", "weapon", "/assets/img/items/ob4.webp"),
  ("ob5", "Jared's Stone", "weapon", "/assets/img/items/ob5.webp"),
  ("ob6", "Glowing Orb", "weapon", "/assets/img/items/default_weapon.webp"),
  ("ob7", "Crystalline Globe", "weapon", "/assets/img/items/default_weapon.webp"),
  ("ob8", "Cloudy Sphere", "weapon", "/assets/img/items/default_weapon.webp"),
  ("ob9", "Sparkling Ball", "weapon", "/assets/img/items/default_weapon.webp"),
  ("oba", "Swirling Crystal", "weapon", "/assets/img/items/default_weapon.webp"),
  ("obb", "Heavenly Stone", "weapon", "/assets/img/items/default_weapon.webp"),
  ("obc", "Eldritch Orb", "weapon", "/assets/img/items/default_weapon.webp"),
  ("obd", "Demon Heart", "weapon", "/assets/img/items/default_weapon.webp"),
  ("obe", "Vortex Orb", "weapon", "/assets/img/items/default_weapon.webp"),
  ("obf", "Dimensional Shard", "weapon", "/assets/img/items/default_weapon.webp"),
  ("opl", "Fulminating Potion", "weapon", "/assets/img/items/opl.webp"),
  ("opm", "Exploding Potion", "weapon", "/assets/img/items/opm.webp"),
  ("ops", "Oil Potion", "weapon", "/assets/img/items/ops.webp"),
  ("pa1", "Targe", "armor", "/assets/img/items/pa1.webp"),
  ("pa2", "Rondache", "armor", "/assets/img/items/pa2.webp"),
  ("pa3", "Heraldic Shield", "armor", "/assets/img/items/pa3.webp"),
  ("pa4", "Aerin Shield", "armor", "/assets/img/items/pa4.webp"),
  ("pa5", "Crown Shield", "armor", "/assets/img/items/pa5.webp"),
  ("pa6", "Akaran Targe", "armor", "/assets/img/items/default_armor.webp"),
  ("pa7", "Akaran Rondache", "armor", "/assets/img/items/default_armor.webp"),
  ("pa8", "Protector Shield", "armor", "/assets/img/items/default_armor.webp"),
  ("pa9", "Gilded Shield", "armor", "/assets/img/items/default_armor.webp"),
  ("paa", "Royal Shield", "armor", "/assets/img/items/default_armor.webp"),
  ("pab", "Sacred Targe", "armor", "/assets/img/items/default_armor.webp"),
  ("pac", "Sacred Rondache", "armor", "/assets/img/items/default_armor.webp"),
  ("pad", "Ancient Shield", "armor", "/assets/img/items/default_armor.webp"),
  ("pae", "Zakarum Shield", "armor", "/assets/img/items/default_armor.webp"),
  ("paf", "Vortex Shield", "armor", "/assets/img/items/default_armor.webp"),
  ("pax", "Poleaxe", "weapon", "/assets/img/items/pax.webp"),
  ("pik", "Pike", "weapon", "/assets/img/items/pik.webp"),
  ("pil", "Pilum", "weapon", "/assets/img/items/pil.webp"),
  ("pk1", "Key of Terror", "misc", "/assets/img/items/default_misc.webp"),
  ("pk2", "Key of Hate", "misc", "/assets/img/items/default_misc.webp"),
  ("pk3", "Key of Destruction", "misc", "/assets/img/items/default_misc.webp"),
  ("plt", "Plate Mail", "armor", "/assets/img/items/plt.webp"),
  ("qbr", "Khalim's Brain", "misc", "/assets/img/items/default_misc.webp"),
  ("qey", "Khalim's Eye", "misc", "/assets/img/items/default_misc.webp"),
  ("qf1", "Khalim's Flail", "weapon", "/assets/img/items/qf1.webp"),
  ("qf2", "Khalim's Will", "weapon", "/assets/img/items/qf2.webp"),
  ("qhr", "Khalim's Heart", "misc", "/assets/img/items/default_misc.webp"),
  ("qll", "Quill", "misc", "/assets/img/items/default_misc.webp"),
  ("qui", "Quilted Armor", "armor", "/assets/img/items/default_armor.webp"),
  ("r01", "El Rune", "rune", "/assets/img/items/r01.webp"),
  ("r02", "Eld Rune", "rune", "/assets/img/runes/r02.webp"),
  ("r03", "Tir Rune", "rune", "/assets/img/runes/r03.webp"),
  ("r04", "Nef Rune", "rune", "/assets/img/runes/r04.webp"),
  ("r05", "Eth Rune", "rune", "/assets/img/runes/r05.webp"),
  ("r06", "Ith Rune", "rune", "/assets/img/runes/r06.webp"),
  ("r07", "Tal Rune", "rune", "/assets/img/runes/r07.webp"),
  ("r08", "Ral Rune", "rune", "/assets/img/runes/r08.webp"),
  ("r09", "Ort Rune", "rune", "/assets/img/runes/r09.webp"),
  ("r10", "Thul Rune", "rune", "/assets/img/runes/r10.webp"),
  ("r11", "Amn Rune", "rune", "/assets/img/runes/r11.webp"),
  ("r12", "Sol Rune", "rune", "/assets/img/runes/r12.webp"),
  ("r13", "Shael Rune", "rune", "/assets/img/runes/r13.webp"),
  ("r14", "Dol Rune", "rune", "/assets/img/runes/r14.webp"),
  ("r15", "Hel Rune", "rune", "/assets/img/runes/r15.webp"),
  ("r16", "Io Rune", "rune", "/assets/img/runes/r16.webp"),
  ("r17", "Lum Rune", "rune", "/assets/img/runes/r17.webp"),
  ("r18", "Ko Rune", "rune", "/assets/img/runes/r18.webp"),
  ("r19", "Fal Rune", "rune", "/assets/img/runes/r19.webp"),
  ("r20", "Lem Rune", "rune", "/assets/img/runes/r20.webp"),
  ("r21", "Pul Rune", "rune", "/assets/img/runes/r21.webp"),
  ("r22", "Um Rune", "rune", "/assets/img/runes/r22.webp"),
  ("r23", "Mal Rune", "rune", "/assets/img/runes/r23.webp"),
  ("r24", "Ist Rune", "rune", "/assets/img/runes/r24.webp"),
  ("r25", "Gul Rune", "rune", "/assets/img/runes/r25.webp"),
  ("r26", "Vex Rune", "rune", "/assets/img/runes/r26.webp"),
  ("r27", "Ohm Rune", "rune", "/assets/img/runes/r27.webp"),
  ("r28", "Lo Rune", "rune", "/assets/img/runes/r28.webp"),
  ("r29", "Sur Rune", "rune", "/assets/img/runes/r29.webp"),
  ("r30", "Ber Rune", "rune", "/assets/img/runes/r30.webp"),
  ("r31", "Jah Rune", "rune", "/assets/img/runes/r31.webp"),
  ("r32", "Cham Rune", "rune", "/assets/img/runes/r32.webp"),
  ("r33", "Zod Rune", "rune", "/assets/img/runes/r33.webp"),
  ("rin", "Ring", "misc", "/assets/img/items/rin.webp"),
  ("rng", "Ring Mail", "armor", "/assets/img/items/rng.webp"),
  ("rpl", "Large Red Potion", "misc", "/assets/img/items/rpl.webp"),
  ("rps", "Small Red Potion", "misc", "/assets/img/items/rps.webp"),
  ("rvl", "Full Rejuvenation Potion", "misc", "/assets/img/items/default_misc.webp"),
  ("rvs", "Rejuvenation Potion", "misc", "/assets/img/items/default_misc.webp"),
  ("rxb", "Repeating Crossbow", "weapon", "/assets/img/items/rxb.webp"),
  ("sbb", "Short Battle Bow", "weapon", "/assets/img/items/sbb.webp"),
  ("sbr", "Saber", "weapon", "/assets/img/items/sbr.webp"),
  ("sbw", "Short Bow", "weapon", "/assets/img/items/sbw.webp"),
  ("scl", "Scale Mail", "armor", "/assets/img/items/scl.webp"),
  ("scm", "Scimitar", "weapon", "/assets/img/items/scm.webp"),
  ("scp", "Scepter", "weapon", "/assets/img/items/scp.webp"),
  ("scy", "Scythe", "weapon", "/assets/img/items/scy.webp"),
  ("scz", "Scalp", "misc", "/assets/img/items/default_misc.webp"),
  ("skc", "Chipped Skull", "gem", "/assets/img/items/skc.webp"),
  ("skf", "Flawed Skull", "gem", "/assets/img/items/skf.webp"),
  ("skl", "Flawless Skull", "gem", "/assets/img/items/skl.webp"),
  ("skp", "Skull Cap", "armor", "/assets/img/items/skp.webp"),
  ("skr", "Scissors Katar", "weapon", "/assets/img/items/skr.webp"),
  ("sku", "Skull", "gem", "/assets/img/items/sku.webp"),
  ("skz", "Perfect Skull", "gem", "/assets/img/items/skz.webp"),
  ("sml", "Small Shield", "armor", "/assets/img/items/sml.webp"),
  ("sol", "Soul", "misc", "/assets/img/items/sol.webp"),
  ("spc", "Spiked Club", "weapon", "/assets/img/items/spc.webp"),
  ("spe", "Spleen", "misc", "/assets/img/items/default_misc.webp"),
  ("spk", "Spiked Shield", "armor", "/assets/img/items/spk.webp"),
  ("spl", "Splint Mail", "armor", "/assets/img/items/spl.webp"),
  ("spr", "Spear", "weapon", "/assets/img/items/spr.webp"),
  ("spt", "Spetum", "weapon", "/assets/img/items/spt.webp"),
  ("ssd", "Short Sword", "weapon", "/assets/img/items/ssd.webp"),
  ("ssp", "Short Spear", "weapon", "/assets/img/items/ssp.webp"),
  ("sst", "Short Staff", "weapon", "/assets/img/items/sst.webp"),
  ("std", "Standard of Heroes", "misc", "/assets/img/items/default_misc.webp"),
  ("stu", "Studded Leather", "armor", "/assets/img/items/stu.webp"),
  ("swb", "Short War Bow", "weapon", "/assets/img/items/swb.webp"),
  ("tal", "Tail", "misc", "/assets/img/items/default_misc.webp"),
  ("tax", "Throwing Axe", "weapon", "/assets/img/items/tax.webp"),
  ("tbk", "Tome of Town Portal", "misc", "/assets/img/items/default_misc.webp"),
  ("tbl", "Heavy Belt", "armor", "/assets/img/items/tbl.webp"),
  ("tbt", "Light Plated Boots", "armor", "/assets/img/items/tbt.webp"),
  ("tch", "Torch", "misc", "/assets/img/items/default_misc.webp"),
  ("tes", "Twisted Essence of Suffering", "essence", "/assets/img/items/tes.webp"),
  ("tgl", "Light Gauntlets", "armor", "/assets/img/items/tgl.webp"),
  ("tkf", "Throwing Knife", "weapon", "/assets/img/items/default_weapon.webp"),
  ("toa", "Token of Absolution", "token", "/assets/img/items/toa.webp"),
  ("tow", "Tower Shield", "armor", "/assets/img/items/tow.webp"),
  ("tr1", "Horadric Scroll", "misc", "/assets/img/items/default_misc.webp"),
  ("tr2", "Scroll of Resistance", "misc", "/assets/img/items/default_misc.webp"),
  ("tri", "Trident", "weapon", "/assets/img/items/tri.webp"),
  ("tsc", "Scroll of Town Portal", "misc", "/assets/img/items/default_misc.webp"),
  ("tsp", "Throwing Spear", "weapon", "/assets/img/items/tsp.webp"),
  ("ua1", "Uber Ancient Summon Material Act 1", "misc", "/assets/img/items/default_misc.webp"),
  ("ua2", "Uber Ancient Summon Material Act 2", "misc", "/assets/img/items/default_misc.webp"),
  ("ua3", "Uber Ancient Summon Material Act 3", "misc", "/assets/img/items/default_misc.webp"),
  ("ua4", "Uber Ancient Summon Material Act 4", "misc", "/assets/img/items/default_misc.webp"),
  ("ua5", "Uber Ancient Summon Material Act5", "misc", "/assets/img/items/default_misc.webp"),
  ("uap", "Shako", "armor", "/assets/img/items/uap.webp"),
  ("uar", "Sacred Armor", "armor", "/assets/img/items/default_armor.webp"),
  ("ucl", "Loricated Mail", "armor", "/assets/img/items/default_armor.webp"),
  ("uea", "Wyrmhide", "armor", "/assets/img/items/default_armor.webp"),
  ("uh9", "Bone Visage", "armor", "/assets/img/items/default_armor.webp"),
  ("uhb", "Myrmidon Greaves", "armor", "/assets/img/items/default_armor.webp"),
  ("uhc", "Colossus Girdle", "armor", "/assets/img/items/default_armor.webp"),
  ("uhg", "Ogre Gauntlets", "armor", "/assets/img/items/default_armor.webp"),
  ("uhl", "Giant Conch", "armor", "/assets/img/items/default_armor.webp"),
  ("uhm", "Spired Helm", "armor", "/assets/img/items/default_armor.webp"),
  ("uhn", "Boneweave", "armor", "/assets/img/items/default_armor.webp"),
  ("uit", "Monarch", "armor", "/assets/img/items/default_armor.webp"),
  ("ukp", "Hydraskull", "armor", "/assets/img/items/default_armor.webp"),
  ("ula", "Scarab Husk", "armor", "/assets/img/items/default_armor.webp"),
  ("ulb", "Wyrmhide Boots", "armor", "/assets/img/items/default_armor.webp"),
  ("ulc", "Spiderweb Sash", "armor", "/assets/img/items/default_armor.webp"),
  ("uld", "Kraken Shell", "armor", "/assets/img/items/default_armor.webp"),
  ("ulg", "Bramble Mitts", "armor", "/assets/img/items/default_armor.webp"),
  ("ulm", "Armet", "armor", "/assets/img/items/default_armor.webp"),
  ("ult", "Hellforge Plate", "armor", "/assets/img/items/default_armor.webp"),
  ("um1", "Uber Ancient Upgrade Material  Fire", "misc", "/assets/img/items/default_misc.webp"),
  ("um2", "Uber Ancient Upgrade Material Poison", "misc", "/assets/img/items/default_misc.webp"),
  ("um3", "Uber Ancient Upgrade Material  Cold", "misc", "/assets/img/items/default_misc.webp"),
  ("um4", "Uber Ancient Upgrade Material Physical", "misc", "/assets/img/items/default_misc.webp"),
  ("um5", "Uber Ancient Upgrade Material Lightning", "misc", "/assets/img/items/default_misc.webp"),
  ("um6", "Uber Ancient Upgrade Material Magic", "misc", "/assets/img/items/default_misc.webp"),
  ("umb", "Boneweave Boots", "armor", "/assets/img/items/default_armor.webp"),
  ("umc", "Mithril Coil", "armor", "/assets/img/items/default_armor.webp"),
  ("umg", "Vambraces", "armor", "/assets/img/items/default_armor.webp"),
  ("uml", "Luna", "armor", "/assets/img/items/default_armor.webp"),
  ("ung", "Diamond Mail", "armor", "/assets/img/items/default_armor.webp"),
  ("uow", "Aegis", "armor", "/assets/img/items/default_armor.webp"),
  ("upk", "Blade Barrier", "armor", "/assets/img/items/default_armor.webp"),
  ("upl", "Balrog Skin", "armor", "/assets/img/items/default_armor.webp"),
  ("urg", "Hyperion", "armor", "/assets/img/items/default_armor.webp"),
  ("urn", "Corona", "armor", "/assets/img/items/default_armor.webp"),
  ("urs", "Great Hauberk", "armor", "/assets/img/items/default_armor.webp"),
  ("ush", "Troll Nest", "armor", "/assets/img/items/default_armor.webp"),
  ("usk", "Demonhead", "armor", "/assets/img/items/default_armor.webp"),
  ("utb", "Mirrored Boots", "armor", "/assets/img/items/default_armor.webp"),
  ("utc", "Troll Belt", "armor", "/assets/img/items/default_armor.webp"),
  ("utg", "Crusader Gauntlets", "armor", "/assets/img/items/default_armor.webp"),
  ("uth", "Lacquered Plate", "armor", "/assets/img/items/default_armor.webp"),
  ("utp", "Archon Plate", "armor", "/assets/img/items/default_armor.webp"),
  ("uts", "Ward", "armor", "/assets/img/items/default_armor.webp"),
  ("utu", "Wire Fleece", "armor", "/assets/img/items/default_armor.webp"),
  ("uuc", "Heater", "armor", "/assets/img/items/default_armor.webp"),
  ("uui", "Dusk Shroud", "armor", "/assets/img/items/default_armor.webp"),
  ("uul", "Shadow Plate", "armor", "/assets/img/items/default_armor.webp"),
  ("uvb", "Scarabshell Boots", "armor", "/assets/img/items/default_armor.webp"),
  ("uvc", "Vampirefang Belt", "armor", "/assets/img/items/default_armor.webp"),
  ("uvg", "Vampirebone Gloves", "armor", "/assets/img/items/default_armor.webp"),
  ("vbl", "Light Belt", "armor", "/assets/img/items/vbl.webp"),
  ("vbt", "Heavy Boots", "armor", "/assets/img/items/vbt.webp"),
  ("vgl", "Heavy Gloves", "armor", "/assets/img/items/vgl.webp"),
  ("vip", "Amulet of the Viper", "misc", "/assets/img/items/vip.webp"),
  ("vou", "Voulge", "weapon", "/assets/img/items/vou.webp"),
  ("vps", "Stamina Potion", "misc", "/assets/img/items/vps.webp"),
  ("wa1", "Old Book", "shield", "/assets/img/items/default_shield.webp"),
  ("wa2", "Tome", "shield", "/assets/img/items/default_shield.webp"),
  ("wa3", "Codex", "shield", "/assets/img/items/default_shield.webp"),
  ("wa4", "Compendium", "shield", "/assets/img/items/default_shield.webp"),
  ("wa5", "Grimoire", "shield", "/assets/img/items/default_shield.webp"),
  ("wa6", "Burnt Text", "shield", "/assets/img/items/default_shield.webp"),
  ("wa7", "Dark Tome", "shield", "/assets/img/items/default_shield.webp"),
  ("wa8", "Dark Codex", "shield", "/assets/img/items/default_shield.webp"),
  ("wa9", "Possessed Compendium", "shield", "/assets/img/items/default_shield.webp"),
  ("waa", "Possessed Grimoire", "shield", "/assets/img/items/default_shield.webp"),
  ("wab", "Forgotten Volume", "shield", "/assets/img/items/default_shield.webp"),
  ("wac", "Occult Tome", "shield", "/assets/img/items/default_shield.webp"),
  ("wad", "Occult Codex", "shield", "/assets/img/items/default_shield.webp"),
  ("wae", "Blasphemous Compendium", "shield", "/assets/img/items/default_shield.webp"),
  ("waf", "Blasphemous Grimoire", "shield", "/assets/img/items/default_shield.webp"),
  ("wax", "War Axe", "weapon", "/assets/img/items/wax.webp"),
  ("whm", "War Hammer", "weapon", "/assets/img/items/whm.webp"),
  ("wms", "Thawing Potion", "misc", "/assets/img/items/default_misc.webp"),
  ("wnd", "Wand", "weapon", "/assets/img/items/wnd.webp"),
  ("wrb", "Wrist Blade", "weapon", "/assets/img/items/default_weapon.webp"),
  ("wsc", "War Scythe", "weapon", "/assets/img/items/wsc.webp"),
  ("wsd", "War Sword", "weapon", "/assets/img/items/wsd.webp"),
  ("wsp", "War Scepter", "weapon", "/assets/img/items/wsp.webp"),
  ("wst", "War Staff", "weapon", "/assets/img/items/wst.webp"),
  ("xa1", "Western Worldstone Shard", "shard", "/assets/img/items/xa1.webp"),
  ("xa2", "Eastern Worldstone Shard", "shard", "/assets/img/items/xa2.webp"),
  ("xa3", "Southern Worldstone Shard", "shard", "/assets/img/items/xa3.webp"),
  ("xa4", "Deep Worldstone Shard", "shard", "/assets/img/items/xa4.webp"),
  ("xa5", "Northern Worldstone Shard", "shard", "/assets/img/items/xa5.webp"),
  ("xap", "War Hat", "armor", "/assets/img/items/default_armor.webp"),
  ("xar", "Ornate Armor", "armor", "/assets/img/items/default_armor.webp"),
  ("xcl", "Tigulated Mail", "armor", "/assets/img/items/default_armor.webp"),
  ("xea", "Serpentskin Armor", "armor", "/assets/img/items/default_armor.webp"),
  ("xh9", "Grim Helm", "armor", "/assets/img/items/default_armor.webp"),
  ("xhb", "War Boots", "armor", "/assets/img/items/default_armor.webp"),
  ("xhg", "War Gauntlets", "armor", "/assets/img/items/default_armor.webp"),
  ("xhl", "Basinet", "armor", "/assets/img/items/default_armor.webp"),
  ("xhm", "Winged Helm", "armor", "/assets/img/items/default_armor.webp"),
  ("xhn", "Mesh Armor", "armor", "/assets/img/items/default_armor.webp"),
  ("xit", "Dragon Shield", "armor", "/assets/img/items/default_armor.webp"),
  ("xkp", "Sallet", "armor", "/assets/img/items/default_armor.webp"),
  ("xla", "Demonhide Armor", "armor", "/assets/img/items/default_armor.webp"),
  ("xlb", "Demonhide Boots", "armor", "/assets/img/items/default_armor.webp"),
  ("xld", "Sharktooth Armor", "armor", "/assets/img/items/default_armor.webp"),
  ("xlg", "Demonhide Gloves", "armor", "/assets/img/items/default_armor.webp"),
  ("xlm", "Casque", "armor", "/assets/img/items/default_armor.webp"),
  ("xlt", "Templar Coat", "armor", "/assets/img/items/default_armor.webp"),
  ("xmb", "Mesh Boots", "armor", "/assets/img/items/default_armor.webp"),
  ("xmg", "Heavy Bracers", "armor", "/assets/img/items/default_armor.webp"),
  ("xml", "Round Shield", "armor", "/assets/img/items/default_armor.webp"),
  ("xng", "Linked Mail", "armor", "/assets/img/items/default_armor.webp"),
  ("xow", "Pavise", "armor", "/assets/img/items/default_armor.webp"),
  ("xpk", "Barbed Shield", "armor", "/assets/img/items/default_armor.webp"),
  ("xpl", "Russet Armor", "armor", "/assets/img/items/xpl.webp"),
  ("xrg", "Scutum", "armor", "/assets/img/items/default_armor.webp"),
  ("xrn", "Grand Crown", "armor", "/assets/img/items/default_armor.webp"),
  ("xrs", "Cuirass", "armor", "/assets/img/items/default_armor.webp"),
  ("xsh", "Grim Shield", "armor", "/assets/img/items/default_armor.webp"),
  ("xsk", "Death Mask", "armor", "/assets/img/items/default_armor.webp"),
  ("xtb", "Battle Boots", "armor", "/assets/img/items/default_armor.webp"),
  ("xtg", "Battle Gauntlets", "armor", "/assets/img/items/default_armor.webp"),
  ("xth", "Embossed Plate", "armor", "/assets/img/items/default_armor.webp"),
  ("xtp", "Mage Plate", "armor", "/assets/img/items/default_armor.webp"),
  ("xts", "Ancient Shield", "armor", "/assets/img/items/default_armor.webp"),
  ("xtu", "Trellised Armor", "armor", "/assets/img/items/default_armor.webp"),
  ("xuc", "Defender", "armor", "/assets/img/items/default_armor.webp"),
  ("xui", "Ghost Armor", "armor", "/assets/img/items/default_armor.webp"),
  ("xul", "Chaos Armor", "armor", "/assets/img/items/default_armor.webp"),
  ("xvb", "Sharkskin Boots", "armor", "/assets/img/items/default_armor.webp"),
  ("xvg", "Sharkskin Gloves", "armor", "/assets/img/items/default_armor.webp"),
  ("xyz", "Potion of Life", "misc", "/assets/img/items/xyz.webp"),
  ("yps", "Antidote Potion", "misc", "/assets/img/items/yps.webp"),
  ("ywn", "Yew Wand", "weapon", "/assets/img/items/ywn.webp"),
  ("zhb", "War Belt", "armor", "/assets/img/items/default_armor.webp"),
  ("zlb", "Demonhide Sash", "armor", "/assets/img/items/default_armor.webp"),
  ("zmb", "Mesh Belt", "armor", "/assets/img/items/default_armor.webp"),
  ("ztb", "Battle Belt", "armor", "/assets/img/items/default_armor.webp"),
  ("zvb", "Sharkskin Belt", "armor", "/assets/img/items/default_armor.webp"),
];
// Total: 691 items

/// Set of item type codes that are stackable
#[rustfmt::skip]
pub const STACKABLE_ITEM_CODES: &[&str] = &[
  "7b8",
  "7bk",
  "7gl",
  "7ja",
  "7pi",
  "7s7",
  "7ta",
  "7tk",
  "7ts",
  "9b8",
  "9bk",
  "9gl",
  "9ja",
  "9pi",
  "9s9",
  "9ta",
  "9tk",
  "9ts",
  "am5",
  "ama",
  "amf",
  "aqv",
  "bal",
  "bkf",
  "bpl",
  "bps",
  "cqv",
  "gld",
  "glv",
  "gpl",
  "gpm",
  "gps",
  "ibk",
  "jav",
  "key",
  "opl",
  "opm",
  "ops",
  "pil",
  "r01",
  "r02",
  "r03",
  "r04",
  "r05",
  "r06",
  "r07",
  "r08",
  "r09",
  "r10",
  "r11",
  "r12",
  "r13",
  "r14",
  "r15",
  "r16",
  "r17",
  "r18",
  "r19",
  "r20",
  "r21",
  "r22",
  "r23",
  "r24",
  "r25",
  "r26",
  "r27",
  "r28",
  "r29",
  "r30",
  "r31",
  "r32",
  "r33",
  "rpl",
  "rps",
  "ssp",
  "tax",
  "tbk",
  "tkf",
  "tsp",
];
// Total: 79 stackable codes

/// Item name → item code lookup table (lowercase names)
#[rustfmt::skip]
pub const ITEM_NAME_TO_CODE: &[(&str, &str)] = &[
  ("a jade figurine", "j34"),
  ("aegis", "uow"),
  ("aerin shield", "pa4"),
  ("akaran rondache", "pa7"),
  ("akaran targe", "pa6"),
  ("alpha helm", "dr6"),
  ("amethyst", "gsv"),
  ("amn rune", "r11"),
  ("amulet", "amu"),
  ("amulet of the viper", "vip"),
  ("ancient armor", "aar"),
  ("ancient axe", "9gi"),
  ("ancient shield", "xts"),
  ("ancient sword", "9wd"),
  ("antidote potion", "yps"),
  ("antlers", "dr3"),
  ("arbalest", "8lx"),
  ("archon plate", "utp"),
  ("archon staff", "6ws"),
  ("armet", "ulm"),
  ("arrows", "aqv"),
  ("ashwood bow", "am6"),
  ("assault helmet", "ba4"),
  ("ataghan", "7sm"),
  ("avenger guard", "ba5"),
  ("axe", "axe"),
  ("baal's eye", "bey"),
  ("balanced axe", "bal"),
  ("balanced knife", "bkf"),
  ("ballista", "8hx"),
  ("balrog blade", "7gs"),
  ("balrog skin", "upl"),
  ("balrog spear", "7s7"),
  ("barbed club", "9sp"),
  ("barbed shield", "xpk"),
  ("bardiche", "bar"),
  ("basinet", "xhl"),
  ("bastard sword", "bsw"),
  ("battle axe", "btx"),
  ("battle belt", "ztb"),
  ("battle boots", "xtb"),
  ("battle cestus", "7cs"),
  ("battle dart", "9tk"),
  ("battle gauntlets", "xtg"),
  ("battle hammer", "9wh"),
  ("battle scythe", "9s8"),
  ("battle staff", "bst"),
  ("battle sword", "9bs"),
  ("bearded axe", "9ba"),
  ("bec-de-corbin", "9h9"),
  ("belt", "mbl"),
  ("ber rune", "r30"),
  ("berserker axe", "7wa"),
  ("bill", "9vo"),
  ("blade", "bld"),
  ("blade barrier", "upk"),
  ("blade bow", "6hb"),
  ("blade talons", "btl"),
  ("blasphemous compendium", "wae"),
  ("blasphemous grimoire", "waf"),
  ("blood spirit", "drb"),
  ("bloodlord skull", "nef"),
  ("bolts", "cqv"),
  ("bone helm", "bhm"),
  ("bone knife", "7dg"),
  ("bone shield", "bsh"),
  ("bone visage", "uh9"),
  ("bone wand", "bwn"),
  ("boneweave", "uhn"),
  ("boneweave boots", "umb"),
  ("book of skill", "ass"),
  ("boots", "lbt"),
  ("brain", "brz"),
  ("bramble mitts", "ulg"),
  ("brandistock", "brn"),
  ("breast plate", "brs"),
  ("broad axe", "bax"),
  ("broad sword", "bsd"),
  ("buckler", "buc"),
  ("burning essence of terror", "bet"),
  ("burnt text", "wa6"),
  ("burnt wand", "9wn"),
  ("caduceus", "7ws"),
  ("cantor trophy", "ne9"),
  ("cap", "cap"),
  ("carnage helm", "bab"),
  ("casque", "xlm"),
  ("cedar bow", "8lb"),
  ("cedar staff", "8cs"),
  ("ceremonial bow", "am7"),
  ("ceremonial javelin", "ama"),
  ("ceremonial pike", "am9"),
  ("ceremonial spear", "am8"),
  ("cestus", "ces"),
  ("chain boots", "mbt"),
  ("chain gloves", "mgl"),
  ("chain mail", "chn"),
  ("cham rune", "r32"),
  ("champion axe", "7ga"),
  ("champion sword", "7b7"),
  ("chaos armor", "xul"),
  ("charged essense of hatred", "ceh"),
  ("chipped amethyst", "gcv"),
  ("chipped diamond", "gcw"),
  ("chipped emerald", "gcg"),
  ("chipped ruby", "gcr"),
  ("chipped sapphire", "gcb"),
  ("chipped skull", "skc"),
  ("chipped topaz", "gcy"),
  ("choking gas potion", "gpm"),
  ("chu-ko-nu", "8rx"),
  ("cinquedeas", "9kr"),
  ("circlet", "ci0"),
  ("clasped orb", "ob4"),
  ("claws", "clw"),
  ("claymore", "clm"),
  ("cleaver", "9ax"),
  ("cloudy sphere", "ob8"),
  ("club", "clb"),
  ("codex", "wa3"),
  ("colossal jewel", "cjw"),
  ("colossal sword", "7fb"),
  ("colossus blade", "7gd"),
  ("colossus crossbow", "6hx"),
  ("colossus girdle", "uhc"),
  ("colossus voulge", "7vo"),
  ("compendium", "wa4"),
  ("composite bow", "cbw"),
  ("conqueror crown", "bae"),
  ("conquest sword", "7bs"),
  ("corona", "urn"),
  ("coronet", "ci1"),
  ("crossbow", "mxb"),
  ("crowbill", "9mp"),
  ("crown", "crn"),
  ("crown shield", "pa5"),
  ("crusader bow", "6l7"),
  ("crusader gauntlets", "utg"),
  ("cryptic axe", "7pa"),
  ("cryptic sword", "7ls"),
  ("crystal sword", "crs"),
  ("crystalline globe", "ob7"),
  ("cudgel", "9cl"),
  ("cuirass", "xrs"),
  ("cutlass", "9sm"),
  ("dacian falx", "9cm"),
  ("dagger", "dgr"),
  ("dark codex", "wa8"),
  ("dark tome", "wa7"),
  ("death mask", "xsk"),
  ("decapitator", "7bt"),
  ("decoy gidbinn", "d33"),
  ("deep worldstone shard", "xa4"),
  ("defender", "xuc"),
  ("demon crossbow", "6rx"),
  ("demon head", "ne5"),
  ("demon heart", "obd"),
  ("demonhead", "usk"),
  ("demonhide armor", "xla"),
  ("demonhide boots", "xlb"),
  ("demonhide gloves", "xlg"),
  ("demonhide sash", "zlb"),
  ("destroyer helm", "bad"),
  ("devil star", "7mt"),
  ("diablo's horn", "dhn"),
  ("diadem", "ci3"),
  ("diamond", "gsw"),
  ("diamond bow", "6s7"),
  ("diamond mail", "ung"),
  ("dimensional blade", "9cr"),
  ("dimensional shard", "obf"),
  ("dirk", "dir"),
  ("divine scepter", "9ws"),
  ("dol rune", "r14"),
  ("double axe", "2ax"),
  ("double bow", "8cb"),
  ("dragon shield", "xit"),
  ("dream spirit", "drf"),
  ("dusk shroud", "uui"),
  ("eagle orb", "ob1"),
  ("ear", "ear"),
  ("earth spirit", "drd"),
  ("eastern worldstone shard", "xa2"),
  ("edge bow", "8sb"),
  ("el rune", "r01"),
  ("eld rune", "r02"),
  ("elder staff", "6cs"),
  ("eldritch orb", "obc"),
  ("elegant blade", "7sb"),
  ("elixir", "elx"),
  ("embossed plate", "xth"),
  ("emerald", "gsg"),
  ("espandon", "92h"),
  ("eth rune", "r05"),
  ("ettin axe", "72a"),
  ("executioner sword", "9gd"),
  ("exploding potion", "opm"),
  ("eye", "eyz"),
  ("fal rune", "r19"),
  ("falcata", "7ss"),
  ("falchion", "flc"),
  ("falcon mask", "dr4"),
  ("fang", "fng"),
  ("fanged helm", "ba2"),
  ("fanged knife", "7kr"),
  ("fascia", "9xf"),
  ("feral axe", "7la"),
  ("feral claws", "7lw"),
  ("festering essence of destruction", "fed"),
  ("fetish trophy", "ne7"),
  ("field plate", "fld"),
  ("flag", "flg"),
  ("flail", "fla"),
  ("flamberge", "flb"),
  ("flanged mace", "9ma"),
  ("flawed amethyst", "gfv"),
  ("flawed diamond", "gfw"),
  ("flawed emerald", "gfg"),
  ("flawed ruby", "gfr"),
  ("flawed sapphire", "gfb"),
  ("flawed skull", "skf"),
  ("flawed topaz", "gfy"),
  ("flawless amethyst", "gzv"),
  ("flawless diamond", "glw"),
  ("flawless emerald", "glg"),
  ("flawless ruby", "glr"),
  ("flawless sapphire", "glb"),
  ("flawless skull", "skl"),
  ("flawless topaz", "gly"),
  ("flying axe", "7ta"),
  ("flying knife", "7tk"),
  ("forgotten volume", "wab"),
  ("francisca", "9ta"),
  ("full healing potion", "hpf"),
  ("full helm", "fhl"),
  ("full mana potion", "mpf"),
  ("full plate mail", "ful"),
  ("full rejuvenation potion", "rvl"),
  ("fulminating potion", "opl"),
  ("fury visor", "bac"),
  ("fuscina", "9tr"),
  ("gargoyle head", "ne4"),
  ("gauntlets", "hgl"),
  ("ghost armor", "xui"),
  ("ghost glaive", "7gl"),
  ("ghost spear", "7st"),
  ("ghost wand", "7yw"),
  ("giant axe", "gix"),
  ("giant conch", "uhl"),
  ("giant sword", "gis"),
  ("giant thresher", "7wc"),
  ("gilded shield", "pa9"),
  ("gladius", "9ss"),
  ("glaive", "glv"),
  ("glorious axe", "7gi"),
  ("glowing orb", "ob6"),
  ("gnarled staff", "cst"),
  ("gold", "gld"),
  ("gorgon crossbow", "6mx"),
  ("gothic axe", "9ga"),
  ("gothic bow", "8lw"),
  ("gothic plate", "gth"),
  ("gothic shield", "gts"),
  ("gothic staff", "8bs"),
  ("gothic sword", "9b9"),
  ("grand charm", "cm3"),
  ("grand crown", "xrn"),
  ("grand matron bow", "amc"),
  ("grand scepter", "gsc"),
  ("grave wand", "9gw"),
  ("great axe", "gax"),
  ("great bow", "6cb"),
  ("great hauberk", "urs"),
  ("great helm", "ghm"),
  ("great maul", "gma"),
  ("great pilum", "9pi"),
  ("great poleaxe", "7h7"),
  ("great sword", "gsd"),
  ("greater claws", "9lw"),
  ("greater healing potion", "hp4"),
  ("greater mana potion", "mp4"),
  ("greater talons", "9tw"),
  ("greaves", "hbt"),
  ("griffon headress", "dr7"),
  ("grim helm", "xh9"),
  ("grim scythe", "9wc"),
  ("grim shield", "xsh"),
  ("grim wand", "gwn"),
  ("grimoire", "wa5"),
  ("guardian crown", "baf"),
  ("gul rune", "r25"),
  ("halberd", "hal"),
  ("hand axe", "hax"),
  ("hand scythe", "9cs"),
  ("hard leather armor", "hla"),
  ("harpoon", "9ts"),
  ("hatchet", "9ha"),
  ("hatchet hands", "axf"),
  ("hawk helm", "dr2"),
  ("healing potion", "hpo"),
  ("heart", "hrt"),
  ("heater", "uuc"),
  ("heavenly stone", "obb"),
  ("heavy belt", "tbl"),
  ("heavy boots", "vbt"),
  ("heavy bracers", "xmg"),
  ("heavy crossbow", "hxb"),
  ("heavy gloves", "vgl"),
  ("heirophant trophy", "nea"),
  ("hel rune", "r15"),
  ("hellforge hammer", "hfh"),
  ("hellforge plate", "ult"),
  ("hellspawn skull", "neg"),
  ("helm", "hlm"),
  ("heraldic shield", "pa3"),
  ("herb", "hrb"),
  ("highland blade", "7cm"),
  ("holy water sprinkler", "9qs"),
  ("horadric cube", "box"),
  ("horadric malus", "hdm"),
  ("horadric scroll", "tr1"),
  ("horadric staff", "hst"),
  ("horn", "hrn"),
  ("horned helm", "ba3"),
  ("hunter's bow", "hbw"),
  ("hunter's guise", "dr8"),
  ("hurlbat", "9b8"),
  ("hydra bow", "6lw"),
  ("hydra edge", "7fc"),
  ("hydraskull", "ukp"),
  ("hyperion", "urg"),
  ("hyperion javelin", "7ja"),
  ("hyperion spear", "7sr"),
  ("io rune", "r16"),
  ("ist rune", "r24"),
  ("ith rune", "r06"),
  ("jagged star", "9mt"),
  ("jah rune", "r31"),
  ("jared's stone", "ob5"),
  ("javelin", "jav"),
  ("jawbone", "jaw"),
  ("jawbone cap", "ba1"),
  ("jawbone visor", "ba6"),
  ("jewel", "jew"),
  ("jo staff", "8ss"),
  ("katar", "ktr"),
  ("key", "key"),
  ("key of destruction", "pk3"),
  ("key of hate", "pk2"),
  ("key of terror", "pk1"),
  ("key to the cairn stones", "bkd"),
  ("khalim's brain", "qbr"),
  ("khalim's eye", "qey"),
  ("khalim's flail", "qf1"),
  ("khalim's heart", "qhr"),
  ("khalim's will", "qf2"),
  ("kite shield", "kit"),
  ("knout", "9fl"),
  ("ko rune", "r18"),
  ("kraken shell", "uld"),
  ("kriss", "kri"),
  ("lacquered plate", "uth"),
  ("lam esen's tome", "bbb"),
  ("lance", "9p9"),
  ("large axe", "lax"),
  ("large blue potion", "bpl"),
  ("large charm", "cm2"),
  ("large red potion", "rpl"),
  ("large shield", "lrg"),
  ("leather armor", "lea"),
  ("leather gloves", "lgl"),
  ("legend spike", "7bl"),
  ("legend sword", "72h"),
  ("legendary mallet", "7wh"),
  ("lem rune", "r20"),
  ("lich wand", "7bw"),
  ("light belt", "vbl"),
  ("light crossbow", "lxb"),
  ("light gauntlets", "tgl"),
  ("light healing potion", "hp2"),
  ("light mana potion", "mp2"),
  ("light plate", "ltp"),
  ("light plated boots", "tbt"),
  ("linked mail", "xng"),
  ("lion helm", "ba7"),
  ("lo rune", "r28"),
  ("lochaber axe", "9b7"),
  ("long battle bow", "lbb"),
  ("long bow", "lbw"),
  ("long siege bow", "8l8"),
  ("long staff", "lst"),
  ("long sword", "lsd"),
  ("long war bow", "lwb"),
  ("loricated mail", "ucl"),
  ("lum rune", "r17"),
  ("luna", "uml"),
  ("mace", "mac"),
  ("mage plate", "xtp"),
  ("maiden javelin", "am5"),
  ("maiden pike", "am4"),
  ("maiden spear", "am3"),
  ("mal rune", "r23"),
  ("malah's potion", "ice"),
  ("mana potion", "mpo"),
  ("mancatcher", "7br"),
  ("martel de fer", "9gm"),
  ("mask", "msk"),
  ("matriarchal bow", "amb"),
  ("matriarchal javelin", "amf"),
  ("matriarchal pike", "ame"),
  ("matriarchal spear", "amd"),
  ("maul", "mau"),
  ("mephisto's brain", "mbr"),
  ("mephisto's soulstone", "mss"),
  ("mesh armor", "xhn"),
  ("mesh belt", "zmb"),
  ("mesh boots", "xmb"),
  ("mighty scepter", "7sc"),
  ("military axe", "9la"),
  ("military pick", "mpi"),
  ("minion skull", "neb"),
  ("minor healing potion", "hp1"),
  ("minor mana potion", "mp1"),
  ("mirrored boots", "utb"),
  ("mithral point", "7di"),
  ("mithril coil", "umc"),
  ("monarch", "uit"),
  ("morning star", "mst"),
  ("mummified trophy", "ne6"),
  ("myrmidon greaves", "uhb"),
  ("mythical sword", "7wd"),
  ("naga", "9wa"),
  ("nef rune", "r04"),
  ("northern worldstone shard", "xa5"),
  ("occult codex", "wad"),
  ("occult tome", "wac"),
  ("ogre axe", "7o7"),
  ("ogre gauntlets", "uhg"),
  ("ogre maul", "7m7"),
  ("ohm rune", "r27"),
  ("oil potion", "ops"),
  ("old book", "wa1"),
  ("ornate armor", "xar"),
  ("ort rune", "r09"),
  ("overseer skull", "ned"),
  ("partizan", "9pa"),
  ("pavise", "xow"),
  ("pellet bow", "6lx"),
  ("perfect amethyst", "gpv"),
  ("perfect diamond", "gpw"),
  ("perfect emerald", "gpg"),
  ("perfect ruby", "gpr"),
  ("perfect sapphire", "gpb"),
  ("perfect skull", "skz"),
  ("perfect topaz", "gpy"),
  ("petrified wand", "9yw"),
  ("phase blade", "7cr"),
  ("pike", "pik"),
  ("pilum", "pil"),
  ("plate mail", "plt"),
  ("plated belt", "hbl"),
  ("poignard", "9dg"),
  ("poleaxe", "pax"),
  ("polished wand", "7wn"),
  ("possessed compendium", "wa9"),
  ("possessed grimoire", "waa"),
  ("potion of life", "xyz"),
  ("preserved head", "ne1"),
  ("protector shield", "pa8"),
  ("pul rune", "r21"),
  ("quarterstaff", "8ls"),
  ("quhab", "9ar"),
  ("quill", "qll"),
  ("quilted armor", "qui"),
  ("rage mask", "ba8"),
  ("ral rune", "r08"),
  ("rancid gas potion", "gps"),
  ("razor bow", "8hb"),
  ("reflex bow", "am2"),
  ("reinforced mace", "7ma"),
  ("rejuvenation potion", "rvs"),
  ("repeating crossbow", "rxb"),
  ("ring", "rin"),
  ("ring mail", "rng"),
  ("rondache", "pa2"),
  ("rondel", "9di"),
  ("round shield", "xml"),
  ("royal shield", "paa"),
  ("ruby", "gsr"),
  ("rune bow", "8sw"),
  ("rune scepter", "9sc"),
  ("rune staff", "8ws"),
  ("rune sword", "9ls"),
  ("runic talons", "7tw"),
  ("russet armor", "xpl"),
  ("saber", "sbr"),
  ("sacred armor", "uar"),
  ("sacred feathers", "dr9"),
  ("sacred globe", "ob2"),
  ("sacred rondache", "pac"),
  ("sacred targe", "pab"),
  ("sallet", "xkp"),
  ("sapphire", "gsb"),
  ("sash", "lbl"),
  ("savage helmet", "ba9"),
  ("scale mail", "scl"),
  ("scalp", "scz"),
  ("scarab husk", "ula"),
  ("scarabshell boots", "uvb"),
  ("scepter", "scp"),
  ("scimitar", "scm"),
  ("scissors katar", "skr"),
  ("scissors quhab", "9qr"),
  ("scissors suwayyah", "7qr"),
  ("scourge", "7fl"),
  ("scroll of identify", "isc"),
  ("scroll of inifuss", "bks"),
  ("scroll of knowledge", "0sc"),
  ("scroll of resistance", "tr2"),
  ("scroll of town portal", "tsc"),
  ("scutum", "xrg"),
  ("scythe", "scy"),
  ("seraph rod", "7qs"),
  ("serpentskin armor", "xea"),
  ("sexton trophy", "ne8"),
  ("shadow bow", "6lb"),
  ("shadow plate", "uul"),
  ("shael rune", "r13"),
  ("shako", "uap"),
  ("shamshir", "9sb"),
  ("sharkskin belt", "zvb"),
  ("sharkskin boots", "xvb"),
  ("sharkskin gloves", "xvg"),
  ("sharktooth armor", "xld"),
  ("shillelagh", "6bs"),
  ("short battle bow", "sbb"),
  ("short bow", "sbw"),
  ("short siege bow", "8s8"),
  ("short spear", "ssp"),
  ("short staff", "sst"),
  ("short sword", "ssd"),
  ("short war bow", "swb"),
  ("siege crossbow", "8mx"),
  ("silver-edged axe", "7ba"),
  ("simbilan", "9s9"),
  ("skull", "sku"),
  ("skull cap", "skp"),
  ("sky spirit", "dre"),
  ("slayer guard", "baa"),
  ("small blue potion", "bps"),
  ("small charm", "cm1"),
  ("small crescent", "7ax"),
  ("small red potion", "rps"),
  ("small shield", "sml"),
  ("smoked sphere", "ob3"),
  ("sol rune", "r12"),
  ("soul", "sol"),
  ("southern worldstone shard", "xa3"),
  ("sparkling ball", "ob9"),
  ("spear", "spr"),
  ("spetum", "spt"),
  ("spiculum", "9gl"),
  ("spider bow", "6sb"),
  ("spiderweb sash", "ulc"),
  ("spiked club", "spc"),
  ("spiked shield", "spk"),
  ("spired helm", "uhm"),
  ("spirit mask", "dr5"),
  ("spleen", "spe"),
  ("splint mail", "spl"),
  ("staff of kings", "msf"),
  ("stag bow", "am1"),
  ("stalagmite", "6ls"),
  ("stamina potion", "vps"),
  ("standard of heroes", "std"),
  ("stilleto", "9bl"),
  ("strangling gas potion", "gpl"),
  ("studded leather", "stu"),
  ("stygian pike", "7tr"),
  ("stygian pilum", "7pi"),
  ("succubus skull", "nee"),
  ("sun spirit", "drc"),
  ("super healing potion", "hp5"),
  ("super mana potion", "mp5"),
  ("sur rune", "r29"),
  ("suwayyah", "7ar"),
  ("swirling crystal", "oba"),
  ("tabar", "9bt"),
  ("tail", "tal"),
  ("tal rune", "r07"),
  ("targe", "pa1"),
  ("templar coat", "xlt"),
  ("thawing potion", "wms"),
  ("the black tower key", "luv"),
  ("the gidbinn", "g33"),
  ("the golden bird", "g34"),
  ("thresher", "7s8"),
  ("throwing axe", "tax"),
  ("throwing knife", "tkf"),
  ("throwing spear", "tsp"),
  ("thul rune", "r10"),
  ("thunder maul", "7gm"),
  ("tiara", "ci2"),
  ("tigulated mail", "xcl"),
  ("tir rune", "r03"),
  ("token of absolution", "toa"),
  ("tomahawk", "7ha"),
  ("tomb wand", "9bw"),
  ("tome", "wa2"),
  ("tome of identify", "ibk"),
  ("tome of town portal", "tbk"),
  ("topaz", "gsy"),
  ("torch", "tch"),
  ("totemic mask", "dra"),
  ("tower shield", "tow"),
  ("trellised armor", "xtu"),
  ("trident", "tri"),
  ("troll belt", "utc"),
  ("troll nest", "ush"),
  ("truncheon", "7cl"),
  ("tulwar", "9fc"),
  ("tusk sword", "9gs"),
  ("twin axe", "92a"),
  ("twisted essence of suffering", "tes"),
  ("two-handed sword", "2hs"),
  ("tyrant club", "7sp"),
  ("uber ancient summon material act 1", "ua1"),
  ("uber ancient summon material act 2", "ua2"),
  ("uber ancient summon material act 3", "ua3"),
  ("uber ancient summon material act 4", "ua4"),
  ("uber ancient summon material act5", "ua5"),
  ("uber ancient upgrade material  cold", "um3"),
  ("uber ancient upgrade material  fire", "um1"),
  ("uber ancient upgrade material lightning", "um5"),
  ("uber ancient upgrade material magic", "um6"),
  ("uber ancient upgrade material physical", "um4"),
  ("uber ancient upgrade material poison", "um2"),
  ("um rune", "r22"),
  ("unearthed wand", "7gw"),
  ("unraveller head", "ne3"),
  ("vambraces", "umg"),
  ("vampirebone gloves", "uvg"),
  ("vampirefang belt", "uvc"),
  ("vex rune", "r26"),
  ("vortex orb", "obe"),
  ("vortex shield", "paf"),
  ("voulge", "vou"),
  ("walking stick", "6ss"),
  ("wand", "wnd"),
  ("war axe", "wax"),
  ("war belt", "zhb"),
  ("war boots", "xhb"),
  ("war club", "9m9"),
  ("war dart", "9bk"),
  ("war fist", "7xf"),
  ("war fork", "9br"),
  ("war gauntlets", "xhg"),
  ("war hammer", "whm"),
  ("war hat", "xap"),
  ("war javelin", "9ja"),
  ("war pike", "7p7"),
  ("war scepter", "wsp"),
  ("war scythe", "wsc"),
  ("war spear", "9sr"),
  ("war spike", "7mp"),
  ("war staff", "wst"),
  ("war sword", "wsd"),
  ("ward", "uts"),
  ("ward bow", "6sw"),
  ("western worldstone shard", "xa1"),
  ("winged axe", "7b8"),
  ("winged harpoon", "7ts"),
  ("winged helm", "xhm"),
  ("winged knife", "7bk"),
  ("wire fleece", "utu"),
  ("wirt's leg", "leg"),
  ("wolf head", "dr1"),
  ("wrist blade", "wrb"),
  ("wrist spike", "9wb"),
  ("wrist sword", "7wb"),
  ("wyrmhide", "uea"),
  ("wyrmhide boots", "ulb"),
  ("yari", "9st"),
  ("yew wand", "ywn"),
  ("zakarum shield", "pae"),
  ("zod rune", "r33"),
  ("zombie head", "ne2"),
  ("zweihander", "9fb"),
];
// Total: 688 name mappings


/// Sorted item codes for D2S JM 10-bit code_index lookup.
/// Generated from item_base (profile 280).
#[rustfmt::skip]
pub const SORTED_CODES: &[&str] = &[
    "0sc",
    "2ax",
    "2hs",
    "6bs",
    "6cb",
    "6cs",
    "6hb",
    "6hx",
    "6l7",
    "6lb",
    "6ls",
    "6lw",
    "6lx",
    "6mx",
    "6rx",
    "6s7",
    "6sb",
    "6ss",
    "6sw",
    "6ws",
    "72a",
    "72h",
    "7ar",
    "7ax",
    "7b7",
    "7b8",
    "7ba",
    "7bk",
    "7bl",
    "7br",
    "7bs",
    "7bt",
    "7bw",
    "7cl",
    "7cm",
    "7cr",
    "7cs",
    "7dg",
    "7di",
    "7fb",
    "7fc",
    "7fl",
    "7ga",
    "7gd",
    "7gi",
    "7gl",
    "7gm",
    "7gs",
    "7gw",
    "7h7",
    "7ha",
    "7ja",
    "7kr",
    "7la",
    "7ls",
    "7lw",
    "7m7",
    "7ma",
    "7mp",
    "7mt",
    "7o7",
    "7p7",
    "7pa",
    "7pi",
    "7qr",
    "7qs",
    "7s7",
    "7s8",
    "7sb",
    "7sc",
    "7sm",
    "7sp",
    "7sr",
    "7ss",
    "7st",
    "7ta",
    "7tk",
    "7tr",
    "7ts",
    "7tw",
    "7vo",
    "7wa",
    "7wb",
    "7wc",
    "7wd",
    "7wh",
    "7wn",
    "7ws",
    "7xf",
    "7yw",
    "8bs",
    "8cb",
    "8cs",
    "8hb",
    "8hx",
    "8l8",
    "8lb",
    "8ls",
    "8lw",
    "8lx",
    "8mx",
    "8rx",
    "8s8",
    "8sb",
    "8ss",
    "8sw",
    "8ws",
    "92a",
    "92h",
    "9ar",
    "9ax",
    "9b7",
    "9b8",
    "9b9",
    "9ba",
    "9bk",
    "9bl",
    "9br",
    "9bs",
    "9bt",
    "9bw",
    "9cl",
    "9cm",
    "9cr",
    "9cs",
    "9dg",
    "9di",
    "9fb",
    "9fc",
    "9fl",
    "9ga",
    "9gd",
    "9gi",
    "9gl",
    "9gm",
    "9gs",
    "9gw",
    "9h9",
    "9ha",
    "9ja",
    "9kr",
    "9la",
    "9ls",
    "9lw",
    "9m9",
    "9ma",
    "9mp",
    "9mt",
    "9p9",
    "9pa",
    "9pi",
    "9qr",
    "9qs",
    "9s8",
    "9s9",
    "9sb",
    "9sc",
    "9sm",
    "9sp",
    "9sr",
    "9ss",
    "9st",
    "9ta",
    "9tk",
    "9tr",
    "9ts",
    "9tw",
    "9vo",
    "9wa",
    "9wb",
    "9wc",
    "9wd",
    "9wh",
    "9wn",
    "9ws",
    "9xf",
    "9yw",
    "aar",
    "am1",
    "am2",
    "am3",
    "am4",
    "am5",
    "am6",
    "am7",
    "am8",
    "am9",
    "ama",
    "amb",
    "amc",
    "amd",
    "ame",
    "amf",
    "amu",
    "aqv",
    "ass",
    "axe",
    "axf",
    "ba1",
    "ba2",
    "ba3",
    "ba4",
    "ba5",
    "ba6",
    "ba7",
    "ba8",
    "ba9",
    "baa",
    "bab",
    "bac",
    "bad",
    "bae",
    "baf",
    "bal",
    "bar",
    "bax",
    "bbb",
    "bet",
    "bey",
    "bhm",
    "bkd",
    "bkf",
    "bks",
    "bld",
    "box",
    "bpl",
    "bps",
    "brn",
    "brs",
    "brz",
    "bsd",
    "bsh",
    "bst",
    "bsw",
    "btl",
    "btx",
    "buc",
    "bwn",
    "cap",
    "cbw",
    "ceh",
    "ces",
    "chn",
    "ci0",
    "ci1",
    "ci2",
    "ci3",
    "cjw",
    "clb",
    "clm",
    "clw",
    "cm1",
    "cm2",
    "cm3",
    "cqv",
    "crn",
    "crs",
    "cst",
    "d33",
    "dgr",
    "dhn",
    "dir",
    "dr1",
    "dr2",
    "dr3",
    "dr4",
    "dr5",
    "dr6",
    "dr7",
    "dr8",
    "dr9",
    "dra",
    "drb",
    "drc",
    "drd",
    "dre",
    "drf",
    "ear",
    "elx",
    "eyz",
    "fed",
    "fhl",
    "fla",
    "flb",
    "flc",
    "fld",
    "flg",
    "fng",
    "ful",
    "g33",
    "g34",
    "gax",
    "gcb",
    "gcg",
    "gcr",
    "gcv",
    "gcw",
    "gcy",
    "gfb",
    "gfg",
    "gfr",
    "gfv",
    "gfw",
    "gfy",
    "ghm",
    "gis",
    "gix",
    "glb",
    "gld",
    "glg",
    "glr",
    "glv",
    "glw",
    "gly",
    "gma",
    "gpb",
    "gpg",
    "gpl",
    "gpm",
    "gpr",
    "gps",
    "gpv",
    "gpw",
    "gpy",
    "gsb",
    "gsc",
    "gsd",
    "gsg",
    "gsr",
    "gsv",
    "gsw",
    "gsy",
    "gth",
    "gts",
    "gwn",
    "gzv",
    "hal",
    "hax",
    "hbl",
    "hbt",
    "hbw",
    "hdm",
    "hfh",
    "hgl",
    "hla",
    "hlm",
    "hp1",
    "hp2",
    "hp3",
    "hp4",
    "hp5",
    "hpf",
    "hpo",
    "hrb",
    "hrn",
    "hrt",
    "hst",
    "hxb",
    "ibk",
    "ice",
    "isc",
    "j34",
    "jav",
    "jaw",
    "jew",
    "key",
    "kit",
    "kri",
    "ktr",
    "lax",
    "lbb",
    "lbl",
    "lbt",
    "lbw",
    "lea",
    "leg",
    "lgl",
    "lrg",
    "lsd",
    "lst",
    "ltp",
    "luv",
    "lwb",
    "lxb",
    "mac",
    "mau",
    "mbl",
    "mbr",
    "mbt",
    "mgl",
    "mp1",
    "mp2",
    "mp3",
    "mp4",
    "mp5",
    "mpf",
    "mpi",
    "mpo",
    "msf",
    "msk",
    "mss",
    "mst",
    "mxb",
    "ne1",
    "ne2",
    "ne3",
    "ne4",
    "ne5",
    "ne6",
    "ne7",
    "ne8",
    "ne9",
    "nea",
    "neb",
    "ned",
    "nee",
    "nef",
    "neg",
    "ob1",
    "ob2",
    "ob3",
    "ob4",
    "ob5",
    "ob6",
    "ob7",
    "ob8",
    "ob9",
    "oba",
    "obb",
    "obc",
    "obd",
    "obe",
    "obf",
    "opl",
    "opm",
    "ops",
    "pa1",
    "pa2",
    "pa3",
    "pa4",
    "pa5",
    "pa6",
    "pa7",
    "pa8",
    "pa9",
    "paa",
    "pab",
    "pac",
    "pad",
    "pae",
    "paf",
    "pax",
    "pik",
    "pil",
    "pk1",
    "pk2",
    "pk3",
    "plt",
    "qbr",
    "qey",
    "qf1",
    "qf2",
    "qhr",
    "qll",
    "qui",
    "r01",
    "r02",
    "r03",
    "r04",
    "r05",
    "r06",
    "r07",
    "r08",
    "r09",
    "r10",
    "r11",
    "r12",
    "r13",
    "r14",
    "r15",
    "r16",
    "r17",
    "r18",
    "r19",
    "r20",
    "r21",
    "r22",
    "r23",
    "r24",
    "r25",
    "r26",
    "r27",
    "r28",
    "r29",
    "r30",
    "r31",
    "r32",
    "r33",
    "rin",
    "rng",
    "rpl",
    "rps",
    "rvl",
    "rvs",
    "rxb",
    "sbb",
    "sbr",
    "sbw",
    "scl",
    "scm",
    "scp",
    "scy",
    "scz",
    "skc",
    "skf",
    "skl",
    "skp",
    "skr",
    "sku",
    "skz",
    "sml",
    "sol",
    "spc",
    "spe",
    "spk",
    "spl",
    "spr",
    "spt",
    "ssd",
    "ssp",
    "sst",
    "std",
    "stu",
    "swb",
    "tal",
    "tax",
    "tbk",
    "tbl",
    "tbt",
    "tch",
    "tes",
    "tgl",
    "tkf",
    "toa",
    "tow",
    "tr1",
    "tr2",
    "tri",
    "tsc",
    "tsp",
    "ua1",
    "ua2",
    "ua3",
    "ua4",
    "ua5",
    "uap",
    "uar",
    "ucl",
    "uea",
    "uh9",
    "uhb",
    "uhc",
    "uhg",
    "uhl",
    "uhm",
    "uhn",
    "uit",
    "ukp",
    "ula",
    "ulb",
    "ulc",
    "uld",
    "ulg",
    "ulm",
    "ult",
    "um1",
    "um2",
    "um3",
    "um4",
    "um5",
    "um6",
    "umb",
    "umc",
    "umg",
    "uml",
    "ung",
    "uow",
    "upk",
    "upl",
    "urg",
    "urn",
    "urs",
    "ush",
    "usk",
    "utb",
    "utc",
    "utg",
    "uth",
    "utp",
    "uts",
    "utu",
    "uuc",
    "uui",
    "uul",
    "uvb",
    "uvc",
    "uvg",
    "vbl",
    "vbt",
    "vgl",
    "vip",
    "vou",
    "vps",
    "wa1",
    "wa2",
    "wa3",
    "wa4",
    "wa5",
    "wa6",
    "wa7",
    "wa8",
    "wa9",
    "waa",
    "wab",
    "wac",
    "wad",
    "wae",
    "waf",
    "wax",
    "whm",
    "wms",
    "wnd",
    "wrb",
    "wsc",
    "wsd",
    "wsp",
    "wst",
    "xa1",
    "xa2",
    "xa3",
    "xa4",
    "xa5",
    "xap",
    "xar",
    "xcl",
    "xea",
    "xh9",
    "xhb",
    "xhg",
    "xhl",
    "xhm",
    "xhn",
    "xit",
    "xkp",
    "xla",
    "xlb",
    "xld",
    "xlg",
    "xlm",
    "xlt",
    "xmb",
    "xmg",
    "xml",
    "xng",
    "xow",
    "xpk",
    "xpl",
    "xrg",
    "xrn",
    "xrs",
    "xsh",
    "xsk",
    "xtb",
    "xtg",
    "xth",
    "xtp",
    "xts",
    "xtu",
    "xuc",
    "xui",
    "xul",
    "xvb",
    "xvg",
    "xyz",
    "yps",
    "ywn",
    "zhb",
    "zlb",
    "zmb",
    "ztb",
    "zvb",
];
