/// Horadric Cube recipes (auto-generated from cubemain.txt)
/// Format: (description, inputs, output, is_mod_recipe)
#[rustfmt::skip]
pub const CUBE_RECIPES: &[(&str, &[&str], &str, bool)] = &[
  ("Staff of Kings + Amulet of the Viper -> Horadric Staff", &["msf", "vip"], "hst", false),
  ("Khalim's Flail + Khalim's Heart + Khalim's Eye + Khalim's Brain -> Khalim's Will", &["qf1", "qhr", "qey", "qbr"], "qf2", false),
  ("Wirt's Leg + Tome of Town Portal -> Portal to The Secret Cow Level", &["leg", "tbk"], "Cow Portal", false),
  ("3 Healing Potions (Any) + 3 Mana Potions (Any) + 1 Standard Gem (Any) -> Full Rejuvenation Potion", &["\"hpot,qty=3\"", "\"mpot,qty=3\"", "gem2"], "rvl", false),
  ("3 Healing Potions (Any) + 3 Mana Potions (Any)  + 1 Chipped Gem (Any) -> Rejuvenation Potion", &["\"hpot,qty=3\"", "\"mpot,qty=3\"", "gem0"], "rvs", false),
  ("3 Rejuvenation Potions -> Full Rejuvenation Potion", &["\"rvs,qty=3\""], "rvl", false),
  ("6 Perfect Gems (1 of each type) + 1 Magic Amulet -> Prismatic Amulet", &["\"amu,mag\"", "gpv", "gpy", "gpb", "gpg", "gpr", "gpw"], "\"amu,mag,pre=331\"", false),
  ("1 Magic Ring + 1 Perfect Ruby + 1 Exploding Potion -> Garnet Ring", &["\"rin,mag\"", "gpr", "opm"], "\"rin,mag,pre=372\"", false),
  ("1 Magic Ring + 1 Perfect Sapphire + 1 Thawing Potion -> Cobalt Ring", &["\"rin,mag\"", "gpb", "wms"], "\"rin,mag,pre=353\"", false),
  ("1 Magic Ring + 1 Perfect Topaz + 1 Rejuvenation Potion -> Coral Ring", &["\"rin,mag\"", "gpy", "rvs"], "\"rin,mag,pre=392\"", false),
  ("1 Magic Ring + 1 Standard Emerald + 1 Antidote Potion -> Jade Ring", &["\"rin,mag\"", "gpg", "yps"], "\"rin,mag,pre=412\"", false),
  ("1 Axe (Any) + 1 Dagger (Any) -> Throwing Axe", &["axe", "knif"], "\"tax,nor\"", false),
  ("1 Spear (Any) + 1 Arrows -> Javelins", &["spea", "aqv"], "\"jav,nor\"", false),
  ("3 Magic Rings -> Magic Amulet", &["\"rin,mag,qty=3\""], "\"amu,mag\"", false),
  ("3 Magic Amulets -> Magic Ring", &["\"amu,mag,qty=3\""], "\"rin,mag\"", false),
  ("3 Standard Gems + 1 Socketed Weapon ->  Socketed Magic Weapon", &["\"weap,sock\"", "\"gem2,qty=3\""], "\"usetype,mag\"", false),
  ("3 Flawless Gems + 1 Magic Weapon -> Socketed Magic Weapon", &["\"weap,mag\"", "\"gem3,qty=3\""], "\"usetype,mag\"", false),
  ("1 Magic Shield + 1 Spiked Club + 2 Skulls (Any) -> Magic Shield of Spikes", &["\"shld,mag\"", "\"gemz,qty=2\"", "spc"], "\"usetype,mag,suf=162\"", false),
  ("4 Healing Potions (Any) + 1 Standard Ruby + 1 Magic Sword -> Sword of the Leech", &["\"swor,mag\"", "gemr", "\"hpot,qty=4\""], "\"usetype,mag,suf=352\"", false),
  ("1 Diamond (Any) + 1 Kris + 1 Staff + 1 Belt -> Savage Polearm", &["kri", "gemd", "staf", "belt"], "\"pole,mag,pre=191\"", false),
  ("1 Strangling Gas Potion + 1 Healing Potion (Any) -> Antidote Potion", &["gpl", "hpot"], "yps", false),
  ("2 Arrows -> Bolts", &["\"aqv,qty=2\""], "cqv", false),
  ("2 Bolts -> Arrows", &["\"cqv,qty=2\""], "aqv", false),
  ("3 Chipped Amethysts -> Flawed Amethyst", &["\"gcv,qty=3\""], "gfv", false),
  ("3 Flawed Amethysts -> Standard Amethyst", &["\"gfv,qty=3\""], "gsv", false),
  ("3 Standard Amethysts -> Flawless Amethyst", &["\"gsv,qty=3\""], "gzv", false),
  ("3 Flawless Amethysts -> Perfect Amethyst", &["\"gzv,qty=3\""], "gpv", false),
  ("3 Chipped Rubies -> Flawed Ruby", &["\"gcr,qty=3\""], "gfr", false),
  ("3 Flawed Rubies -> Standard Ruby", &["\"gfr,qty=3\""], "gsr", false),
  ("3 Standard Rubies -> Flawless Ruby", &["\"gsr,qty=3\""], "glr", false),
  ("3 Flawless Rubies -> Perfect Ruby", &["\"glr,qty=3\""], "gpr", false),
  ("3 Chipped Sapphires -> Flawed Sapphire", &["\"gcb,qty=3\""], "gfb", false),
  ("3 Flawed Sapphires -> Standard Sapphire", &["\"gfb,qty=3\""], "gsb", false),
  ("3 Standard Sapphires -> Flawless Sapphire", &["\"gsb,qty=3\""], "glb", false),
  ("3 Flawless Sapphires -> Perfect Sapphire", &["\"glb,qty=3\""], "gpb", false),
  ("3 Chipped Topazes -> Flawed Topaz", &["\"gcy,qty=3\""], "gfy", false),
  ("3 Flawed Topazes -> Standard Topaz", &["\"gfy,qty=3\""], "gsy", false),
  ("3 Standard Topazes -> Flawless Topaz", &["\"gsy,qty=3\""], "gly", false),
  ("3 Flawless Topazes -> Perfect Topaz", &["\"gly,qty=3\""], "gpy", false),
  ("3 Chipped Emeralds -> Flawed Emerald", &["\"gcg,qty=3\""], "gfg", false),
  ("3 Flawed Emeralds -> Standard Emerald", &["\"gfg,qty=3\""], "gsg", false),
  ("3 Standard Emeralds -> Flawless Emerald", &["\"gsg,qty=3\""], "glg", false),
  ("3 Flawless Emeralds -> Perfect Emerald", &["\"glg,qty=3\""], "gpg", false),
  ("3 Chipped Diamonds -> Flawed Diamond", &["\"gcw,qty=3\""], "gfw", false),
  ("3 Flawed Diamonds -> Standard Diamond", &["\"gfw,qty=3\""], "gsw", false),
  ("3 Standard Diamonds -> Flawless Diamond", &["\"gsw,qty=3\""], "glw", false),
  ("3 Flawless Diamonds -> Perfect Diamond", &["\"glw,qty=3\""], "gpw", false),
  ("3 Chipped Skulls -> Flawed Skull", &["\"skc,qty=3\""], "skf", false),
  ("3 Flawed Skulls -> Standard Skull", &["\"skf,qty=3\""], "sku", false),
  ("3 Standard Skulls -> Flawless Skull", &["\"sku,qty=3\""], "skl", false),
  ("3 Flawless Skulls -> Perfect Skull", &["\"skl,qty=3\""], "skz", false),
  ("3 El Runes -> Eld Rune", &["\"r01,qty=3\""], "r02", false),
  ("3 Eld Runes -> Tir Rune", &["\"r02,qty=3\""], "r03", false),
  ("3 Tir Runes -> Nef Rune", &["\"r03,qty=3\""], "r04", false),
  ("3 Nef Runes -> Eth Rune", &["\"r04,qty=3\""], "r05", false),
  ("3 Eth Runes -> Ith Rune", &["\"r05,qty=3\""], "r06", false),
  ("3 Ith Runes -> Tal Rune", &["\"r06,qty=3\""], "r07", false),
  ("3 Tal Runes -> Ral Rune", &["\"r07,qty=3\""], "r08", false),
  ("3 Ral Runes -> Ort Rune", &["\"r08,qty=3\""], "r09", false),
  ("3 Ort Runes -> Thul Rune", &["\"r09,qty=3\""], "r10", false),
  ("3 Perfect Gems (Any) + 1 Magic Item -> Re-rolled Magic Item", &["\"any,mag\"", "\"gem4,qty=3\""], "\"usetype,mag\"", false),
  ("6 Perfect Skulls + 1 Rare Item -> 1 Low Quality Rare Item", &["\"any,rar\"", "\"skz,qty=6\""], "\"usetype,rar\"", false),
  ("1 Perfect Skull + 1 Rare Item + 1 Stone of Jordan -> 1 High Quality Rare Item", &["\"any,rar\"", "skz", "The Stone of Jordan"], "\"usetype,rar\"", false),
  ("3 Perfect Skull + 1 Rare Item + 1 Stone of Jordan -> Add 1 Socket to Rare Item", &["\"any,rar,nos\"", "\"skz,qty=3\"", "The Stone of Jordan"], "\"useitem,sock=1\"", false),
  ("1 Magic Full Helm + 1 Jewel + 1 Ith Rune + 1 Perfect Sapphire -> Hit Power Helm", &["\"fhl,mag,upg\"", "jew", "r06", "gpb"], "\"usetype,crf\"", false),
  ("1 Magic Chain Boots + 1 Jewel + 1 Ral Rune + 1 Perfect Sapphire -> Hit Power Boots", &["\"mbt,mag,upg\"", "jew", "r08", "gpb"], "\"usetype,crf\"", false),
  ("1 Magic Chain Gloves + 1 Jewel + 1 Ort Rune + 1 Perfect Sapphire -> Hit Power Gloves", &["\"mgl,mag,upg\"", "jew", "r09", "gpb"], "\"usetype,crf\"", false),
  ("1 Magic Heavy Belt + 1 Jewel + 1 Tal Rune + 1 Perfect Sapphire -> Hit Power Belt", &["\"tbl,mag,upg\"", "jew", "r07", "gpb"], "\"usetype,crf\"", false),
  ("1 Magic Gothic Shield + 1 Jewel + 1 Eth Rune + 1 Perfect Sapphire -> Hit Power Shield", &["\"gts,mag,upg\"", "jew", "r05", "gpb"], "\"usetype,crf\"", false),
  ("1 Magic Field Plate + 1 Jewel + 1 Nef Rune + 1 Perfect Sapphire -> Hit Power Body", &["\"fld,mag,upg\"", "jew", "r04", "gpb"], "\"usetype,crf\"", false),
  ("1 Magic Amulet + 1 Jewel + Thul Rune + 1 Perfect Sapphire -> Hit Power Amulet", &["\"amul,mag\"", "jew", "r10", "gpb"], "\"usetype,crf\"", false),
  ("1 Magic Ring + 1 Jewel + 1 Amn Rune + 1 Perfect Sapphire -> Hit Power Ring", &["\"ring,mag\"", "jew", "r11", "gpb"], "\"usetype,crf\"", false),
  ("1 Magic Blunt Weapon + 1 Jewel + 1 Tir Rune + 1 Perfect Sapphire -> Hit Power Weapon", &["\"blun,mag\"", "jew", "r03", "gpb"], "\"usetype,crf\"", false),
  ("1 Magic Helm + 1 Jewel + 1 Ral Rune + 1 Perfect Ruby -> Blood Helm", &["\"hlm,mag,upg\"", "jew", "r08", "gpr"], "\"usetype,crf\"", false),
  ("1 Magic Light Plated Boots + 1 Jewel + 1 Eth Rune + 1 Perfect Ruby -> Blood Boots", &["\"tbt,mag,upg\"", "jew", "r05", "gpr"], "\"usetype,crf\"", false),
  ("1 Magic Heavy Gloves + 1 Jewel + 1 Nef Rune + 1 Perfect Ruby -> Blood Gloves", &["\"vgl,mag,upg\"", "jew", "r04", "gpr"], "\"usetype,crf\"", false),
  ("1 Magic Belt + 1 Jewel + 1 Tal Rune + 1 Perfect Ruby -> Blood Belt", &["\"mbl,mag,upg\"", "jew", "r07", "gpr"], "\"usetype,crf\"", false),
  ("1 Magic Spiked Shield + 1 Jewel + 1 Ith Rune + 1 Perfect Ruby -> Blood Shield", &["\"spk,mag,upg\"", "jew", "r06", "gpr"], "\"usetype,crf\"", false),
  ("1 Magic Plate Mail + 1 Jewel + 1 Thul Rune + 1 Perfect Ruby -> Blood Body", &["\"plt,mag,upg\"", "jew", "r10", "gpr"], "\"usetype,crf\"", false),
  ("1 Magic Amulet + 1 Jewel + 1 Amn Rune + 1 Perfect Ruby -> Blood Amulet", &["\"amul,mag\"", "jew", "r11", "gpr"], "\"usetype,crf\"", false),
  ("1 Magic Ring + 1 Jewel + 1 Sol Rune + 1 Perfect Ruby -> Blood Ring", &["\"ring,mag\"", "jew", "r12", "gpr"], "\"usetype,crf\"", false),
  ("1 Magic Axe + 1 Jewel + Ort Rune + 1 Perfect Ruby -> Blood Weapon", &["\"axe,mag\"", "jew", "r09", "gpr"], "\"usetype,crf\"", false),
  ("1 Magic Mask + 1 Jewel + Nef Rune + 1 Perfect Amethyst -> Caster Helm", &["\"msk,mag,upg\"", "jew", "r04", "gpv"], "\"usetype,crf\"", false),
  ("1 Magic Boots + 1 Jewel + Thul Rune + 1 Perfect Amethyst -> Caster Boots", &["\"lbt,mag,upg\"", "jew", "r10", "gpv"], "\"usetype,crf\"", false),
  ("1 Magic Leather Gloves + 1 Jewel + Ort Rune + 1 Perfect Amethyst -> Caster Gloves", &["\"lgl,mag,upg\"", "jew", "r09", "gpv"], "\"usetype,crf\"", false),
  ("1 Magic Light Belt + 1 Jewel + Ith Rune + 1 Perfect Amethyst -> Caster Belt", &["\"vbl,mag,upg\"", "jew", "r06", "gpv"], "\"usetype,crf\"", false),
  ("1 Magic Small Shield + 1 Jewel + 1 Eth Rune + 1 Perfect Amethyst -> Caster Shield", &["\"sml,mag,upg\"", "jew", "r05", "gpv"], "\"usetype,crf\"", false),
  ("1 Magic Light Plate + 1 Jewel + 1 Tal Rune + 1 Perfect Amethyst -> Caster Body", &["\"ltp,mag,upg\"", "jew", "r07", "gpv"], "\"usetype,crf\"", false),
  ("1 Magic Amulet + 1 Jewel + 1 Ral Rune + 1 Perfect Amethyst -> Caster Amulet", &["\"amul,mag\"", "jew", "r08", "gpv"], "\"usetype,crf\"", false),
  ("1 Magic Ring + 1 Jewel + 1 Amn Rune + 1 Perfect Amethyst -> Caster Ring", &["\"ring,mag\"", "jew", "r11", "gpv"], "\"usetype,crf\"", false),
  ("1 Magic Rod + 1 Jewel + 1 Tir Rune + 1 Perfect Amethyst -> Caster Weapon", &["\"rod,mag\"", "jew", "r03", "gpv"], "\"usetype,crf\"", false),
  ("1 Magic Crown + 1 Jewel + 1 Ith Rune + 1 Perfect Emerald -> Safety Helm", &["\"crn,mag,upg\"", "jew", "r06", "gpg"], "\"usetype,crf\"", false),
  ("1 Magic Plated Boots + 1 Jewel + 1 Ort Rune + 1 Perfect Emerald -> Safety Boots", &["\"hbt,mag,upg\"", "jew", "r09", "gpg"], "\"usetype,crf\"", false),
  ("1 Magic Gauntlets + 1 Jewel + 1 Ral Rune + 1 Perfect Emerald -> Safety Gloves", &["\"hgl,mag,upg\"", "jew", "r08", "gpg"], "\"usetype,crf\"", false),
  ("1 Magic Sash + 1 Jewel + 1 Tal Rune + 1 Perfect Emerald -> Safety Belt", &["\"lbl,mag,upg\"", "jew", "r07", "gpg"], "\"usetype,crf\"", false),
  ("1 Magic Kite Shield + 1 Jewel + 1 Nef Rune + 1 Perfect Emerald -> Safety Shield", &["\"kit,mag,upg\"", "jew", "r04", "gpg"], "\"usetype,crf\"", false),
  ("1 Magic Breast Plate + 1 Jewel + 1 Eth Rune + 1 Perfect Emerald -> Safety Body", &["\"brs,mag,upg\"", "jew", "r05", "gpg"], "\"usetype,crf\"", false),
  ("1 Magic Amulet + 1 Jewel + 1 Thul Rune + 1 Perfect Emerald -> Safety Amulet", &["\"amul,mag\"", "jew", "r10", "gpg"], "\"usetype,crf\"", false),
  ("1 Magic Ring + 1 Jewel + 1 Amn Rune + 1 Perfect Emerald -> Safety Ring", &["\"ring,mag\"", "jew", "r11", "gpg"], "\"usetype,crf\"", false),
  ("1 Magic Spear + 1 Jewel + 1 Sol Rune + 1 Perfect Emerald -> Safety Weapon", &["\"spea,mag\"", "jew", "r12", "gpg"], "\"usetype,crf\"", false),
  ("3 Thul Runes + 1 Chipped Topaz -> Amn Rune", &["\"r10,qty=3\"", "gcy"], "r11", false),
  ("3 Amn Runes + 1 Chipped Amethyst -> Sol Rune", &["\"r11,qty=3\"", "gcv"], "r12", false),
  ("3 Sol Runes + 1 Chipped Sapphire -> Shael Rune", &["\"r12,qty=3\"", "gcb"], "r13", false),
  ("3 Shael Runes + 1 Chipped Ruby -> Dol Rune", &["\"r13,qty=3\"", "gcr"], "r14", false),
  ("3 Dol Runes + 1 Chipped Emerald -> Hel Rune", &["\"r14,qty=3\"", "gcg"], "r15", false),
  ("3 Hel Runes + 1 Chipped Diamond -> Io Rune", &["\"r15,qty=3\"", "gcw"], "r16", false),
  ("3 Io Runes + 1 Flawed Topaz -> Lum Rune", &["\"r16,qty=3\"", "gfy"], "r17", false),
  ("3 Lum Runes + 1 Flawed Amethyst -> Ko Rune", &["\"r17,qty=3\"", "gfv"], "r18", false),
  ("3 Ko Runes + 1 Flawed Sapphire -> Fal Rune", &["\"r18,qty=3\"", "gfb"], "r19", false),
  ("3 Fal Runes + 1 Flawed Ruby -> Lem Rune", &["\"r19,qty=3\"", "gfr"], "r20", false),
  ("3 Lem Runes + 1 Flawed Emerald -> Pul Rune", &["\"r20,qty=3\"", "gfg"], "r21", false),
  ("2 Pul Runes + 1 Flawed Diamond -> Um Rune", &["\"r21,qty=2\"", "gfw"], "r22", false),
  ("2 Um Runes + 1 Standard Topaz -> Mal Rune", &["\"r22,qty=2\"", "gsy"], "r23", false),
  ("2 Mal Runes + 1 Standard Amethyst -> Ist Rune", &["\"r23,qty=2\"", "gsv"], "r24", false),
  ("2 Ist Runes + 1 Standard Sapphire -> Gul Rune", &["\"r24,qty=2\"", "gsb"], "r25", false),
  ("2 Gul Runes + 1 Standard Ruby -> Vex Rune", &["\"r25,qty=2\"", "gsr"], "r26", false),
  ("2 Vex Runes + 1 Standard Emerald -> Ohm Rune", &["\"r26,qty=2\"", "gsg"], "r27", false),
  ("2 Ohm Runes + 1 Standard Diamond -> Lo Rune", &["\"r27,qty=2\"", "gsw"], "r28", false),
  ("2 Lo Runes + 1 Flawless Topaz -> Sur Rune", &["\"r28,qty=2\"", "gly"], "r29", false),
  ("2 Sur Runes + 1 Flawless Amethyst -> Ber Rune", &["\"r29,qty=2\"", "gzv"], "r30", false),
  ("2 Ber Runes + 1 Flawless Sapphire -> Jah Rune", &["\"r30,qty=2\"", "glb"], "r31", false),
  ("2 Jah Runes + 1 Flawless Ruby -> Cham Rune", &["\"r31,qty=2\"", "glr"], "r32", false),
  ("2 Cham Runes + 1 Flawless Emerald -> Zod Rune", &["\"r32,qty=2\"", "glg"], "r33", false),
  ("1 Tal Rune + 1 Thul Rune + 1 Perfect Topaz + 1 Normal Torso Armor -> Socketed Torso Armor", &["\"tors,nor,nos\"", "r07", "r10", "gpy"], "useitem", false),
  ("1 Ral Rune + 1 Amn Rune + 1 Perfect Amethyst + 1 Normal Weapon -> Socketed Weapon", &["\"weap,nor,nos\"", "r08", "r11", "gpv"], "useitem", false),
  ("1 Ral Rune + 1 Thul Rune + 1 Perfect Sapphire + 1 Normal Helm -> Socketed Helm", &["\"helm,nor,nos\"", "r08", "r10", "gpb"], "useitem", false),
  ("1 Tal Rune + 1 Amn Rune + 1 Perfect Ruby + 1 Normal Shield -> Socketed Shield", &["\"shld,nor,nos\"", "r07", "r11", "gpr"], "useitem", false),
  ("1 Eld Rune + 1 Chipped Gem (Any) + 1 Low Quality Weapon -> Normal Weapon", &["\"weap,low\"", "r02", "gem0"], "\"usetype,nor\"", false),
  ("1 El Rune + 1 Chipped Gem (Any) + 1 Low Quality Armor -> Normal Armor", &["\"armo,low\"", "r01", "gem0"], "\"usetype,nor\"", false),
  ("1 Ral Rune + 1 Sol Rune + 1 Perfect Emerald + 1 Normal Unique Weapon -> Exceptional Unique Weapon", &["\"weap,bas,uni\"", "r08", "r12", "gpg"], "\"useitem,mod,exc\"", false),
  ("1 Tal Rune + 1 Shael Rune + 1 Perfect Diamond + 1 Normal Unique Armor -> Exceptional Unique Armor", &["\"armo,bas,uni\"", "r07", "r13", "gpw"], "\"useitem,mod,exc\"", false),
  ("1 Lum Rune + 1 Pul Rune + 1 Perfect Emerald + 1 Exceptional Unique Weapon -> Elite Unique Weapon", &["\"weap,exc,uni\"", "r17", "r21", "gpg"], "\"useitem,mod,eli\"", false),
  ("1 Ko Rune + 1 Lem Rune + 1 Perfect Diamond + 1 Exceptional Unique Armor -> Elite Unique Armor", &["\"armo,exc,uni\"", "r18", "r20", "gpw"], "\"useitem,mod,eli\"", false),
  ("1 Ort Rune + 1 Amn Rune + 1 Perfect Sapphire + 1 Normal Rare Weapon -> Exceptional Rare Weapon", &["\"weap,bas,rar\"", "r09", "r11", "gpb"], "\"useitem,mod,exc\"", false),
  ("1 Ral Rune + 1 Thul Rune + 1 Perfect Amethyst + 1 Normal Rare Armor -> Exceptional Rare Armor", &["\"armo,bas,rar\"", "r08", "r10", "gpv"], "\"useitem,mod,exc\"", false),
  ("1 Fal Rune + 1 Um Rune + 1 Perfect Sapphire + 1 Exceptional Rare Weapon -> Elite Rare Weapon", &["\"weap,exc,rar\"", "r19", "r22", "gpb"], "\"useitem,mod,eli\"", false),
  ("1 Ko Rune + 1 Pul Rune + 1 Perfect Amethyst + 1 Exceptional Rare Armor -> Elite Rare Armor", &["\"armo,exc,rar\"", "r18", "r21", "gpv"], "\"useitem,mod,eli\"", false),
  ("1 Ort Rune + 1 Weapon -> Fully Repaired Weapon", &["\"weap,noe\"", "r09"], "\"useitem,rep,qty=255\"", false),
  ("1 Ral Rune + 1 Armor -> Fully Repaired Armor", &["\"armo,noe\"", "r08"], "\"useitem,rep,qty=255\"", false),
  ("1 Ort Rune + 1 Chipped Gem (Any) + 1 Weapon -> Fully Repaired and Recharged Weapon", &["\"weap,noe\"", "r09", "gem0"], "\"useitem,rep,rch,qty=255\"", false),
  ("1 Ral Rune + 1 Flawed Gem (Any) + 1 Armor -> Fully Repaired and Recharged Armor", &["\"armo,noe\"", "r08", "gem1"], "\"useitem,rep,rch,qty=255\"", false),
  ("1 Hel Rune + Scroll of Town Portal + 1 Socketed Item -> Clear Sockets on Item", &["\"any,sock\"", "r15", "tsc"], "\"useitem,uns\"", false),
  ("1 Ral Rune + 1 Jewel + 1 Superior Armor -> Tempered Armor", &["\"armo,hiq,nos\"", "jew", "r08"], "\"useitem,tmp\"", false),
  ("1 Ral Rune + 1 Jewel + 1 Superior Weapon -> Tempered Weapon", &["\"weap,hiq,nos\"", "jew", "r08"], "\"useitem,tmp\"", false),
  ("1 Ral Rune + 1 Jewel + Magic Ring -> Tempered Ring", &["\"ring,mag\"", "jew", "r08"], "\"usetype,tmp\"", false),
  ("1 Ral Rune + 1 Jewel + 1 Magic Amulet -> Tempered Amulet", &["\"amu,mag\"", "jew", "r08"], "\"usetype,tmp\"", false),
  ("1 El Rune + 1 Chipped Gem (Any) + 1 Tempered Weapon -> Weapon With Extra Attack Rating", &["\"weap,tmp\"", "r01", "gcv"], "useitem", false),
  ("3 Chipped Gems (Any) + 1 Magic Weapon -> Socketed Magic Weapon", &["\"weap,mag\"", "\"gem0,qty=3\""], "\"usetype,mag\"", false),
  ("1 Key of Terror + 1 Key of Hate + 1 Key of Destruction -> Portal to Matron's Den/Forgotten Sands/Furnace of Pain (Random)", &["pk1", "pk2", "pk3"], "Pandemonium Portal", false),
  ("1 Diablo's Horn + 1 Baal's Eye + 1 Mephisto's Brain -> Portal to Tristram (Pandemonium Finale)", &["dhn", "bey", "mbr"], "Pandemonium Finale Portal", false),
  ("1 Twisted Essence of Suffering + 1 Charged Essence of Hatred + 1 Burning Essence of Terror + 1 Festering Essence of Destruction -> Token of Absolution", &["tes", "ceh", "bet", "fed"], "toa", false),
  ("1 Ral Rune + 1 Sol Rune + 1 Perfect Emerald + 1 Normal Set Weapon -> Exceptional Set Weapon", &["\"weap,bas,set\"", "r08", "r12", "gpg"], "\"useitem,mod,exc\"", false),
  ("1 Tal Rune + 1 Shael Rune + 1 Perfect Diamond + 1 Normal Set Armor -> Exceptional Set Armor", &["\"armo,bas,set\"", "r07", "r13", "gpw"], "\"useitem,mod,exc\"", false),
  ("1 Lum Rune + 1 Pul Rune + 1 Perfect Emerald + 1 Exceptional Set Weapon -> Elite Set Weapon", &["\"weap,exc,set\"", "r17", "r21", "gpg"], "\"useitem,mod,eli\"", false),
  ("1 Ko Rune + 1 Lem Rune + 1 Perfect Diamond + 1 Exceptional Set Armor -> Elite Set Armor", &["\"armo,exc,set\"", "r18", "r20", "gpw"], "\"useitem,mod,eli\"", false),
  ("1 Ko Rune + 1 Perfect Emerald + 1 Western Worldstone Shard + 1 Magic Amulet -> Virulent Amulet", &["\"amu,mag\"", "r18", "gpg", "xa1"], "\"useitem,pre=674\"", true),
  ("1 Ko Rune + 1 Perfect Emerald + 1 Western Worldstone Shard + 1 Magic Ring -> Virulent Ring", &["\"ring,mag\"", "r18", "gpg", "xa1"], "\"useitem,pre=673\"", true),
  ("1 Ko Rune + 1 Perfect Emerald + 1 Western Worldstone Shard + 1 Magic Helm -> Virulent Helm", &["\"helm,mag\"", "r18", "gpg", "xa1"], "\"useitem,pre=674\"", true),
  ("1 Ko Rune + 1 Perfect Emerald + 1 Western Worldstone Shard + 1 Magic Boots -> Virulent Boots", &["\"boot,mag\"", "r18", "gpg", "xa1"], "\"useitem,pre=674\"", true),
  ("1 Ko Rune + 1 Perfect Emerald + 1 Western Worldstone Shard + 1 Magic Gloves -> Virulent Gloves", &["\"glov,mag\"", "r18", "gpg", "xa1"], "\"useitem,pre=674\"", true),
  ("1 Ko Rune + 1 Perfect Emerald + 1 Western Worldstone Shard + 1 Magic Armor -> Virulent Armor", &["\"tors,mag\"", "r18", "gpg", "xa1"], "\"useitem,pre=676\"", true),
  ("1 Ko Rune + 1 Perfect Emerald + 1 Western Worldstone Shard + 1 Magic Weapon -> Virulent Weapon", &["\"weap,mag\"", "r18", "gpg", "xa1"], "\"useitem,pre=675\"", true),
  ("1 Ko Rune + 1 Perfect Emerald + 1 Western Worldstone Shard + 1 Magic Shield -> Virulent Shield", &["\"shie,mag\"", "r18", "gpg", "xa1"], "\"useitem,pre=675\"", true),
  ("1 Ko Rune + 1 Perfect Emerald + 1 Western Worldstone Shard + 1 Small Charm -> Virulent Small Charm", &["\"scha,mag\"", "r18", "gpg", "xa1"], "\"useitem,pre=671\"", true),
  ("1 Ko Rune + 1 Perfect Emerald + 1 Western Worldstone Shard + 1 Large Charm -> Virulent Large Charm", &["\"mcha,mag\"", "r18", "gpg", "xa1"], "\"useitem,pre=673\"", true),
  ("1 Ko Rune + 1 Perfect Emerald + 1 Uber Ancient Summon Material Act1 + 1 Rotting Fissure -> Virulent Rotting Fissure", &["PreCrafted Rotting Fissure", "r18", "gpg", "xa1"], "Crafted Rotting Fissure", true),
  ("1 Lum Rune + 1 Perfect Sapphire + 1 Eastern Worldstone Shard + 1 Magic Amulet -> Gelid Amulet", &["\"amu,mag\"", "r17", "gpb", "xa2"], "\"useitem,pre=684\"", true),
  ("1 Lum Rune + 1 Perfect Sapphire + 1 Eastern Worldstone Shard + 1 Magic Ring -> Gelid Ring", &["\"ring,mag\"", "r17", "gpb", "xa2"], "\"useitem,pre=683\"", true),
  ("1 Lum Rune + 1 Perfect Sapphire + 1 Eastern Worldstone Shard + 1 Magic Helm -> Gelid Helm", &["\"helm,mag\"", "r17", "gpb", "xa2"], "\"useitem,pre=684\"", true),
  ("1 Lum Rune + 1 Perfect Sapphire + 1 Eastern Worldstone Shard + 1 Magic Boots -> Gelid Boots", &["\"boot,mag\"", "r17", "gpb", "xa2"], "\"useitem,pre=684\"", true),
  ("1 Lum Rune + 1 Perfect Sapphire + 1 Eastern Worldstone Shard + 1 Magic Gloves -> Gelid Gloves", &["\"glov,mag\"", "r17", "gpb", "xa2"], "\"useitem,pre=684\"", true),
  ("1 Lum Rune + 1 Perfect Sapphire + 1 Eastern Worldstone Shard + 1 Magic Armor -> Gelid Armor", &["\"tors,mag\"", "r17", "gpb", "xa2"], "\"useitem,pre=686\"", true),
  ("1 Lum Rune + 1 Perfect Sapphire + 1 Eastern Worldstone Shard + 1 Magic Weapon -> Gelid Weapon", &["\"weap,mag\"", "r17", "gpb", "xa2"], "\"useitem,pre=685\"", true),
  ("1 Lum Rune + 1 Perfect Sapphire + 1 Eastern Worldstone Shard + 1 Magic Shield -> Gelid Shield", &["\"shie,mag\"", "r17", "gpb", "xa2"], "\"useitem,pre=685\"", true),
  ("1 Lum Rune + 1 Perfect Sapphire + 1 Eastern Worldstone Shard + 1 Small Charm -> Gelid Small Charm", &["\"scha,mag\"", "r17", "gpb", "xa2"], "\"useitem,pre=682\"", true),
  ("1 Lum Rune + 1 Perfect Sapphire + 1 Eastern Worldstone Shard + 1 Large Charm -> Gelid Large Charm", &["\"mcha,mag\"", "r17", "gpb", "xa2"], "\"useitem,pre=683\"", true),
  ("1 Lum Rune + 1 Perfect Sapphire + 1 Eastern Worldstone Shard + 1 Grand Charm -> Gelid Grand Charm", &["\"lcha,mag\"", "r17", "gpb", "xa2"], "\"useitem,pre=684\"", true),
  ("1 Lum Rune + 1 Perfect Sapphire + 1 Uber Ancient Summon Material Act2 + 1 Cold Rupture -> Gelid Cold Rupture", &["PreCrafted Cold Rupture", "r17", "gpb", "xa2"], "Crafted Cold Rupture", true),
  ("1 Fal Rune + 1 Perfect Topaz + 1 Southern Worldstone Shard + 1 Magic Amulet -> Magnetic Amulet", &["\"amu,mag\"", "r19", "gpy", "xa3"], "\"useitem,pre=689\"", true),
  ("1 Fal Rune + 1 Perfect Topaz + 1 Southern Worldstone Shard + 1 Magic Ring -> Magnetic Ring", &["\"ring,mag\"", "r19", "gpy", "xa3"], "\"useitem,pre=688\"", true),
  ("1 Fal Rune + 1 Perfect Topaz + 1 Southern Worldstone Shard + 1 Magic Helm -> Magnetic Helm", &["\"helm,mag\"", "r19", "gpy", "xa3"], "\"useitem,pre=689\"", true),
  ("1 Fal Rune + 1 Perfect Topaz + 1 Southern Worldstone Shard + 1 Magic Boots -> Magnetic Boots", &["\"boot,mag\"", "r19", "gpy", "xa3"], "\"useitem,pre=689\"", true),
  ("1 Fal Rune + 1 Perfect Topaz + 1 Southern Worldstone Shard + 1 Magic Gloves -> Magnetic Gloves", &["\"glov,mag\"", "r19", "gpy", "xa3"], "\"useitem,pre=689\"", true),
  ("1 Fal Rune + 1 Perfect Topaz + 1 Southern Worldstone Shard + 1 Magic Armor -> Magnetic Armor", &["\"tors,mag\"", "r19", "gpy", "xa3"], "\"useitem,pre=691\"", true),
  ("1 Fal Rune + 1 Perfect Topaz + 1 Southern Worldstone Shard + 1 Magic Weapon -> Magnetic Weapon", &["\"weap,mag\"", "r19", "gpy", "xa3"], "\"useitem,pre=690\"", true),
  ("1 Fal Rune + 1 Perfect Topaz + 1 Southern Worldstone Shard + 1 Magic Shield -> Magnetic Shield", &["\"shie,mag\"", "r19", "gpy", "xa3"], "\"useitem,pre=690\"", true),
  ("1 Fal Rune + 1 Perfect Topaz + 1 Southern Worldstone Shard + 1 Small Charm -> Magnetic Small Charm", &["\"scha,mag\"", "r19", "gpy", "xa3"], "\"useitem,pre=687\"", true),
  ("1 Fal Rune + 1 Perfect Topaz + 1 Southern Worldstone Shard + 1 Large Charm -> Magnetic Large Charm", &["\"mcha,mag\"", "r19", "gpy", "xa3"], "\"useitem,pre=688\"", true),
  ("1 Fal Rune + 1 Perfect Topaz + 1 Southern Worldstone Shard + 1 Grand Charm -> Magnetic Grand Charm", &["\"lcha,mag\"", "r19", "gpy", "xa3"], "\"useitem,pre=689\"", true),
  ("1 Fal Rune + 1 Perfect Topaz + 1 Uber Ancient Summon Material Act3 + 1 Crack of the Heavens -> Magnetic Crack of the Heavens", &["PreCrafted Crack of the Heavens", "r19", "gpy", "xa3"], "Crafted Crack of the Heavens", true),
  ("1 Io Rune + 1 Perfect Ruby + 1 Deep Worldstone Shard + 1 Magic Amulet -> Incendiary Amulet", &["\"amu,mag\"", "r16", "gpr", "xa4"], "\"useitem,pre=679\"", true),
  ("1 Io Rune + 1 Perfect Ruby + 1 Deep Worldstone Shard + 1 Magic Ring -> Incendiary Ring", &["\"ring,mag\"", "r16", "gpr", "xa4"], "\"useitem,pre=678\"", true),
  ("1 Io Rune + 1 Perfect Ruby + 1 Deep Worldstone Shard + 1 Magic Helm -> Incendiary Helm", &["\"helm,mag\"", "r16", "gpr", "xa4"], "\"useitem,pre=679\"", true),
  ("1 Io Rune + 1 Perfect Ruby + 1 Deep Worldstone Shard + 1 Magic Boots -> Incendiary Boots", &["\"boot,mag\"", "r16", "gpr", "xa4"], "\"useitem,pre=679\"", true),
  ("1 Io Rune + 1 Perfect Ruby + 1 Deep Worldstone Shard + 1 Magic Gloves -> Incendiary Gloves", &["\"glov,mag\"", "r16", "gpr", "xa4"], "\"useitem,pre=679\"", true),
  ("1 Io Rune + 1 Perfect Ruby + 1 Deep Worldstone Shard + 1 Magic Armor -> Incendiary Armor", &["\"tors,mag\"", "r16", "gpr", "xa4"], "\"useitem,pre=681\"", true),
  ("1 Io Rune + 1 Perfect Ruby + 1 Deep Worldstone Shard + 1 Magic Weapon -> Incendiary Weapon", &["\"weap,mag\"", "r16", "gpr", "xa4"], "\"useitem,pre=680\"", true),
  ("1 Io Rune + 1 Perfect Ruby + 1 Deep Worldstone Shard + 1 Magic Shield -> Incendiary Shield", &["\"shie,mag\"", "r16", "gpr", "xa4"], "\"useitem,pre=680\"", true),
  ("1 Io Rune + 1 Perfect Ruby + 1 Deep Worldstone Shard + 1 Small Charm -> Incendiary Small Charm", &["\"scha,mag\"", "r16", "gpr", "xa4"], "\"useitem,pre=677\"", true),
  ("1 Io Rune + 1 Perfect Ruby + 1 Deep Worldstone Shard + 1 Large Charm -> Incendiary Large Charm", &["\"mcha,mag\"", "r16", "gpr", "xa4"], "\"useitem,pre=678\"", true),
  ("1 Io Rune + 1 Perfect Ruby + 1 Deep Worldstone Shard + 1 Grand Charm -> Incendiary Grand Charm", &["\"lcha,mag\"", "r16", "gpr", "xa4"], "\"useitem,pre=679\"", true),
  ("1 Io Rune + 1 Perfect Ruby + 1 Uber Ancient Summon Material Act4 + 1 Flame Rift -> Incendiary Flame Rift", &["PreCrafted Flame Rift", "r16", "gpr", "xa4"], "Crafted Flame Rift", true),
  ("1 Pul Rune + 1 Perfect Amethyst + 1 Northern Worldstone Shard + 1 Magic Amulet -> Breaching Amulet", &["\"amu,mag\"", "r21", "gpv", "xa5"], "\"useitem,pre=699\"", true),
  ("1 Pul Rune + 1 Perfect Amethyst + 1 Northern Worldstone Shard + 1 Magic Ring -> Breaching Ring", &["\"ring,mag\"", "r21", "gpv", "xa5"], "\"useitem,pre=698\"", true),
  ("1 Pul Rune + 1 Perfect Amethyst + 1 Northern Worldstone Shard + 1 Magic Helm -> Breaching Helm", &["\"helm,mag\"", "r21", "gpv", "xa5"], "\"useitem,pre=699\"", true),
  ("1 Pul Rune + 1 Perfect Amethyst + 1 Northern Worldstone Shard + 1 Magic Boots -> Breaching Boots", &["\"boot,mag\"", "r21", "gpv", "xa5"], "\"useitem,pre=699\"", true),
  ("1 Pul Rune + 1 Perfect Amethyst + 1 Northern Worldstone Shard + 1 Magic Gloves -> Breaching Gloves", &["\"glov,mag\"", "r21", "gpv", "xa5"], "\"useitem,pre=699\"", true),
  ("1 Pul Rune + 1 Perfect Amethyst + 1 Northern Worldstone Shard + 1 Magic Armor -> Breaching Armor", &["\"tors,mag\"", "r21", "gpv", "xa5"], "\"useitem,pre=701\"", true),
  ("1 Pul Rune + 1 Perfect Amethyst + 1 Northern Worldstone Shard + 1 Magic Weapon -> Breaching Weapon", &["\"weap,mag\"", "r21", "gpv", "xa5"], "\"useitem,pre=700\"", true),
  ("1 Pul Rune + 1 Perfect Amethyst + 1 Northern Worldstone Shard + 1 Magic Shield -> Breaching Shield", &["\"shie,mag\"", "r21", "gpv", "xa5"], "\"useitem,pre=700\"", true),
  ("1 Pul Rune + 1 Perfect Amethyst + 1 Northern Worldstone Shard + 1 Small Charm -> Breaching Small Charm", &["\"scha,mag\"", "r21", "gpv", "xa5"], "\"useitem,pre=697\"", true),
  ("1 Pul Rune + 1 Perfect Amethyst + 1 Northern Worldstone Shard + 1 Large Charm -> Breaching Large Charm", &["\"mcha,mag\"", "r21", "gpv", "xa5"], "\"useitem,pre=698\"", true),
  ("1 Pul Rune + 1 Perfect Amethyst + 1 Northern Worldstone Shard + 1 Grand Charm -> Breaching Grand Charm", &["\"lcha,mag\"", "r21", "gpv", "xa5"], "\"useitem,pre=699\"", true),
  ("1 Pul Rune + 1 Perfect Amethyst + 1 Uber Ancient Summon Material Act5 + 1 Bone Break -> Breaching Bone Break", &["PreCrafted Bone Break", "r21", "gpv", "xa5"], "Crafted Bone Break", true),
  ("1 Mal Rune + 1 Perfect Diamond + 1 Northern Worldstone Shard + 1 Magic Amulet -> Mystical Amulet", &["\"amu,mag\"", "r23", "gpw", "xa5"], "\"useitem,pre=694\"", true),
  ("1 Mal Rune + 1 Perfect Diamond + 1 Northern Worldstone Shard + 1 Magic Ring -> Mystical Ring", &["\"ring,mag\"", "r23", "gpw", "xa5"], "\"useitem,pre=693\"", true),
  ("1 Mal Rune + 1 Perfect Diamond + 1 Northern Worldstone Shard + 1 Magic Helm -> Mystical Helm", &["\"helm,mag\"", "r23", "gpw", "xa5"], "\"useitem,pre=694\"", true),
  ("1 Mal Rune + 1 Perfect Diamond + 1 Northern Worldstone Shard + 1 Magic Boots -> Mystical Boots", &["\"boot,mag\"", "r23", "gpw", "xa5"], "\"useitem,pre=694\"", true),
  ("1 Mal Rune + 1 Perfect Diamond + 1 Northern Worldstone Shard + 1 Magic Gloves -> Mystical Gloves", &["\"glov,mag\"", "r23", "gpw", "xa5"], "\"useitem,pre=694\"", true),
  ("1 Mal Rune + 1 Perfect Diamond + 1 Northern Worldstone Shard + 1 Magic Armor -> Mystical Armor", &["\"tors,mag\"", "r23", "gpw", "xa5"], "\"useitem,pre=696\"", true),
  ("1 Mal Rune + 1 Perfect Diamond + 1 Northern Worldstone Shard + 1 Magic Weapon -> Mystical Weapon", &["\"weap,mag\"", "r23", "gpw", "xa5"], "\"useitem,pre=695\"", true),
  ("1 Mal Rune + 1 Perfect Diamond + 1 Northern Worldstone Shard + 1 Magic Shield -> Mystical Shield", &["\"shie,mag\"", "r23", "gpw", "xa5"], "\"useitem,pre=695\"", true),
  ("1 Mal Rune + 1 Perfect Diamond + 1 Northern Worldstone Shard + 1 Small Charm -> Mystical Small Charm", &["\"scha,mag\"", "r23", "gpw", "xa5"], "\"useitem,pre=692\"", true),
  ("1 Mal Rune + 1 Perfect Diamond + 1 Northern Worldstone Shard + 1 Large Charm -> Mystical Large Charm", &["\"mcha,mag\"", "r23", "gpw", "xa5"], "\"useitem,pre=693\"", true),
  ("1 Mal Rune + 1 Perfect Diamond + 1 Northern Worldstone Shard + 1 Grand Charm -> Mystical Grand Charm", &["\"lcha,mag\"", "r23", "gpw", "xa5"], "\"useitem,pre=694\"", true),
  ("1 Mal Rune + 1 Perfect Diamond + 1 Uber Ancient Summon Material Act5 + 1 Black Cleft -> Mystical Black Cleft", &["PreCrafted Black Cleft", "r23", "gpw", "xa3", "xa4", "xa5"], "Crafted Black Cleft", true),
  ("1 Uber Ancient Summon Material from Act 1 + Act2 + Act3 + Act 4 + Act 5 -> Portal to Colossal Summit", &["ua1", "ua2", "ua3", "ua4", "ua5"], "\"Red Portal,lvl=137,qty=1\"", true),
  ("[P2][BInf] Lsh Hp", &["\"any,nor\"", "\"lsh\""], "useitem", true),
  ("[P2][BInf] Lsh Hp [mag]", &["\"any,mag\"", "\"lsh\""], "useitem", true),
  ("[P2][BInf] Lsh Hp [rar]", &["\"any,rar\"", "\"lsh\""], "useitem", true),
  ("[P2][BInf] Lsh Hp [uni]", &["\"any,uni\"", "\"lsh\""], "useitem", true),
  ("[P2][BInf] Lsh Hp [set]", &["\"any,set\"", "\"lsh\""], "useitem", true),
  ("[P2][BInf] Lin Str", &["\"any,nor\"", "\"lin\""], "useitem", true),
  ("[P2][BInf] Lin Str [mag]", &["\"any,mag\"", "\"lin\""], "useitem", true),
  ("[P2][BInf] Lin Str [rar]", &["\"any,rar\"", "\"lin\""], "useitem", true),
  ("[P2][BInf] Lin Str [uni]", &["\"any,uni\"", "\"lin\""], "useitem", true),
  ("[P2][BInf] Lin Str [set]", &["\"any,set\"", "\"lin\""], "useitem", true),
  ("[P2][BInf] Lyd Dex", &["\"any,nor\"", "\"lyd\""], "useitem", true),
  ("[P2][BInf] Lyd Dex [mag]", &["\"any,mag\"", "\"lyd\""], "useitem", true),
  ("[P2][BInf] Lyd Dex [rar]", &["\"any,rar\"", "\"lyd\""], "useitem", true),
  ("[P2][BInf] Lyd Dex [uni]", &["\"any,uni\"", "\"lyd\""], "useitem", true),
  ("[P2][BInf] Lyd Dex [set]", &["\"any,set\"", "\"lyd\""], "useitem", true),
  ("[P2][BInf] Xfu MF", &["\"any,nor\"", "\"xfu\""], "useitem", true),
  ("[P2][BInf] Xfu MF [mag]", &["\"any,mag\"", "\"xfu\""], "useitem", true),
  ("[P2][BInf] Xfu MF [rar]", &["\"any,rar\"", "\"xfu\""], "useitem", true),
  ("[P2][BInf] Xfu MF [uni]", &["\"any,uni\"", "\"xfu\""], "useitem", true),
  ("[P2][BInf] Xfu MF [set]", &["\"any,set\"", "\"xfu\""], "useitem", true),
  ("[P2][BInf10] Ls1 Hp", &["\"any,nor\"", "\"ls1\""], "useitem", true),
  ("[P2][BInf10] Ls1 Hp [mag]", &["\"any,mag\"", "\"ls1\""], "useitem", true),
  ("[P2][BInf10] Ls1 Hp [rar]", &["\"any,rar\"", "\"ls1\""], "useitem", true),
  ("[P2][BInf10] Ls1 Hp [uni]", &["\"any,uni\"", "\"ls1\""], "useitem", true),
  ("[P2][BInf10] Ls1 Hp [set]", &["\"any,set\"", "\"ls1\""], "useitem", true),
  ("[P2][BInf10] Li1 Str", &["\"any,nor\"", "\"li1\""], "useitem", true),
  ("[P2][BInf10] Li1 Str [mag]", &["\"any,mag\"", "\"li1\""], "useitem", true),
  ("[P2][BInf10] Li1 Str [rar]", &["\"any,rar\"", "\"li1\""], "useitem", true),
  ("[P2][BInf10] Li1 Str [uni]", &["\"any,uni\"", "\"li1\""], "useitem", true),
  ("[P2][BInf10] Li1 Str [set]", &["\"any,set\"", "\"li1\""], "useitem", true),
  ("[P2][BInf10] Ld1 Dex", &["\"any,nor\"", "\"ld1\""], "useitem", true),
  ("[P2][BInf10] Ld1 Dex [mag]", &["\"any,mag\"", "\"ld1\""], "useitem", true),
  ("[P2][BInf10] Ld1 Dex [rar]", &["\"any,rar\"", "\"ld1\""], "useitem", true),
  ("[P2][BInf10] Ld1 Dex [uni]", &["\"any,uni\"", "\"ld1\""], "useitem", true),
  ("[P2][BInf10] Ld1 Dex [set]", &["\"any,set\"", "\"ld1\""], "useitem", true),
  ("[P2][BInf10] Xf1 MF", &["\"any,nor\"", "\"xf1\""], "useitem", true),
  ("[P2][BInf10] Xf1 MF [mag]", &["\"any,mag\"", "\"xf1\""], "useitem", true),
  ("[P2][BInf10] Xf1 MF [rar]", &["\"any,rar\"", "\"xf1\""], "useitem", true),
  ("[P2][BInf10] Xf1 MF [uni]", &["\"any,uni\"", "\"xf1\""], "useitem", true),
  ("[P2][BInf10] Xf1 MF [set]", &["\"any,set\"", "\"xf1\""], "useitem", true),
  ("[P2][BInf] Jlf Cast", &["\"any,nor\"", "\"jlf\""], "useitem", true),
  ("[P2][BInf] Jlf Cast [mag]", &["\"any,mag\"", "\"jlf\""], "useitem", true),
  ("[P2][BInf] Jlf Cast [rar]", &["\"any,rar\"", "\"jlf\""], "useitem", true),
  ("[P2][BInf] Jlf Cast [uni]", &["\"any,uni\"", "\"jlf\""], "useitem", true),
  ("[P2][BInf] Jlf Cast [set]", &["\"any,set\"", "\"jlf\""], "useitem", true),
  ("[P2][BInf10] Jl1 Cast", &["\"any,nor\"", "\"jl1\""], "useitem", true),
  ("[P2][BInf10] Jl1 Cast [mag]", &["\"any,mag\"", "\"jl1\""], "useitem", true),
  ("[P2][BInf10] Jl1 Cast [rar]", &["\"any,rar\"", "\"jl1\""], "useitem", true),
  ("[P2][BInf10] Jl1 Cast [uni]", &["\"any,uni\"", "\"jl1\""], "useitem", true),
  ("[P2][BInf10] Jl1 Cast [set]", &["\"any,set\"", "\"jl1\""], "useitem", true),
  ("[P2][BInf] Nls ResAll", &["\"any,nor\"", "\"nls\""], "useitem", true),
  ("[P2][BInf] Nls ResAll [mag]", &["\"any,mag\"", "\"nls\""], "useitem", true),
  ("[P2][BInf] Nls ResAll [rar]", &["\"any,rar\"", "\"nls\""], "useitem", true),
  ("[P2][BInf] Nls ResAll [uni]", &["\"any,uni\"", "\"nls\""], "useitem", true),
  ("[P2][BInf] Nls ResAll [set]", &["\"any,set\"", "\"nls\""], "useitem", true),
  ("[P2][BInf10] Nl1 ResAll", &["\"any,nor\"", "\"nl1\""], "useitem", true),
  ("[P2][BInf10] Nl1 ResAll [mag]", &["\"any,mag\"", "\"nl1\""], "useitem", true),
  ("[P2][BInf10] Nl1 ResAll [rar]", &["\"any,rar\"", "\"nl1\""], "useitem", true),
  ("[P2][BInf10] Nl1 ResAll [uni]", &["\"any,uni\"", "\"nl1\""], "useitem", true),
  ("[P2][BInf10] Nl1 ResAll [set]", &["\"any,set\"", "\"nl1\""], "useitem", true),
  ("[P2][BInf] Rly Swing", &["\"any,nor\"", "\"rly\""], "useitem", true),
  ("[P2][BInf] Rly Swing [mag]", &["\"any,mag\"", "\"rly\""], "useitem", true),
  ("[P2][BInf] Rly Swing [rar]", &["\"any,rar\"", "\"rly\""], "useitem", true),
  ("[P2][BInf] Rly Swing [uni]", &["\"any,uni\"", "\"rly\""], "useitem", true),
  ("[P2][BInf] Rly Swing [set]", &["\"any,set\"", "\"rly\""], "useitem", true),
  ("[P2][BInf10] Rl1 Swing", &["\"any,nor\"", "\"rl1\""], "useitem", true),
  ("[P2][BInf10] Rl1 Swing [mag]", &["\"any,mag\"", "\"rl1\""], "useitem", true),
  ("[P2][BInf10] Rl1 Swing [rar]", &["\"any,rar\"", "\"rl1\""], "useitem", true),
  ("[P2][BInf10] Rl1 Swing [uni]", &["\"any,uni\"", "\"rl1\""], "useitem", true),
  ("[P2][BInf10] Rl1 Swing [set]", &["\"any,set\"", "\"rl1\""], "useitem", true),
  ("COI_RECIPE_34edqf", &["\"any,mag\"", "cly"], "useitem", true),
  ("COI_RECIPE_swbyyq", &["\"any,rar\"", "cly"], "useitem", true),
  ("[P2][GateInit] Title Init - Apprentice", &["t01", "cly"], "useitem", true),
  ("[P2][GateInit] Title Init - Foundation", &["t02", "cly"], "useitem", true),
  ("[P2][GateInit] Title Init - Golden Core", &["t03", "cly"], "useitem", true),
  ("[P2][TitleInf] T01 Lin", &["t01", "\"lin\""], "useitem", true),
  ("[P2][TitleInf] T01 Lsh", &["t01", "\"lsh\""], "useitem", true),
  ("[P2][TitleInf] T01 Lyd", &["t01", "\"lyd\""], "useitem", true),
  ("[P2][TitleInf] T01 Jlf", &["t01", "\"jlf\""], "useitem", true),
  ("[P2][TitleInf] T01 Xfu", &["t01", "\"xfu\""], "useitem", true),
  ("[P2][TitleInf] T01 Rly", &["t01", "\"rly\""], "useitem", true),
  ("[P2][TitleInf] T01 Nls", &["t01", "\"nls\""], "useitem", true),
  ("COI_RECIPE_h57b3b", &["xuj", "\"armo,uni\""], "xuj,mod", true),
  ("COI_RECIPE_h7x00w", &["xuj", "\"weap,uni\""], "xuj,mod", true),
  ("COI_RECIPE_e0kou2", &["xuj", "\"ring,uni\""], "xuj,mod", true),
  ("COI_RECIPE_e7ccrd", &["xuj", "\"amu,uni\""], "xuj,mod", true),
  ("COI_RECIPE_hmaqwk", &["xuj", "\"armo,set\""], "xuj,mod", true),
  ("COI_RECIPE_j1ozyd", &["xuj", "\"weap,set\""], "xuj,mod", true),
  ("COI_RECIPE_kqxd5t", &["xuj", "\"ring,set\""], "xuj,mod", true),
  ("COI_RECIPE_pvcrgw", &["xuj", "\"amu,set\""], "xuj,mod", true),
  ("COI_RECIPE_u5mkza", &["xuj", "lkg"], "xuj,mod", true),
  ("COI_RECIPE_mwq48f", &["xuj", "lkm"], "xuj,mod", true),
  ("COI_RECIPE_z2ox7h", &["xuj", "lks"], "xuj,mod", true),
  ("COI_RECIPE_66cf28", &["xuj", "lkh"], "xuj,mod", true),
  ("COI_RECIPE_qcqitz", &["xuj", "lkt"], "xuj,mod", true),
  ("COI_RECIPE_3t3722", &["xuj", "lka"], "xuj,mod", true),
  ("COI_RECIPE_9t6yds", &["xuj", "lkd"], "xuj,mod", true),
  ("COI_RECIPE_dy86qh", &["\"weap\"", "lkd", "r11"], "useitem", true),
  ("COI_RECIPE_80ni5c", &["\"armo\"", "lkd", "r11"], "useitem", true),
  ("COI_RECIPE_hfvqfl", &["xmd", "\"lin,qty=1\""], "useitem", true),
  ("COI_RECIPE_c9h6fj", &["xmd", "\"lin,qty=6\""], "useitem", true),
  ("COI_RECIPE_ekjwq5", &["xmd", "\"xfu,qty=1\""], "useitem", true),
  ("COI_RECIPE_f4t04z", &["xmd", "\"xfu,qty=6\""], "useitem", true),
  ("COI_RECIPE_nlz2uc", &["xmd", "\"lsh,qty=1\""], "useitem", true),
  ("COI_RECIPE_63du0s", &["xmd", "\"lsh,qty=6\""], "useitem", true),
  ("COI_RECIPE_ccr4xw", &["xmd", "\"lyd,qty=1\""], "useitem", true),
  ("COI_RECIPE_hclrx8", &["xmd", "\"lyd,qty=6\""], "useitem", true),
  ("COI_RECIPE_w1ykt4", &["xmd", "\"jlf,qty=1\""], "useitem", true),
  ("COI_RECIPE_99skaw", &["xmd", "\"jlf,qty=6\""], "useitem", true),
  ("COI_RECIPE_vxc1tp", &["xmd", "\"rly,qty=1\""], "useitem", true),
  ("COI_RECIPE_9ef3ab", &["xmd", "\"rly,qty=6\""], "useitem", true),
  ("COI_RECIPE_7blt5i", &["xmd", "\"nls,qty=1\""], "useitem", true),
  ("COI_RECIPE_mdr3pm", &["xmd", "\"nls,qty=6\""], "useitem", true),
  ("COI_RECIPE_traaaj", &["xmd", "\"lck,qty=1\""], "useitem", true),
  ("COI_RECIPE_1xdff", &["xmd", "\"lck,qty=6\""], "useitem", true),
  ("COI_RECIPE_9vys5s", &["xmd", "\"cly,qty=1\""], "useitem", true),
  ("COI_RECIPE_vfscy8", &["xmd", "\"cly,qty=6\""], "useitem", true),
  ("COI_RECIPE_veu9be", &["xmd", "\"qlf,qty=1\""], "useitem", true),
  ("COI_RECIPE_9wwvsm", &["xmd", "\"qlf,qty=6\""], "useitem", true),
  ("COI_RECIPE_haj2ns", &["xmd", "\"cll,qty=1\""], "useitem", true),
  ("COI_RECIPE_cetu7c", &["xmd", "\"cll,qty=6\""], "useitem", true),
  ("COI_RECIPE_lnbjap", &["xmd", "\"lgy,qty=1\""], "useitem", true),
  ("COI_RECIPE_jofltb", &["xmd", "\"lgy,qty=6\""], "useitem", true),
  ("COI_RECIPE_55hf08", &["xmd", "\"lgs,qty=1\""], "useitem", true),
  ("COI_RECIPE_yuubvc", &["xmd", "\"lgs,qty=6\""], "useitem", true),
  ("COI_RECIPE_4hjrp9", &["xmd", "r01"], "useitem", true),
  ("COI_RECIPE_lfzy28", &["xmd", "r02"], "useitem", true),
  ("COI_RECIPE_g6ibuq", &["xmd", "r03"], "useitem", true),
  ("COI_RECIPE_9fheou", &["xmd", "r04"], "useitem", true),
  ("COI_RECIPE_mjz5ul", &["xmd", "r05"], "useitem", true),
  ("COI_RECIPE_mq9zoe", &["xmd", "r06"], "useitem", true),
  ("COI_RECIPE_3vfnr6", &["xmd", "r07"], "useitem", true),
  ("COI_RECIPE_ng5y4j", &["xmd", "r08"], "useitem", true),
  ("COI_RECIPE_z0jaff", &["xmd", "r09"], "useitem", true),
  ("COI_RECIPE_yna618", &["xmd", "r10"], "useitem", true),
  ("COI_RECIPE_qbxfyx", &["xmd", "r11"], "useitem", true),
  ("COI_RECIPE_xr3mo8", &["xmd", "r12"], "useitem", true),
  ("COI_RECIPE_x7doe4", &["xmd", "r13"], "useitem", true),
  ("COI_RECIPE_p3g61v", &["\"lin,qty=10\""], "li1", true),
  ("COI_RECIPE_vyym1k", &["\"xfu,qty=10\""], "xf1", true),
  ("COI_RECIPE_bsabl", &["\"lsh,qty=10\""], "ls1", true),
  ("COI_RECIPE_jpfz5o", &["\"lyd,qty=10\""], "ld1", true),
  ("COI_RECIPE_q5lm4p", &["\"jlf,qty=10\""], "jl1", true),
  ("COI_RECIPE_vbcof5", &["\"rly,qty=10\""], "rl1", true),
  ("COI_RECIPE_o3gvgd", &["\"nls,qty=10\""], "nl1", true),
  ("[P2][Cube] Rare Jewel Reforge", &["\"jew,rar,qty=3\""], "jew,rar", true),
  ("[P2][Cube] Jewel Upgrade to Rare", &["\"jew,qty=7\""], "jew,rar", true),
  ("[P2][Cube] Grand Charm Upgrade to Rare", &["\"cm3,mag,qty=3\""], "cm3,rar", true),
  ("[P2][Cube] Large Charm Upgrade to Rare", &["\"cm2,mag,qty=3\""], "cm2,rar", true),
  ("[P2][Cube] Small Charm Upgrade to Rare", &["\"cm1,mag,qty=3\""], "cm1,rar", true),
  ("[P2] Open Cow Portal with Two Tomes", &["\"tbk,qty=2\""], "Cow Portal", true),
  ("[P2] Startup Fund Synthesis", &["isc", "tsc"], "stf", true),
  ("[P2] White Item Socket to 1", &["\"any,nor\"", "r01"], "useitem,sock=1", true),
  ("[P2] White Item Socket to 2", &["\"any,nor\"", "r02"], "useitem,sock=2", true),
  ("[P2] White Item Socket to 3", &["\"any,nor\"", "r03"], "useitem,sock=3", true),
  ("[P2] Polearm Socket to 4", &["\"pole,nor\"", "r04"], "useitem,sock=4", true),
  ("[P2] Polearm Superior Socket to 4", &["\"pole,hiq\"", "r04"], "useitem,sock=4", true),
  ("[P2] White Item Socket to 4", &["\"any,nor\"", "r04"], "useitem,sock=4", true),
  ("[P2] White Item Socket to 5", &["\"any,nor\"", "r05"], "useitem,sock=5", true),
  ("[P2] White Item Socket to 6", &["\"any,nor\"", "r06"], "useitem,sock=6", true),
  ("[P2] Superior White Item Socket to 1", &["\"any,hiq\"", "r01"], "useitem,sock=1", true),
  ("[P2] Superior White Item Socket to 2", &["\"any,hiq\"", "r02"], "useitem,sock=2", true),
  ("[P2] Superior White Item Socket to 3", &["\"any,hiq\"", "r03"], "useitem,sock=3", true),
  ("[P2] Superior White Item Socket to 4", &["\"any,hiq\"", "r04"], "useitem,sock=4", true),
  ("[P2] Superior White Item Socket to 5", &["\"any,hiq\"", "r05"], "useitem,sock=5", true),
  ("[P2] Superior White Item Socket to 6", &["\"any,hiq\"", "r06"], "useitem,sock=6", true),
  ("[P2] Unique Item Socket to 1", &["\"any,uni\"", "r01"], "useitem,sock=1", true),
  ("[P2] Unique Item Socket to 2", &["\"any,uni\"", "r02"], "useitem,sock=2", true),
  ("[P2] Unique Item Socket to 3", &["\"any,uni\"", "r03"], "useitem,sock=3", true),
  ("[P2] Socketed Item Restore to No Socket", &["\"any,sock\"", "r01", "tsc"], "useitem,uns", true),
  ("[P2][TitleUpgrade] Apprentice to Foundation", &["t01", "\"lin,qty=5\"", "\"lsh,qty=5\"", "\"lyd,qty=5\"", "lck"], "t02", true),
  ("[P2][TitleUpgrade] Foundation to Golden Core", &["t02", "\"li1,qty=5\"", "\"ls1,qty=5\"", "\"ld1,qty=5\"", "\"lck,qty=2\""], "t03", true),
  ("[P4] Attack Direction Embryo", &["lgp", "li1", "\"ls1,qty=2\"", "\"ld1,qty=10\"", "gpr"], "atc", true),
  ("[P4] Defense Direction Embryo", &["lgp", "li1", "\"ls1,qty=2\"", "\"ld1,qty=10\"", "glw"], "def", true),
  ("[P4] Magic Direction Embryo", &["lgp", "li1", "\"ls1,qty=2\"", "\"ld1,qty=10\"", "gpv"], "mag", true),
  ("[P4] Attack L1 Spirit Treasure Craft", &["atc", "\"ld1,qty=10\"", "\"ls1,qty=3\"", "li1"], "COI_SPIRIT_A01", true),
  ("[P4] Attack L5 Spirit Treasure Craft", &["atc", "\"ld1,qty=12\"", "\"nl1,qty=2\"", "xf1"], "COI_SPIRIT_A05", true),
  ("[P4] Attack L10 Spirit Treasure Craft", &["atc", "\"ld1,qty=16\"", "\"nl1,qty=4\"", "\"xf1,qty=2\""], "COI_SPIRIT_A10", true),
  ("[P4] Defense L1 Spirit Treasure Craft", &["def", "\"ld1,qty=10\"", "\"ls1,qty=3\"", "li1"], "COI_SPIRIT_D01", true),
  ("[P4] Defense L5 Spirit Treasure Craft", &["def", "\"ld1,qty=12\"", "\"nl1,qty=2\"", "xf1"], "COI_SPIRIT_D05", true),
  ("[P4] Defense L10 Spirit Treasure Craft", &["def", "\"ld1,qty=16\"", "\"nl1,qty=4\"", "\"xf1,qty=2\""], "COI_SPIRIT_D10", true),
  ("[P4] Magic L1 Spirit Treasure Craft", &["mag", "\"ld1,qty=10\"", "\"ls1,qty=3\"", "li1"], "COI_SPIRIT_M01", true),
  ("[P4] Magic L5 Spirit Treasure Craft", &["mag", "\"ld1,qty=12\"", "\"nl1,qty=2\"", "xf1"], "COI_SPIRIT_M05", true),
  ("[P4] Magic L10 Spirit Treasure Craft", &["mag", "\"ld1,qty=16\"", "\"nl1,qty=4\"", "\"xf1,qty=2\""], "COI_SPIRIT_M10", true),
  ("[P4] Attack L1 to L5 Upgrade", &["a01", "li1", "\"ls1,qty=3\"", "\"ld1,qty=8\""], "COI_SPIRIT_A05", true),
  ("[P4] Attack L5 to L10 Upgrade", &["a05", "li1", "\"ls1,qty=5\"", "\"ld1,qty=12\"", "nl1"], "COI_SPIRIT_A10", true),
  ("[P4] Attack L10 to L15 Upgrade", &["a10", "li1", "\"ls1,qty=8\"", "\"ld1,qty=15\"", "nl1"], "COI_SPIRIT_A15", true),
  ("[P4] Attack L15 to L20 Upgrade", &["a15", "li1", "\"ls1,qty=10\"", "\"ld1,qty=18\"", "\"nl1,qty=2\""], "COI_SPIRIT_A20", true),
  ("[P4] Attack L20 to L25 Upgrade", &["a20", "\"li1,qty=2\"", "\"ls1,qty=14\"", "\"ld1,qty=20\"", "\"nl1,qty=4\"", "xf1"], "COI_SPIRIT_A25", true),
  ("[P4] Attack L25 to L30 Upgrade", &["a25", "\"li1,qty=2\"", "\"ls1,qty=18\"", "\"ld1,qty=20\"", "\"nl1,qty=5\"", "\"xf1,qty=3\"", "lck"], "COI_SPIRIT_A30", true),
  ("[P4] Defense L1 to L5 Upgrade", &["d01", "li1", "\"ls1,qty=3\"", "\"ld1,qty=8\""], "COI_SPIRIT_D05", true),
  ("[P4] Defense L5 to L10 Upgrade", &["d05", "li1", "\"ls1,qty=5\"", "\"ld1,qty=12\"", "nl1"], "COI_SPIRIT_D10", true),
  ("[P4] Defense L10 to L15 Upgrade", &["d10", "li1", "\"ls1,qty=8\"", "\"ld1,qty=15\"", "nl1"], "COI_SPIRIT_D15", true),
  ("[P4] Defense L15 to L20 Upgrade", &["d15", "li1", "\"ls1,qty=10\"", "\"ld1,qty=18\"", "\"nl1,qty=2\""], "COI_SPIRIT_D20", true),
  ("[P4] Defense L20 to L25 Upgrade", &["d20", "\"li1,qty=2\"", "\"ls1,qty=14\"", "\"ld1,qty=20\"", "\"nl1,qty=4\"", "xf1"], "COI_SPIRIT_D25", true),
  ("[P4] Defense L25 to L30 Upgrade", &["d25", "\"li1,qty=2\"", "\"ls1,qty=18\"", "\"ld1,qty=20\"", "\"nl1,qty=5\"", "\"xf1,qty=3\"", "lck"], "COI_SPIRIT_D30", true),
  ("[P4] Magic L1 to L5 Upgrade", &["m01", "li1", "\"ls1,qty=3\"", "\"ld1,qty=8\""], "COI_SPIRIT_M05", true),
  ("[P4] Magic L5 to L10 Upgrade", &["m05", "li1", "\"ls1,qty=5\"", "\"ld1,qty=12\"", "nl1"], "COI_SPIRIT_M10", true),
  ("[P4] Magic L10 to L15 Upgrade", &["m10", "li1", "\"ls1,qty=8\"", "\"ld1,qty=15\"", "nl1"], "COI_SPIRIT_M15", true),
  ("[P4] Magic L15 to L20 Upgrade", &["m15", "li1", "\"ls1,qty=10\"", "\"ld1,qty=18\"", "\"nl1,qty=2\""], "COI_SPIRIT_M20", true),
  ("[P4] Magic L20 to L25 Upgrade", &["m20", "\"li1,qty=2\"", "\"ls1,qty=14\"", "\"ld1,qty=20\"", "\"nl1,qty=4\"", "xf1"], "COI_SPIRIT_M25", true),
  ("[P4] Magic L25 to L30 Upgrade", &["m25", "\"li1,qty=2\"", "\"ls1,qty=18\"", "\"ld1,qty=20\"", "\"nl1,qty=5\"", "\"xf1,qty=3\"", "lck"], "COI_SPIRIT_M30", true),
  ("[P4] Attack L15 Degrade to L10", &["a15", "lgc", "rl1"], "COI_SPIRIT_A10", true),
  ("[P4] Attack L20 Degrade to L15", &["a20", "lmc", "rl1"], "COI_SPIRIT_A15", true),
  ("[P4] Attack L25 Degrade to L20", &["a25", "lsc", "rl1"], "COI_SPIRIT_A20", true),
  ("[P4] Attack L30 Degrade to L25", &["a30", "lhc", "rl1"], "COI_SPIRIT_A25", true),
  ("[P4] Defense L15 Degrade to L10", &["d15", "lgc", "rl1"], "COI_SPIRIT_D10", true),
  ("[P4] Defense L20 Degrade to L15", &["d20", "lmc", "rl1"], "COI_SPIRIT_D15", true),
  ("[P4] Defense L25 Degrade to L20", &["d25", "lsc", "rl1"], "COI_SPIRIT_D20", true),
  ("[P4] Defense L30 Degrade to L25", &["d30", "lhc", "rl1"], "COI_SPIRIT_D25", true),
  ("[P4] Magic L15 Degrade to L10", &["m15", "lgc", "rl1"], "COI_SPIRIT_M10", true),
  ("[P4] Magic L20 Degrade to L15", &["m20", "lmc", "rl1"], "COI_SPIRIT_M15", true),
  ("[P4] Magic L25 Degrade to L20", &["m25", "lsc", "rl1"], "COI_SPIRIT_M20", true),
  ("[P4] Magic L30 Degrade to L25", &["m30", "lhc", "rl1"], "COI_SPIRIT_M25", true),
  ("[P4] Awakening - Attack T5", &["a30", "\"xf1,qty=4\"", "lgc", "\"ld1,qty=20\"", "\"nl1,qty=6\"", "\"lck,qty=2\""], "useitem,uni", true),
  ("[P4] Awakening - Defense T5", &["d30", "\"xf1,qty=4\"", "lmc", "\"ld1,qty=20\"", "\"nl1,qty=6\"", "\"lck,qty=2\""], "useitem,uni", true),
  ("[P4] Awakening - Magic T5", &["m30", "\"xf1,qty=4\"", "lsc", "\"ld1,qty=20\"", "\"nl1,qty=6\"", "\"lck,qty=2\""], "useitem,uni", true),
  ("[P4] Awakening - Attack Armor Break", &["a30", "\"xf1,qty=4\"", "lgc", "\"ld1,qty=24\"", "\"nl1,qty=7\"", "\"lck,qty=2\""], "useitem,uni", true),
  ("[P4] Awakening - Magic Arcane Break", &["m30", "\"xf1,qty=4\"", "lac", "\"ld1,qty=24\"", "\"nl1,qty=7\"", "\"lck,qty=2\""], "useitem,uni", true),
  ("[P4] Awakening - Magic Frost Break", &["m30", "\"xf1,qty=4\"", "lsc", "\"ld1,qty=24\"", "\"nl1,qty=7\"", "\"lck,qty=2\""], "useitem,uni", true),
  ("[P4] Awakening - Magic Flame Break", &["m30", "\"xf1,qty=4\"", "lhc", "\"ld1,qty=24\"", "\"nl1,qty=7\"", "\"lck,qty=2\""], "useitem,uni", true),
  ("[P4] Awakening - Magic Storm Break", &["m30", "\"xf1,qty=4\"", "lac", "\"ld1,qty=24\"", "\"nl1,qty=7\"", "\"lck,qty=2\""], "useitem,uni", true),
  ("[P4] Awakening - Magic Venom Break", &["m30", "\"xf1,qty=4\"", "ldc", "\"ld1,qty=24\"", "\"nl1,qty=7\"", "\"lck,qty=2\""], "useitem,uni", true),
  ("[P4] Attack L10 Protected to L15", &["a10", "li1", "\"ls1,qty=10\"", "\"ld1,qty=15\"", "\"nl1,qty=2\"", "lck"], "COI_SPIRIT_A15", true),
  ("[P4] Attack L20 Protected to L25", &["a20", "\"li1,qty=2\"", "\"ls1,qty=14\"", "\"ld1,qty=18\"", "\"nl1,qty=4\"", "\"lck,qty=2\""], "COI_SPIRIT_A25", true),
  ("[P4] Defense L10 Protected to L15", &["d10", "li1", "\"ls1,qty=10\"", "\"ld1,qty=15\"", "\"nl1,qty=2\"", "lck"], "COI_SPIRIT_D15", true),
  ("[P4] Defense L20 Protected to L25", &["d20", "\"li1,qty=2\"", "\"ls1,qty=14\"", "\"ld1,qty=18\"", "\"nl1,qty=4\"", "\"lck,qty=2\""], "COI_SPIRIT_D25", true),
  ("[P4] Magic L10 Protected to L15", &["m10", "li1", "\"ls1,qty=10\"", "\"ld1,qty=15\"", "\"nl1,qty=2\"", "lck"], "COI_SPIRIT_M15", true),
  ("[P4] Magic L20 Protected to L25", &["m20", "\"li1,qty=2\"", "\"ls1,qty=14\"", "\"ld1,qty=18\"", "\"nl1,qty=4\"", "\"lck,qty=2\""], "COI_SPIRIT_M25", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Attack Path)", &["\"any,nor\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "a05"], "useitem", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Attack Path) [mag]", &["\"any,mag\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "a05"], "useitem", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Attack Path) [rar]", &["\"any,rar\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "a05"], "useitem", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Attack Path) [uni]", &["\"any,uni\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "a05"], "useitem", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Attack Path) [set]", &["\"any,set\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "a05"], "useitem", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Defense Path)", &["\"any,nor\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "d05"], "COI_SPIRIT_D05", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Defense Path) [mag]", &["\"any,mag\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "d05"], "COI_SPIRIT_D05", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Defense Path) [rar]", &["\"any,rar\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "d05"], "COI_SPIRIT_D05", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Defense Path) [uni]", &["\"any,uni\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "d05"], "COI_SPIRIT_D05", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Defense Path) [set]", &["\"any,set\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "d05"], "COI_SPIRIT_D05", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Magic Path)", &["\"any,nor\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "m05"], "COI_SPIRIT_M05", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Magic Path) [mag]", &["\"any,mag\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "m05"], "COI_SPIRIT_M05", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Magic Path) [rar]", &["\"any,rar\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "m05"], "COI_SPIRIT_M05", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Magic Path) [uni]", &["\"any,uni\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "m05"], "COI_SPIRIT_M05", true),
  ("[P4][9.2] Spirit Weapon Upgrade (Magic Path) [set]", &["\"any,set\"", "li1", "\"ls1,qty=4\"", "\"ld1,qty=10\"", "xf1", "m05"], "COI_SPIRIT_M05", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Attack Path)", &["\"any,nor\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "a15"], "COI_SPIRIT_A15", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Attack Path) [mag]", &["\"any,mag\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "a15"], "COI_SPIRIT_A15", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Attack Path) [rar]", &["\"any,rar\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "a15"], "COI_SPIRIT_A15", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Attack Path) [uni]", &["\"any,uni\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "a15"], "COI_SPIRIT_A15", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Attack Path) [set]", &["\"any,set\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "a15"], "COI_SPIRIT_A15", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Defense Path)", &["\"any,nor\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "d15"], "COI_SPIRIT_D15", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Defense Path) [mag]", &["\"any,mag\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "d15"], "COI_SPIRIT_D15", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Defense Path) [rar]", &["\"any,rar\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "d15"], "COI_SPIRIT_D15", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Defense Path) [uni]", &["\"any,uni\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "d15"], "COI_SPIRIT_D15", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Defense Path) [set]", &["\"any,set\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "d15"], "COI_SPIRIT_D15", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Magic Path)", &["\"any,nor\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "m15"], "COI_SPIRIT_M15", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Magic Path) [mag]", &["\"any,mag\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "m15"], "COI_SPIRIT_M15", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Magic Path) [rar]", &["\"any,rar\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "m15"], "COI_SPIRIT_M15", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Magic Path) [uni]", &["\"any,uni\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "m15"], "COI_SPIRIT_M15", true),
  ("[P4][9.2] Immortal Treasure Upgrade (Magic Path) [set]", &["\"any,set\"", "li1", "\"ls1,qty=6\"", "\"ld1,qty=14\"", "\"xf1,qty=2\"", "nl1", "m15"], "COI_SPIRIT_M15", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Attack Path)", &["\"any,nor\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_A25", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Attack Path) [mag]", &["\"any,mag\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_A25", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Attack Path) [rar]", &["\"any,rar\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_A25", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Attack Path) [uni]", &["\"any,uni\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_A25", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Attack Path) [set]", &["\"any,set\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_A25", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Defense Path)", &["\"any,nor\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_D25", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Defense Path) [mag]", &["\"any,mag\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_D25", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Defense Path) [rar]", &["\"any,rar\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_D25", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Defense Path) [uni]", &["\"any,uni\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_D25", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Defense Path) [set]", &["\"any,set\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_D25", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Magic Path)", &["\"any,nor\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_M25", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Magic Path) [mag]", &["\"any,mag\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_M25", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Magic Path) [rar]", &["\"any,rar\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_M25", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Magic Path) [uni]", &["\"any,uni\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_M25", true),
  ("[P4][9.2] Primordial Treasure Upgrade (Magic Path) [set]", &["\"any,set\"", "li1", "\"ls1,qty=8\"", "\"ld1,qty=18\"", "\"xf1,qty=3\"", "\"nl1,qty=2\"", "lgp"], "COI_SPIRIT_M25", true),
  ("[P4][Test] Craft Title Apprentice", &["lgy", "lgs", "lgz", "r01"], "t01,uni", true),
  ("[P4][Test] Craft Title Foundation", &["lgy", "lgs", "lgz", "r02"], "t02,uni", true),
  ("[P4][Test] Craft Title Golden Core", &["lgy", "lgs", "lgz", "r03"], "t03,uni", true),
  ("[P10][Core] Seven Cores Merge True Marrow", &["lgc", "lmc", "lsc", "lhc", "ltc", "lac", "ldc"], "lgx,uni", true),
  ("[P10][L1] Gold Root Determination", &["lgx", "cll", "lgy", "lsh", "lgc"], "useitem", true),
  ("[P10][L1] Wood Root Determination", &["lgx", "cll", "lgy", "lsh", "lmc"], "useitem", true),
  ("[P10][L1] Water Root Determination", &["lgx", "cll", "lgy", "lsh", "lsc"], "useitem", true),
  ("[P10][L1] Fire Root Determination", &["lgx", "cll", "lgy", "lsh", "lhc"], "useitem", true),
  ("[P10][L1] Earth Root Determination", &["lgx", "cll", "lgy", "lsh", "ltc"], "useitem", true),
  ("[P10][L1] Light Root Determination", &["lgx", "cll", "lgy", "lsh", "lac"], "useitem", true),
  ("[P10][L1] Dark Root Determination", &["lgx", "cll", "lgy", "lsh", "ldc"], "useitem", true),
  ("[P10][L2] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L2] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L2] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L2] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L2] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L2] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L2] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P10][L3] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L3] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L3] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L3] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L3] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L3] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L3] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P10][L4] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L4] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L4] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L4] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L4] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L4] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L4] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P10][L5] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L5] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L5] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L5] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L5] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L5] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L5] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P10][L6] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L6] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L6] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L6] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L6] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L6] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L6] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P10][L7] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L7] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L7] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L7] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L7] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L7] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L7] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P10][L8] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L8] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L8] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L8] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L8] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L8] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L8] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P10][L9] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L9] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L9] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L9] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L9] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L9] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L9] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P10][L10] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L10] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L10] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L10] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L10] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L10] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L10] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P10][L11] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L11] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L11] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L11] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L11] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L11] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L11] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P10][L12] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L12] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L12] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L12] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L12] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L12] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L12] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P10][L13] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L13] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L13] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L13] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L13] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L13] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L13] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P10][L14] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L14] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L14] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L14] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L14] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L14] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L14] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P10][L15] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L15] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L15] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L15] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L15] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L15] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L15] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P10][L16] Gold Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lgc"], "useitem", true),
  ("[P10][L16] Wood Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lmc"], "useitem", true),
  ("[P10][L16] Water Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lsc"], "useitem", true),
  ("[P10][L16] Fire Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lhc"], "useitem", true),
  ("[P10][L16] Earth Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ltc"], "useitem", true),
  ("[P10][L16] Light Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "lac"], "useitem", true),
  ("[P10][L16] Dark Root Upgrade", &["lgx", "cll", "lgy", "\"lgs,qty=2\"", "ldc"], "useitem", true),
  ("[P11][Gate] Reincarnation Gate I", &["rh1", "qlf", "\"lck,qty=1\"", "\"ld1,qty=12\""], "rm1", true),
  ("[P11][Gate] Reincarnation Gate II", &["rh2", "qlf", "\"lck,qty=1\"", "\"ld1,qty=14\""], "Red Portal,lvl=178,qty=1", true),
  ("[P11][Gate] Reincarnation Gate III", &["rh3", "\"qlf,qty=2\"", "\"lck,qty=2\"", "\"ld1,qty=16\""], "Red Portal,lvl=179,qty=1", true),
  ("[P11][Gate] Reincarnation Gate IV", &["rh4", "\"qlf,qty=2\"", "\"lck,qty=2\"", "\"ld1,qty=18\""], "Red Portal,lvl=180,qty=1", true),
  ("[P11][Gate] Reincarnation Gate V", &["rh5", "\"qlf,qty=3\"", "\"lck,qty=2\"", "\"ld1,qty=20\""], "Red Portal,lvl=181,qty=1", true),
  ("[P11][Gate] Reincarnation Gate VI", &["rh6", "\"qlf,qty=3\"", "\"lck,qty=3\"", "\"ld1,qty=24\""], "Red Portal,lvl=182,qty=1", true),
  ("[P11][Advance] Reincarnation Jade I to II", &["rh1", "rp1", "\"nl1,qty=1\"", "\"ld1,qty=8\""], "rh2", true),
  ("[P11][Advance] Reincarnation Jade II to III", &["rh2", "rp2", "\"nl1,qty=1\"", "\"ld1,qty=10\""], "rh3", true),
  ("[P11][Advance] Reincarnation Jade III to IV", &["rh3", "rp3", "\"nl1,qty=2\"", "\"ld1,qty=12\""], "rh4", true),
  ("[P11][Advance] Reincarnation Jade IV to V", &["rh4", "rp4", "\"nl1,qty=2\"", "\"ld1,qty=14\""], "rh5", true),
  ("[P11][Advance] Reincarnation Jade V to VI", &["rh5", "rp5", "\"nl1,qty=3\"", "\"ld1,qty=16\""], "rh6", true),
  ("[P11][Advance] Reincarnation Jade VI Recast", &["rh6", "rp6", "\"nl1,qty=3\"", "\"lck,qty=2\"", "\"ld1,qty=20\""], "rh6", true),
  ("[P12][PoC] Spirit Root Materials Craft Test Charm I", &["tsc", "r01"], "pc1,uni", true),
  ("[P12][PoC] Spirit Root Materials Craft Test Charm II", &["tsc", "r02"], "pc2,uni", true),
  ("[P12][PoC] Spirit Root Materials Craft Test Charm III", &["tsc", "r03"], "pc3,uni", true),
  ("[P12][PoC] Spirit Root Materials Craft Test Charm IV", &["tsc", "r04"], "pc4,uni", true),
  ("[P12][PoC] Spirit Root Materials Craft Test Charm V", &["tsc", "r05"], "pc5,uni", true),
  ("COI_RECIPE_wvbk48", &["\"any,mag\"", "\"lvs\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_xbld2l", &["\"any,rar\"", "\"lvs\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_juyz0z", &["\"any,uni\"", "\"lvs\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_t4in0x", &["\"any,set\"", "\"lvs\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_tc1nns", &["\"any,mag\"", "\"lmp\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_vb63rh", &["\"any,rar\"", "\"lmp\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_hujppv", &["\"any,uni\"", "\"lmp\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_v4xwc1", &["\"any,set\"", "\"lmp\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_s7f9fk", &["\"any,mag\"", "\"lre\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_969s5", &["\"any,rar\"", "\"lre\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_d7g49h", &["\"any,uni\"", "\"lre\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_8u6bnr", &["\"any,set\"", "\"lre\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_f5o38v", &["\"any,mag\"", "\"lri\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_bjsptg", &["\"any,rar\"", "\"lri\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_1wto86", &["\"any,uni\"", "\"lri\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_k4srp2", &["\"any,set\"", "\"lri\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_ofqu14", &["\"any,mag\"", "\"lcr\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_i6im0j", &["\"any,rar\"", "\"lcr\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_vn5025", &["\"any,uni\"", "\"lcr\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_9lik4x", &["\"any,set\"", "\"lcr\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_addfco", &["\"any,mag\"", "\"lpn\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_7fugmr", &["\"any,rar\"", "\"lpn\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_kwguod", &["\"any,uni\"", "\"lpn\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_155l8v", &["\"any,set\"", "\"lpn\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_glegnm", &["\"any,mag\"", "\"lem\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_tojbhl", &["\"any,rar\"", "\"lem\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_rvycfx", &["\"any,uni\"", "\"lem\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_l3j9lz", &["\"any,set\"", "\"lem\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_6jvfs6", &["\"any,mag\"", "\"ls2\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_4l63px", &["\"any,rar\"", "\"ls2\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_i1shrj", &["\"any,uni\"", "\"ls2\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_3zty5p", &["\"any,set\"", "\"ls2\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_108nhh", &["\"any,mag\"", "\"ldf\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_h2qqxs", &["\"any,rar\"", "\"ldf\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_ujd4ze", &["\"any,uni\"", "\"ldf\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_8hqp26", &["\"any,set\"", "\"ldf\"", "\"lin,qty=2\"", "\"lsh,qty=2\"", "\"lyd,qty=2\""], "useitem", true),
  ("COI_RECIPE_77y85f", &["\"lvs\"", "\"lvs\"", "\"lvs\""], "\"lwf\"", true),
  ("COI_RECIPE_spviao", &["\"lmp\"", "\"lmp\"", "\"lmp\""], "\"lag\"", true),
  ("COI_RECIPE_p98b8x", &["\"lre\"", "\"lre\"", "\"lre\""], "\"lfs\"", true),
  ("COI_RECIPE_ksyf08", &["\"lri\"", "\"lri\"", "\"lri\""], "\"lvp\"", true),
  ("COI_RECIPE_e5pvdp", &["\"lcr\"", "\"lcr\"", "\"lcr\""], "\"lhr\"", true),
  ("COI_RECIPE_4v39td", &["\"lpn\"", "\"lpn\"", "\"lpn\""], "\"lsk\"", true),
  ("COI_RECIPE_mrlf9h", &["\"lem\"", "\"lem\"", "\"lem\""], "\"lmf\"", true),
  ("COI_RECIPE_xt6298", &["\"ls2\"", "\"ls2\"", "\"ls2\""], "\"lbd\"", true),
  ("COI_RECIPE_v29s9s", &["\"ldf\"", "\"ldf\"", "\"ldf\""], "\"lcb\"", true),
  ("COI_RECIPE_639ssi", &["\"any,mag\"", "\"lwf\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_53y9h5", &["\"any,rar\"", "\"lwf\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_62lxxv", &["\"any,uni\"", "\"lwf\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_oof215", &["\"any,set\"", "\"lwf\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_jaura0", &["\"any,mag\"", "\"lag\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_tzm52l", &["\"any,rar\"", "\"lag\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_t0yglv", &["\"any,uni\"", "\"lag\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_b94le9", &["\"any,set\"", "\"lag\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_gbw3rf", &["\"any,mag\"", "\"lfs\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_wvxqog", &["\"any,rar\"", "\"lfs\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_vxa27q", &["\"any,uni\"", "\"lfs\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_8cszse", &["\"any,set\"", "\"lfs\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_mo8zsv", &["\"any,mag\"", "\"lvp\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_cfjrgk", &["\"any,rar\"", "\"lvp\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_bgw2zu", &["\"any,uni\"", "\"lvp\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_st6z0a", &["\"any,set\"", "\"lvp\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_x8x9hz", &["\"any,mag\"", "\"lhr\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_h3ckkk", &["\"any,rar\"", "\"lhr\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_i2091a", &["\"any,uni\"", "\"lhr\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_cp0qxq", &["\"any,set\"", "\"lhr\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_u5hebo", &["\"any,mag\"", "\"lsk\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_7ojlvl", &["\"any,rar\"", "\"lsk\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_6pvxev", &["\"any,uni\"", "\"lsk\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_xk74l9", &["\"any,set\"", "\"lsk\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_57lwp8", &["\"any,mag\"", "\"lmf\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_99pga7", &["\"any,rar\"", "\"lmf\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_a8d4qx", &["\"any,uni\"", "\"lmf\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_kinv83", &["\"any,set\"", "\"lmf\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_n64kkx", &["\"any,mag\"", "\"lbd\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_hr2fcm", &["\"any,rar\"", "\"lbd\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_gseqvw", &["\"any,uni\"", "\"lbd\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_nhob48", &["\"any,set\"", "\"lbd\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_4v2a2v", &["\"any,mag\"", "\"lcb\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_g5e1tg", &["\"any,rar\"", "\"lcb\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_h41qa6", &["\"any,uni\"", "\"lcb\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_dmz9ou", &["\"any,set\"", "\"lcb\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_jx7r32", &["\"any,mag\"", "\"lud\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_1g54yr", &["\"any,rar\"", "\"lud\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_hhgi1", &["\"any,uni\"", "\"lud\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_v8igh1", &["\"any,set\"", "\"lud\"", "\"xf1,qty=2\"", "\"li1,qty=2\"", "\"ls1,qty=2\"", "\"ld1,qty=2\""], "useitem", true),
  ("COI_RECIPE_zg41l1", &["\"weap,armo,mag\"", "\"lzb\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_hz179c", &["\"weap,armo,rar\"", "\"lzb\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_e2mriy", &["\"weap,armo,uni\"", "\"lzb\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_9ufsxq", &["\"weap,armo,set\"", "\"lzb\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_19wato", &["\"weap,armo,mag\"", "\"lsw\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_lv041l", &["\"weap,armo,rar\"", "\"lsw\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_a6nuqp", &["\"weap,armo,uni\"", "\"lsw\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_5ygw5h", &["\"weap,armo,set\"", "\"lsw\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_333iam", &["\"weap,armo,mag\"", "\"lmn\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_82rgrh", &["\"weap,armo,rar\"", "\"lmn\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_uwomfd", &["\"weap,armo,uni\"", "\"lmn\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_z4vl0l", &["\"weap,armo,set\"", "\"lmn\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_jqqaiz", &["\"weap,armo,mag\"", "\"lqd\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_v4bp0w", &["\"weap,armo,rar\"", "\"lqd\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_7v4e5y", &["\"weap,armo,uni\"", "\"lqd\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_c3bcr6", &["\"weap,armo,set\"", "\"lqd\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_5g7sa0", &["\"weap,armo,mag\"", "\"lji\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_yv75zx", &["\"weap,armo,rar\"", "\"lji\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_2tj77n", &["\"weap,armo,uni\"", "\"lji\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_71q5sv", &["\"weap,armo,set\"", "\"lji\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_aimee1", &["\"weap,armo,mag\"", "\"ljs\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_fm1n1o", &["\"weap,armo,rar\"", "\"ljs\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_gfmbqm", &["\"weap,armo,uni\"", "\"ljs\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("COI_RECIPE_c7fd5e", &["\"weap,armo,set\"", "\"ljs\"", "\"xf1,qty=3\"", "\"nl1,qty=3\"", "\"li1,qty=3\"", "\"ls1,qty=3\"", "\"ld1,qty=3\""], "useitem", true),
  ("[QCT] 9 Chipped Amethyst -> 3 Flawed Amethyst", &["gcv,qty=9"], "gfv", true),
  ("[QCT] 9 Flawed Amethyst -> 3 Standard Amethyst", &["gfv,qty=9"], "gsv", true),
  ("[QCT] 9 Standard Amethyst -> 3 Flawless Amethyst", &["gsv,qty=9"], "gzv", true),
  ("[QCT] 9 Flawless Amethyst -> 3 Perfect Amethyst", &["gzv,qty=9"], "gpv", true),
  ("[QCT] 9 Chipped Ruby -> 3 Flawed Ruby", &["gcr,qty=9"], "gfr", true),
  ("[QCT] 9 Flawed Ruby -> 3 Standard Ruby", &["gfr,qty=9"], "gsr", true),
  ("[QCT] 9 Standard Ruby -> 3 Flawless Ruby", &["gsr,qty=9"], "glr", true),
  ("[QCT] 9 Flawless Ruby -> 3 Perfect Ruby", &["glr,qty=9"], "gpr", true),
  ("[QCT] 9 Chipped Sapphire -> 3 Flawed Sapphire", &["gcb,qty=9"], "gfb", true),
  ("[QCT] 9 Flawed Sapphire -> 3 Standard Sapphire", &["gfb,qty=9"], "gsb", true),
  ("[QCT] 9 Standard Sapphire -> 3 Flawless Sapphire", &["gsb,qty=9"], "glb", true),
  ("[QCT] 9 Flawless Sapphire -> 3 Perfect Sapphire", &["glb,qty=9"], "gpb", true),
  ("[QCT] 9 Chipped Topaz -> 3 Flawed Topaz", &["gcy,qty=9"], "gfy", true),
  ("[QCT] 9 Flawed Topaz -> 3 Standard Topaz", &["gfy,qty=9"], "gsy", true),
  ("[QCT] 9 Standard Topaz -> 3 Flawless Topaz", &["gsy,qty=9"], "gly", true),
  ("[QCT] 9 Flawless Topaz -> 3 Perfect Topaz", &["gly,qty=9"], "gpy", true),
  ("[QCT] 9 Chipped Emerald -> 3 Flawed Emerald", &["gcg,qty=9"], "gfg", true),
  ("[QCT] 9 Flawed Emerald -> 3 Standard Emerald", &["gfg,qty=9"], "gsg", true),
  ("[QCT] 9 Standard Emerald -> 3 Flawless Emerald", &["gsg,qty=9"], "glg", true),
  ("[QCT] 9 Flawless Emerald -> 3 Perfect Emerald", &["glg,qty=9"], "gpg", true),
  ("[QCT] 9 Chipped Diamond -> 3 Flawed Diamond", &["gcw,qty=9"], "gfw", true),
  ("[QCT] 9 Flawed Diamond -> 3 Standard Diamond", &["gfw,qty=9"], "gsw", true),
  ("[QCT] 9 Standard Diamond -> 3 Flawless Diamond", &["gsw,qty=9"], "glw", true),
  ("[QCT] 9 Flawless Diamond -> 3 Perfect Diamond", &["glw,qty=9"], "gpw", true),
  ("[QCT] 9 Chipped Skull -> 3 Flawed Skull", &["skc,qty=9"], "skf", true),
  ("[QCT] 9 Flawed Skull -> 3 Standard Skull", &["skf,qty=9"], "sku", true),
  ("[QCT] 9 Standard Skull -> 3 Flawless Skull", &["sku,qty=9"], "skl", true),
  ("[QCT] 9 Flawless Skull -> 3 Perfect Skull", &["skl,qty=9"], "skz", true),
  ("[QCT] 9 El->Eld -> 3 R02", &["r01,qty=9"], "r02", true),
  ("[QCT] 9 Eld->Tir -> 3 R03", &["r02,qty=9"], "r03", true),
  ("[QCT] 9 Tir->Nef -> 3 R04", &["r03,qty=9"], "r04", true),
  ("[QCT] 9 Nef->Eth -> 3 R05", &["r04,qty=9"], "r05", true),
  ("[QCT] 9 Eth->Ith -> 3 R06", &["r05,qty=9"], "r06", true),
  ("[QCT] 9 Ith->Tal -> 3 R07", &["r06,qty=9"], "r07", true),
  ("[QCT] 9 Tal->Ral -> 3 R08", &["r07,qty=9"], "r08", true),
  ("[QCT] 9 Ral->Ort -> 3 R09", &["r08,qty=9"], "r09", true),
  ("[QCT] 9 Ort->Thul -> 3 R10", &["r09,qty=9"], "r10", true),
  ("[QCT] 9 Thul->Amn -> 3 R11", &["r10,qty=9", "gcy,qty=3"], "r11", true),
  ("[QCT] 9 Amn->Sol -> 3 R12", &["r11,qty=9", "gcv,qty=3"], "r12", true),
  ("[QCT] 9 Sol->Shael -> 3 R13", &["r12,qty=9", "gcb,qty=3"], "r13", true),
  ("[QCT] 9 Shael->Dol -> 3 R14", &["r13,qty=9", "gcr,qty=3"], "r14", true),
  ("[QCT] 9 Dol->Hel -> 3 R15", &["r14,qty=9", "gcg,qty=3"], "r15", true),
  ("[QCT] 9 Hel->Io -> 3 R16", &["r15,qty=9", "gcw,qty=3"], "r16", true),
  ("[QCT] 9 Io->Lum -> 3 R17", &["r16,qty=9", "gfy,qty=3"], "r17", true),
  ("[QCT] 9 Lum->Ko -> 3 R18", &["r17,qty=9", "gfv,qty=3"], "r18", true),
  ("[QCT] 9 Ko->Fal -> 3 R19", &["r18,qty=9", "gfb,qty=3"], "r19", true),
  ("[QCT] 9 Fal->Lem -> 3 R20", &["r19,qty=9", "gfr,qty=3"], "r20", true),
  ("[QCT] 9 Lem->Pul -> 3 R21", &["r20,qty=9", "gfg,qty=3"], "r21", true),
  ("[QCT] 6 Pul->Um -> 3 R22", &["r21,qty=6", "gfw,qty=3"], "r22", true),
  ("[QCT] 6 Um->Mal -> 3 R23", &["r22,qty=6", "gcy,qty=3"], "r23", true),
  ("[QCT] 6 Mal->Ist -> 3 R24", &["r23,qty=6", "gsv,qty=3"], "r24", true),
  ("[QCT] 6 Ist->Gul -> 3 R25", &["r24,qty=6", "gsb,qty=3"], "r25", true),
  ("[QCT] 6 Gul->Vex -> 3 R26", &["r25,qty=6", "gsr,qty=3"], "r26", true),
  ("[QCT] 6 Vex->Ohm -> 3 R27", &["r26,qty=6", "gsg,qty=3"], "r27", true),
  ("[QCT] 6 Ohm->Lo -> 3 R28", &["r27,qty=6", "gsw,qty=3"], "r28", true),
  ("[QCT] 6 Lo->Sur -> 3 R29", &["r28,qty=6", "gly,qty=3"], "r29", true),
  ("[QCT] 6 Sur->Ber -> 3 R30", &["r29,qty=6", "gzv,qty=3"], "r30", true),
  ("[QCT] 6 Ber->Jah -> 3 R31", &["r30,qty=6", "glb,qty=3"], "r31", true),
  ("[QCT] 6 Jah->Cham -> 3 R32", &["r31,qty=6", "glr,qty=3"], "r32", true),
  ("[QCT] 6 Cham->Zod -> 3 R33", &["r32,qty=6", "glg,qty=3"], "r33", true),
  ("[QCT] 1 Perfect Amethyst -> 3 Flawless Amethyst", &["gpv"], "gzv", true),
  ("[QCT] 1 Flawless Amethyst -> 3 Standard Amethyst", &["gzv"], "gsv", true),
  ("[QCT] 1 Standard Amethyst -> 3 Flawed Amethyst", &["gsv"], "gfv", true),
  ("[QCT] 1 Flawed Amethyst -> 3 Chipped Amethyst", &["gfv"], "gcv", true),
  ("[QCT] 1 Perfect Ruby -> 3 Flawless Ruby", &["gpr"], "glr", true),
  ("[QCT] 1 Flawless Ruby -> 3 Standard Ruby", &["glr"], "gsr", true),
  ("[QCT] 1 Standard Ruby -> 3 Flawed Ruby", &["gsr"], "gfr", true),
  ("[QCT] 1 Flawed Ruby -> 3 Chipped Ruby", &["gfr"], "gcr", true),
  ("[QCT] 1 Perfect Sapphire -> 3 Flawless Sapphire", &["gpb"], "glb", true),
  ("[QCT] 1 Flawless Sapphire -> 3 Standard Sapphire", &["glb"], "gsb", true),
  ("[QCT] 1 Standard Sapphire -> 3 Flawed Sapphire", &["gsb"], "gfb", true),
  ("[QCT] 1 Flawed Sapphire -> 3 Chipped Sapphire", &["gfb"], "gcb", true),
  ("[QCT] 1 Perfect Topaz -> 3 Flawless Topaz", &["gpy"], "gly", true),
  ("[QCT] 1 Flawless Topaz -> 3 Standard Topaz", &["gly"], "gsy", true),
  ("[QCT] 1 Standard Topaz -> 3 Flawed Topaz", &["gsy"], "gfy", true),
  ("[QCT] 1 Flawed Topaz -> 3 Chipped Topaz", &["gfy"], "gcy", true),
  ("[QCT] 1 Perfect Emerald -> 3 Flawless Emerald", &["gpg"], "glg", true),
  ("[QCT] 1 Flawless Emerald -> 3 Standard Emerald", &["glg"], "gsg", true),
  ("[QCT] 1 Standard Emerald -> 3 Flawed Emerald", &["gsg"], "gfg", true),
  ("[QCT] 1 Flawed Emerald -> 3 Chipped Emerald", &["gfg"], "gcg", true),
  ("[QCT] 1 Perfect Diamond -> 3 Flawless Diamond", &["gpw"], "glw", true),
  ("[QCT] 1 Flawless Diamond -> 3 Standard Diamond", &["glw"], "gsw", true),
  ("[QCT] 1 Standard Diamond -> 3 Flawed Diamond", &["gsw"], "gfw", true),
  ("[QCT] 1 Flawed Diamond -> 3 Chipped Diamond", &["gfw"], "gcw", true),
  ("[QCT] 1 Perfect Skull -> 3 Flawless Skull", &["skz"], "skl", true),
  ("[QCT] 1 Flawless Skull -> 3 Standard Skull", &["skl"], "sku", true),
  ("[QCT] 1 Standard Skull -> 3 Flawed Skull", &["sku"], "skf", true),
  ("[QCT] 1 Flawed Skull -> 3 Chipped Skull", &["skf"], "skc", true),
  ("[QCT] 1 R02 + 3 Perfect Gems -> 3 R01", &["r02", "\"gem4,qty=3\""], "r01", true),
  ("[QCT] 1 R03 + 3 Perfect Gems -> 3 R02", &["r03", "\"gem4,qty=3\""], "r02", true),
  ("[QCT] 1 R04 + 3 Perfect Gems -> 3 R03", &["r04", "\"gem4,qty=3\""], "r03", true),
  ("[QCT] 1 R05 + 3 Perfect Gems -> 3 R04", &["r05", "\"gem4,qty=3\""], "r04", true),
  ("[QCT] 1 R06 + 3 Perfect Gems -> 3 R05", &["r06", "\"gem4,qty=3\""], "r05", true),
  ("[QCT] 1 R07 + 3 Perfect Gems -> 3 R06", &["r07", "\"gem4,qty=3\""], "r06", true),
  ("[QCT] 1 R08 + 3 Perfect Gems -> 3 R07", &["r08", "\"gem4,qty=3\""], "r07", true),
  ("[QCT] 1 R09 + 3 Perfect Gems -> 3 R08", &["r09", "\"gem4,qty=3\""], "r08", true),
  ("[QCT] 1 R10 + 3 Perfect Gems -> 3 R09", &["r10", "\"gem4,qty=3\""], "r09", true),
  ("[QCT] 1 R11 + 3 Perfect Gems -> 3 R10", &["r11", "\"gem4,qty=3\""], "r10", true),
  ("[QCT] 1 R12 + 3 Perfect Gems -> 3 R11", &["r12", "\"gem4,qty=3\""], "r11", true),
  ("[QCT] 1 R13 + 3 Perfect Gems -> 3 R12", &["r13", "\"gem4,qty=3\""], "r12", true),
  ("[QCT] 1 R14 + 3 Perfect Gems -> 3 R13", &["r14", "\"gem4,qty=3\""], "r13", true),
  ("[QCT] 1 R15 + 3 Perfect Gems -> 3 R14", &["r15", "\"gem4,qty=3\""], "r14", true),
  ("[QCT] 1 R16 + 3 Perfect Gems -> 3 R15", &["r16", "\"gem4,qty=3\""], "r15", true),
  ("[QCT] 1 R17 + 3 Perfect Gems -> 3 R16", &["r17", "\"gem4,qty=3\""], "r16", true),
  ("[QCT] 1 R18 + 3 Perfect Gems -> 3 R17", &["r18", "\"gem4,qty=3\""], "r17", true),
  ("[QCT] 1 R19 + 3 Perfect Gems -> 3 R18", &["r19", "\"gem4,qty=3\""], "r18", true),
  ("[QCT] 1 R20 + 3 Perfect Gems -> 3 R19", &["r20", "\"gem4,qty=3\""], "r19", true),
  ("[QCT] 1 R21 + 3 Perfect Gems -> 3 R20", &["r21", "\"gem4,qty=3\""], "r20", true),
  ("[QCT] 1 R22 + 3 Perfect Gems -> 2 R21", &["r22", "\"gem4,qty=3\""], "r21", true),
  ("[QCT] 1 R23 + 3 Perfect Gems -> 2 R22", &["r23", "\"gem4,qty=3\""], "r22", true),
  ("[QCT] 1 R24 + 3 Perfect Gems -> 2 R23", &["r24", "\"gem4,qty=3\""], "r23", true),
  ("[QCT] 1 R25 + 3 Perfect Gems -> 2 R24", &["r25", "\"gem4,qty=3\""], "r24", true),
  ("[QCT] 1 R26 + 3 Perfect Gems -> 2 R25", &["r26", "\"gem4,qty=3\""], "r25", true),
  ("[QCT] 1 R27 + 3 Perfect Gems -> 2 R26", &["r27", "\"gem4,qty=3\""], "r26", true),
  ("[QCT] 1 R28 + 3 Perfect Gems -> 2 R27", &["r28", "\"gem4,qty=3\""], "r27", true),
  ("[QCT] 1 R29 + 3 Perfect Gems -> 2 R28", &["r29", "\"gem4,qty=3\""], "r28", true),
  ("[QCT] 1 R30 + 3 Perfect Gems -> 2 R29", &["r30", "\"gem4,qty=3\""], "r29", true),
  ("[QCT] 1 R31 + 3 Perfect Gems -> 2 R30", &["r31", "\"gem4,qty=3\""], "r30", true),
  ("[QCT] 1 R32 + 3 Perfect Gems -> 2 R31", &["r32", "\"gem4,qty=3\""], "r31", true),
  ("[QCT] 1 R33 + 3 Perfect Gems -> 2 R32", &["r33", "\"gem4,qty=3\""], "r32", true),
  ("[P11][Test] RM1+LIN→Realm I Portal", &["rm1", "lin", "0", "0", "0", "0"], "Red Portal,lvl=177,qty=1", true),
  ("[P16] 仙宠合成: 玄龟", &["pe1", "\"li1,qty=1\""], "\"pt1,uni\"", true),
  ("[P16] 仙宠合成: 灵獒", &["pe2", "\"li1,qty=1\""], "\"pt2,uni\"", true),
  ("[P16] 仙宠合成: 仙鹤", &["pe3", "\"li1,qty=1\""], "\"pt3,uni\"", true),
];
// Total: 867 recipes (155 vanilla + 712 mod)