/// All item type definitions (auto-generated from game TXT files)
/// Source: D2R 3.2-92777 + D2RMM 仙道轮回 mod
/// Format: (item_code, display_name, is_armor, is_weapon, is_shield)
#[rustfmt::skip]
pub const ALL_ITEMS: &[(&str, &str, bool, bool, bool)] = &[
  ("0sc", "Scroll of Knowledge", false, false, false),
  ("2ax", "Double Axe", false, true, false),
  ("2hs", "Two-Handed Sword", false, true, false),
  ("6bs", "Shillelagh", false, true, false),
  ("6cb", "Great Bow", false, true, false),
  ("6cs", "Elder Staff", false, true, false),
  ("6hb", "Blade Bow", false, true, false),
  ("6hx", "Colossus Crossbow", false, true, false),
  ("6l7", "Crusader Bow", false, true, false),
  ("6lb", "Shadow Bow", false, true, false),
  ("6ls", "Stalagmite", false, true, false),
  ("6lw", "Hydra Bow", false, true, false),
  ("6lx", "Pellet Bow", false, true, false),
  ("6mx", "Gorgon Crossbow", false, true, false),
  ("6rx", "Demon Crossbow", false, true, false),
  ("6s7", "Diamond Bow", false, true, false),
  ("6sb", "Spider Bow", false, true, false),
  ("6ss", "Walking Stick", false, true, false),
  ("6sw", "Ward Bow", false, true, false),
  ("6ws", "Archon Staff", false, true, false),
  ("72a", "Ettin Axe", false, true, false),
  ("72h", "Legend Sword", false, true, false),
  ("7ar", "Suwayyah", false, true, false),
  ("7ax", "Small Crescent", false, true, false),
  ("7b7", "Champion Sword", false, true, false),
  ("7b8", "Winged Axe", false, true, false),
  ("7ba", "Silver-edged Axe", false, true, false),
  ("7bk", "Winged Knife", false, true, false),
  ("7bl", "Legend Spike", false, true, false),
  ("7br", "Mancatcher", false, true, false),
  ("7bs", "Conquest Sword", false, true, false),
  ("7bt", "Decapitator", false, true, false),
  ("7bw", "Lich Wand", false, true, false),
  ("7cl", "Truncheon", false, true, false),
  ("7cm", "Highland Blade", false, true, false),
  ("7cr", "Phase Blade", false, true, false),
  ("7cs", "Battle Cestus", false, true, false),
  ("7dg", "Bone Knife", false, true, false),
  ("7di", "Mithral Point", false, true, false),
  ("7fb", "Colossal Sword", false, true, false),
  ("7fc", "Hydra Edge", false, true, false),
  ("7fl", "Scourge", false, true, false),
  ("7ga", "Champion Axe", false, true, false),
  ("7gd", "Colossus Blade", false, true, false),
  ("7gi", "Glorious Axe", false, true, false),
  ("7gl", "Ghost Glaive", false, true, false),
  ("7gm", "Thunder Maul", false, true, false),
  ("7gs", "Balrog Blade", false, true, false),
  ("7gw", "Unearthed Wand", false, true, false),
  ("7h7", "Great Poleaxe", false, true, false),
  ("7ha", "Tomahawk", false, true, false),
  ("7ja", "Hyperion Javelin", false, true, false),
  ("7kr", "Fanged Knife", false, true, false),
  ("7la", "Feral Axe", false, true, false),
  ("7ls", "Cryptic Sword", false, true, false),
  ("7lw", "Feral Claws", false, true, false),
  ("7m7", "Ogre Maul", false, true, false),
  ("7ma", "Reinforced Mace", false, true, false),
  ("7mp", "War Spike", false, true, false),
  ("7mt", "Devil Star", false, true, false),
  ("7o7", "Ogre Axe", false, true, false),
  ("7p7", "War Pike", false, true, false),
  ("7pa", "Cryptic Axe", false, true, false),
  ("7pi", "Stygian Pilum", false, true, false),
  ("7qr", "Scissors Suwayyah", false, true, false),
  ("7qs", "Seraph Rod", false, true, false),
  ("7s7", "Balrog Spear", false, true, false),
  ("7s8", "Thresher", false, true, false),
  ("7sb", "Elegant Blade", false, true, false),
  ("7sc", "Mighty Scepter", false, true, false),
  ("7sm", "Ataghan", false, true, false),
  ("7sp", "Tyrant Club", false, true, false),
  ("7sr", "Hyperion Spear", false, true, false),
  ("7ss", "Falcata", false, true, false),
  ("7st", "Ghost Spear", false, true, false),
  ("7ta", "Flying Axe", false, true, false),
  ("7tk", "Flying Knife", false, true, false),
  ("7tr", "Stygian Pike", false, true, false),
  ("7ts", "Winged Harpoon", false, true, false),
  ("7tw", "Runic Talons", false, true, false),
  ("7vo", "Colossus Voulge", false, true, false),
  ("7wa", "Berserker Axe", false, true, false),
  ("7wb", "Wrist Sword", false, true, false),
  ("7wc", "Giant Thresher", false, true, false),
  ("7wd", "Mythical Sword", false, true, false),
  ("7wh", "Legendary Mallet", false, true, false),
  ("7wn", "Polished Wand", false, true, false),
  ("7ws", "Caduceus", false, true, false),
  ("7xf", "War Fist", false, true, false),
  ("7yw", "Ghost Wand", false, true, false),
  ("8bs", "Gothic Staff", false, true, false),
  ("8cb", "Double Bow", false, true, false),
  ("8cs", "Cedar Staff", false, true, false),
  ("8hb", "Razor Bow", false, true, false),
  ("8hx", "Ballista", false, true, false),
  ("8l8", "Long Siege Bow", false, true, false),
  ("8lb", "Cedar Bow", false, true, false),
  ("8ls", "Quarterstaff", false, true, false),
  ("8lw", "Gothic Bow", false, true, false),
  ("8lx", "Arbalest", false, true, false),
  ("8mx", "Siege Crossbow", false, true, false),
  ("8rx", "Chu-Ko-Nu", false, true, false),
  ("8s8", "Short Siege Bow", false, true, false),
  ("8sb", "Edge Bow", false, true, false),
  ("8ss", "Jo Staff", false, true, false),
  ("8sw", "Rune Bow", false, true, false),
  ("8ws", "Rune Staff", false, true, false),
  ("92a", "Twin Axe", false, true, false),
  ("92h", "Espandon", false, true, false),
  ("9ar", "Quhab", false, true, false),
  ("9ax", "Cleaver", false, true, false),
  ("9b7", "Lochaber Axe", false, true, false),
  ("9b8", "Hurlbat", false, true, false),
  ("9b9", "Gothic Sword", false, true, false),
  ("9ba", "Bearded Axe", false, true, false),
  ("9bk", "War Dart", false, true, false),
  ("9bl", "Stilleto", false, true, false),
  ("9br", "War Fork", false, true, false),
  ("9bs", "Battle Sword", false, true, false),
  ("9bt", "Tabar", false, true, false),
  ("9bw", "Tomb Wand", false, true, false),
  ("9cl", "Cudgel", false, true, false),
  ("9cm", "Dacian Falx", false, true, false),
  ("9cr", "Dimensional Blade", false, true, false),
  ("9cs", "Hand Scythe", false, true, false),
  ("9dg", "Poignard", false, true, false),
  ("9di", "Rondel", false, true, false),
  ("9fb", "Zweihander", false, true, false),
  ("9fc", "Tulwar", false, true, false),
  ("9fl", "Knout", false, true, false),
  ("9ga", "Gothic Axe", false, true, false),
  ("9gd", "Executioner Sword", false, true, false),
  ("9gi", "Ancient Axe", false, true, false),
  ("9gl", "Spiculum", false, true, false),
  ("9gm", "Martel de Fer", false, true, false),
  ("9gs", "Tusk Sword", false, true, false),
  ("9gw", "Grave Wand", false, true, false),
  ("9h9", "Bec-de-Corbin", false, true, false),
  ("9ha", "Hatchet", false, true, false),
  ("9ja", "War Javelin", false, true, false),
  ("9kr", "Cinquedeas", false, true, false),
  ("9la", "Military Axe", false, true, false),
  ("9ls", "Rune Sword", false, true, false),
  ("9lw", "Greater Claws", false, true, false),
  ("9m9", "War Club", false, true, false),
  ("9ma", "Flanged Mace", false, true, false),
  ("9mp", "Crowbill", false, true, false),
  ("9mt", "Jagged Star", false, true, false),
  ("9p9", "Lance", false, true, false),
  ("9pa", "Partizan", false, true, false),
  ("9pi", "Great Pilum", false, true, false),
  ("9qr", "Scissors Quhab", false, true, false),
  ("9qs", "Holy Water Sprinkler", false, true, false),
  ("9s8", "Battle Scythe", false, true, false),
  ("9s9", "Simbilan", false, true, false),
  ("9sb", "Shamshir", false, true, false),
  ("9sc", "Rune Scepter", false, true, false),
  ("9sm", "Cutlass", false, true, false),
  ("9sp", "Barbed Club", false, true, false),
  ("9sr", "War Spear", false, true, false),
  ("9ss", "Gladius", false, true, false),
  ("9st", "Yari", false, true, false),
  ("9ta", "Francisca", false, true, false),
  ("9tk", "Battle Dart", false, true, false),
  ("9tr", "Fuscina", false, true, false),
  ("9ts", "Harpoon", false, true, false),
  ("9tw", "Greater Talons", false, true, false),
  ("9vo", "Bill", false, true, false),
  ("9wa", "Naga", false, true, false),
  ("9wb", "Wrist Spike", false, true, false),
  ("9wc", "Grim Scythe", false, true, false),
  ("9wd", "Ancient Sword", false, true, false),
  ("9wh", "Battle Hammer", false, true, false),
  ("9wn", "Burnt Wand", false, true, false),
  ("9ws", "Divine Scepter", false, true, false),
  ("9xf", "Fascia", false, true, false),
  ("9yw", "Petrified Wand", false, true, false),
  ("a01", "Attack Spirit Treasure L1", false, false, false),
  ("a05", "Attack Spirit Treasure L5", false, false, false),
  ("a10", "Attack Spirit Treasure L10", false, false, false),
  ("a15", "Attack Spirit Treasure L15", false, false, false),
  ("a20", "Attack Spirit Treasure L20", false, false, false),
  ("a25", "Attack Spirit Treasure L25", false, false, false),
  ("a30", "Attack Spirit Treasure L30", false, false, false),
  ("aar", "Ancient Armor", true, false, false),
  ("am1", "Stag Bow", false, true, false),
  ("am2", "Reflex Bow", false, true, false),
  ("am3", "Maiden Spear", false, true, false),
  ("am4", "Maiden Pike", false, true, false),
  ("am5", "Maiden Javelin", false, true, false),
  ("am6", "Ashwood Bow", false, true, false),
  ("am7", "Ceremonial Bow", false, true, false),
  ("am8", "Ceremonial Spear", false, true, false),
  ("am9", "Ceremonial Pike", false, true, false),
  ("ama", "Ceremonial Javelin", false, true, false),
  ("amb", "Matriarchal Bow", false, true, false),
  ("amc", "Grand Matron Bow", false, true, false),
  ("amd", "Matriarchal Spear", false, true, false),
  ("ame", "Matriarchal Pike", false, true, false),
  ("amf", "Matriarchal Javelin", false, true, false),
  ("amu", "Amulet", false, false, false),
  ("aqv", "Arrows", false, false, false),
  ("ass", "Book of Skill", false, false, false),
  ("atc", "Attack Spirit Embryo", false, false, false),
  ("axe", "Axe", false, true, false),
  ("axf", "Hatchet Hands", false, true, false),
  ("ba1", "Jawbone Cap", true, false, false),
  ("ba2", "Fanged Helm", true, false, false),
  ("ba3", "Horned Helm", true, false, false),
  ("ba4", "Assault Helmet", true, false, false),
  ("ba5", "Avenger Guard", true, false, false),
  ("ba6", "Jawbone Visor", true, false, false),
  ("ba7", "Lion Helm", true, false, false),
  ("ba8", "Rage Mask", true, false, false),
  ("ba9", "Savage Helmet", true, false, false),
  ("baa", "Slayer Guard", true, false, false),
  ("bab", "Carnage Helm", true, false, false),
  ("bac", "Fury Visor", true, false, false),
  ("bad", "Destroyer Helm", true, false, false),
  ("bae", "Conqueror Crown", true, false, false),
  ("baf", "Guardian Crown", true, false, false),
  ("bal", "Balanced Axe", false, true, false),
  ("bar", "Bardiche", false, true, false),
  ("bax", "Broad Axe", false, true, false),
  ("bbb", "Lam Esen's Tome", false, false, false),
  ("bet", "Burning Essence of Terror", false, false, false),
  ("bey", "Baal's Eye", false, false, false),
  ("bhm", "Bone Helm", true, false, false),
  ("bkd", "Key to the Cairn Stones", false, false, false),
  ("bkf", "Balanced Knife", false, true, false),
  ("bks", "Scroll of Inifuss", false, false, false),
  ("bld", "Blade", false, true, false),
  ("box", "Horadric Cube", false, false, false),
  ("bpl", "Large Blue Potion", false, false, false),
  ("bps", "Small Blue Potion", false, false, false),
  ("brn", "Brandistock", false, true, false),
  ("brs", "Breast Plate", true, false, false),
  ("brz", "Brain", false, false, false),
  ("bsd", "Broad Sword", false, true, false),
  ("bsh", "Bone Shield", true, false, true),
  ("bst", "Battle Staff", false, true, false),
  ("bsw", "Bastard Sword", false, true, false),
  ("btl", "Blade Talons", false, true, false),
  ("btx", "Battle Axe", false, true, false),
  ("buc", "Buckler", true, false, true),
  ("bwn", "Bone Wand", false, true, false),
  ("cap", "Cap", true, false, false),
  ("cbw", "Composite Bow", false, true, false),
  ("ceh", "Charged Essense of Hatred", false, false, false),
  ("ces", "Cestus", false, true, false),
  ("chn", "Chain Mail", true, false, false),
  ("ci0", "Circlet", true, false, false),
  ("ci1", "Coronet", true, false, false),
  ("ci2", "Tiara", true, false, false),
  ("ci3", "Diadem", true, false, false),
  ("cjw", "Colossal Jewel", false, false, false),
  ("clb", "Club", false, true, false),
  ("cll", "Spirit Root Test Decree", false, false, false),
  ("clm", "Claymore", false, true, false),
  ("clw", "Claws", false, true, false),
  ("cly", "Spirit Root Probe Jade", false, false, false),
  ("cm1", "Small Charm", false, false, false),
  ("cm2", "Large Charm", false, false, false),
  ("cm3", "Grand Charm", false, false, false),
  ("cqv", "Bolts", false, false, false),
  ("crn", "Crown", true, false, false),
  ("crs", "Crystal Sword", false, true, false),
  ("cs2", "Crafted Sunder Charm", false, false, false),
  ("cst", "Gnarled Staff", false, true, false),
  ("d01", "Defense Spirit Treasure L1", false, false, false),
  ("d05", "Defense Spirit Treasure L5", false, false, false),
  ("d10", "Defense Spirit Treasure L10", false, false, false),
  ("d15", "Defense Spirit Treasure L15", false, false, false),
  ("d20", "Defense Spirit Treasure L20", false, false, false),
  ("d25", "Defense Spirit Treasure L25", false, false, false),
  ("d30", "Defense Spirit Treasure L30", false, false, false),
  ("d33", "Decoy Gidbinn", false, true, false),
  ("def", "Defense Spirit Embryo", false, false, false),
  ("dgr", "Dagger", false, true, false),
  ("dhn", "Diablo's Horn", false, false, false),
  ("dir", "Dirk", false, true, false),
  ("dr1", "Wolf Head", true, false, false),
  ("dr2", "Hawk Helm", true, false, false),
  ("dr3", "Antlers", true, false, false),
  ("dr4", "Falcon Mask", true, false, false),
  ("dr5", "Spirit Mask", true, false, false),
  ("dr6", "Alpha Helm", true, false, false),
  ("dr7", "Griffon Headress", true, false, false),
  ("dr8", "Hunter's Guise", true, false, false),
  ("dr9", "Sacred Feathers", true, false, false),
  ("dra", "Totemic Mask", true, false, false),
  ("drb", "Blood Spirit", true, false, false),
  ("drc", "Sun Spirit", true, false, false),
  ("drd", "Earth Spirit", true, false, false),
  ("dre", "Sky Spirit", true, false, false),
  ("drf", "Dream Spirit", true, false, false),
  ("ear", "Ear", false, false, false),
  ("elx", "Elixir", false, false, false),
  ("eyz", "Eye", false, false, false),
  ("fed", "Festering Essence of Destruction", false, false, false),
  ("fhl", "Full Helm", true, false, false),
  ("fla", "Flail", false, true, false),
  ("flb", "Flamberge", false, true, false),
  ("flc", "Falchion", false, true, false),
  ("fld", "Field Plate", true, false, false),
  ("flg", "Flag", false, false, false),
  ("fng", "Fang", false, false, false),
  ("ftb", "Frost Bind", true, false, false),
  ("ftt", "Frost Stride", true, false, false),
  ("ftu", "Frost Shell", true, false, false),
  ("ftw", "Frostbite", false, true, false),
  ("ful", "Full Plate Mail", true, false, false),
  ("g33", "The Gidbinn", false, true, false),
  ("g34", "The Golden Bird", false, false, false),
  ("gax", "Great Axe", false, true, false),
  ("gcb", "Chipped Sapphire", false, false, false),
  ("gcg", "Chipped Emerald", false, false, false),
  ("gcr", "Chipped Ruby", false, false, false),
  ("gcv", "Chipped Amethyst", false, false, false),
  ("gcw", "Chipped Diamond", false, false, false),
  ("gcy", "Chipped Topaz", false, false, false),
  ("gfb", "Flawed Sapphire", false, false, false),
  ("gfg", "Flawed Emerald", false, false, false),
  ("gfr", "Flawed Ruby", false, false, false),
  ("gfv", "Flawed Amethyst", false, false, false),
  ("gfw", "Flawed Diamond", false, false, false),
  ("gfy", "Flawed Topaz", false, false, false),
  ("ghm", "Great Helm", true, false, false),
  ("gis", "Giant Sword", false, true, false),
  ("gix", "Giant Axe", false, true, false),
  ("glb", "Flawless Sapphire", false, false, false),
  ("gld", "Gold", false, false, false),
  ("glg", "Flawless Emerald", false, false, false),
  ("glr", "Flawless Ruby", false, false, false),
  ("glv", "Glaive", false, true, false),
  ("glw", "Flawless Diamond", false, false, false),
  ("gly", "Flawless Topaz", false, false, false),
  ("gma", "Great Maul", false, true, false),
  ("gpb", "Perfect Sapphire", false, false, false),
  ("gpg", "Perfect Emerald", false, false, false),
  ("gpl", "Strangling Gas Potion", false, true, false),
  ("gpm", "Choking Gas Potion", false, true, false),
  ("gpr", "Perfect Ruby", false, false, false),
  ("gps", "Rancid Gas Potion", false, true, false),
  ("gpv", "Perfect Amethyst", false, false, false),
  ("gpw", "Perfect Diamond", false, false, false),
  ("gpy", "Perfect Topaz", false, false, false),
  ("gsb", "Sapphire", false, false, false),
  ("gsc", "Grand Scepter", false, true, false),
  ("gsd", "Great Sword", false, true, false),
  ("gsg", "Emerald", false, false, false),
  ("gsr", "Ruby", false, false, false),
  ("gsv", "Amethyst", false, false, false),
  ("gsw", "Diamond", false, false, false),
  ("gsy", "Topaz", false, false, false),
  ("gth", "Gothic Plate", true, false, false),
  ("gts", "Gothic Shield", true, false, true),
  ("gwn", "Grim Wand", false, true, false),
  ("gzv", "Flawless Amethyst", false, false, false),
  ("hal", "Halberd", false, true, false),
  ("hax", "Hand Axe", false, true, false),
  ("hbl", "Plated Belt", true, false, false),
  ("hbt", "Greaves", true, false, false),
  ("hbw", "Hunter's Bow", false, true, false),
  ("hdm", "Horadric Malus", false, true, false),
  ("hfh", "Hellforge Hammer", false, true, false),
  ("hgl", "Gauntlets", true, false, false),
  ("hla", "Hard Leather Armor", true, false, false),
  ("hlm", "Helm", true, false, false),
  ("hp1", "Minor Healing Potion", false, false, false),
  ("hp2", "Light Healing Potion", false, false, false),
  ("hp3", "Healing Potion", false, false, false),
  ("hp4", "Greater Healing Potion", false, false, false),
  ("hp5", "Super Healing Potion", false, false, false),
  ("hpf", "Full Healing Potion", false, false, false),
  ("hpo", "Healing Potion", false, false, false),
  ("hrb", "Herb", false, false, false),
  ("hrn", "Horn", false, false, false),
  ("hrt", "Heart", false, false, false),
  ("hst", "Horadric Staff", false, true, false),
  ("hxb", "Heavy Crossbow", false, true, false),
  ("ibk", "Tome of Identify", false, false, false),
  ("ice", "Malah's Potion", false, false, false),
  ("isc", "Scroll of Identify", false, false, false),
  ("j34", "A Jade Figurine", false, false, false),
  ("jav", "Javelin", false, true, false),
  ("jaw", "Jawbone", false, false, false),
  ("jew", "Jewel", false, false, false),
  ("jl1", "Gathering Charm (10)", false, false, false),
  ("jlf", "Gathering Charm", false, false, false),
  ("key", "Key", false, false, false),
  ("kit", "Kite Shield", true, false, true),
  ("kri", "Kriss", false, true, false),
  ("ktr", "Katar", false, true, false),
  ("lac", "Light Spirit Core", false, false, false),
  ("lag", "Swift Wind Glyph", false, false, false),
  ("lax", "Large Axe", false, true, false),
  ("lbb", "Long Battle Bow", false, true, false),
  ("lbd", "Treasure Glyph", false, false, false),
  ("lbl", "Sash", true, false, false),
  ("lbt", "Boots", true, false, false),
  ("lbw", "Long Bow", false, true, false),
  ("lcb", "Crush Glyph", false, false, false),
  ("lck", "Lucky Charm", false, false, false),
  ("lcr", "Soul Mark", false, false, false),
  ("ld1", "Lingyun Point (10)", false, false, false),
  ("ldc", "Dark Spirit Core", false, false, false),
  ("ldf", "Ward Mark", false, false, false),
  ("lea", "Leather Armor", true, false, false),
  ("leg", "Wirt's Leg", false, true, false),
  ("lem", "Blaze Mark", false, false, false),
  ("lfb", "Thunder Bind", true, false, false),
  ("lfs", "Mingsha Glyph", false, false, false),
  ("lft", "Lightning Stride", true, false, false),
  ("lfu", "Lightning Shell", true, false, false),
  ("lfw", "Thunderfury", false, true, false),
  ("lgc", "Gold Spirit Core", false, false, false),
  ("lgl", "Leather Gloves", true, false, false),
  ("lgp", "Root Essence", false, false, false),
  ("lgs", "Spirit Root Divine Stone", false, false, false),
  ("lgx", "Spirit Root Embryo", false, false, false),
  ("lgy", "Spirit Root Source Essence", false, false, false),
  ("lgz", "Spirit Root True Marrow", false, false, false),
  ("lhc", "Fire Spirit Core", false, false, false),
  ("lhr", "Thorns Glyph", false, false, false),
  ("li1", "Spirit Seal (10)", false, false, false),
  ("lin", "Spirit Seal", false, false, false),
  ("lji", "Cleansing Artifact", false, false, false),
  ("ljs", "Redemption Artifact", false, false, false),
  ("lka", "Light Core Dust", false, false, false),
  ("lkd", "Dark Core Dust", false, false, false),
  ("lkg", "Gold Core Dust", false, false, false),
  ("lkh", "Fire Core Dust", false, false, false),
  ("lkm", "Wood Core Dust", false, false, false),
  ("lks", "Water Core Dust", false, false, false),
  ("lkt", "Earth Core Dust", false, false, false),
  ("lmc", "Wood Spirit Core", false, false, false),
  ("lmf", "Fortune Glyph", false, false, false),
  ("lmn", "Meditation Artifact", false, false, false),
  ("lmp", "Spirit Mark", false, false, false),
  ("lpn", "Void Mark", false, false, false),
  ("lqd", "Prayer Artifact", false, false, false),
  ("lre", "Moist Mark", false, false, false),
  ("lrg", "Large Shield", true, false, true),
  ("lri", "Guard Mark", false, false, false),
  ("ls1", "Spirit Stone (10)", false, false, false),
  ("ls2", "Devour Mark", false, false, false),
  ("lsc", "Water Spirit Core", false, false, false),
  ("lsd", "Long Sword", false, true, false),
  ("lsh", "Spirit Stone", false, false, false),
  ("lsk", "Soul Forge Glyph", false, false, false),
  ("lst", "Long Staff", false, true, false),
  ("lsw", "Might Artifact", false, false, false),
  ("ltc", "Earth Spirit Core", false, false, false),
  ("ltp", "Light Plate", true, false, false),
  ("lud", "Immortal Glyph", false, false, false),
  ("luv", "The Black Tower Key", false, false, false),
  ("lvp", "Blood Glyph", false, false, false),
  ("lvs", "Origin Mark", false, false, false),
  ("lwb", "Long War Bow", false, true, false),
  ("lwf", "Battle Soul Glyph", false, false, false),
  ("lxb", "Light Crossbow", false, true, false),
  ("lyd", "Lingyun Point", false, false, false),
  ("lzb", "Fanaticism Artifact", false, false, false),
  ("m01", "Magic Spirit Treasure L1", false, false, false),
  ("m05", "Magic Spirit Treasure L5", false, false, false),
  ("m10", "Magic Spirit Treasure L10", false, false, false),
  ("m15", "Magic Spirit Treasure L15", false, false, false),
  ("m20", "Magic Spirit Treasure L20", false, false, false),
  ("m25", "Magic Spirit Treasure L25", false, false, false),
  ("m30", "Magic Spirit Treasure L30", false, false, false),
  ("mac", "Mace", false, true, false),
  ("mag", "Magic Spirit Embryo", false, false, false),
  ("mau", "Maul", false, true, false),
  ("mbl", "Belt", true, false, false),
  ("mbr", "Mephisto's Brain", false, false, false),
  ("mbt", "Chain Boots", true, false, false),
  ("mfp", "Magic Find Potion", false, false, false),
  ("mgl", "Chain Gloves", true, false, false),
  ("mp1", "Minor Mana Potion", false, false, false),
  ("mp2", "Light Mana Potion", false, false, false),
  ("mp3", "Mana Potion", false, false, false),
  ("mp4", "Greater Mana Potion", false, false, false),
  ("mp5", "Super Mana Potion", false, false, false),
  ("mpf", "Full Mana Potion", false, false, false),
  ("mpi", "Military Pick", false, true, false),
  ("mpo", "Mana Potion", false, false, false),
  ("msf", "Staff of Kings", false, true, false),
  ("msk", "Mask", true, false, false),
  ("mss", "Mephisto's Soulstone", false, false, false),
  ("mst", "Morning Star", false, true, false),
  ("mxb", "Crossbow", false, true, false),
  ("ne1", "Preserved Head", true, false, false),
  ("ne2", "Zombie Head", true, false, false),
  ("ne3", "Unraveller Head", true, false, false),
  ("ne4", "Gargoyle Head", true, false, false),
  ("ne5", "Demon Head", true, false, false),
  ("ne6", "Mummified Trophy", true, false, false),
  ("ne7", "Fetish Trophy", true, false, false),
  ("ne8", "Sexton Trophy", true, false, false),
  ("ne9", "Cantor Trophy", true, false, false),
  ("nea", "Heirophant Trophy", true, false, false),
  ("neb", "Minion Skull", true, false, false),
  ("ned", "Overseer Skull", true, false, false),
  ("nee", "Succubus Skull", true, false, false),
  ("nef", "Bloodlord Skull", true, false, false),
  ("neg", "Hellspawn Skull", true, false, false),
  ("nl1", "Condensed Spirit Sand (10)", false, false, false),
  ("nls", "Condensed Spirit Sand", false, false, false),
  ("ob1", "Eagle Orb", false, true, false),
  ("ob2", "Sacred Globe", false, true, false),
  ("ob3", "Smoked Sphere", false, true, false),
  ("ob4", "Clasped Orb", false, true, false),
  ("ob5", "Jared's Stone", false, true, false),
  ("ob6", "Glowing Orb", false, true, false),
  ("ob7", "Crystalline Globe", false, true, false),
  ("ob8", "Cloudy Sphere", false, true, false),
  ("ob9", "Sparkling Ball", false, true, false),
  ("oba", "Swirling Crystal", false, true, false),
  ("obb", "Heavenly Stone", false, true, false),
  ("obc", "Eldritch Orb", false, true, false),
  ("obd", "Demon Heart", false, true, false),
  ("obe", "Vortex Orb", false, true, false),
  ("obf", "Dimensional Shard", false, true, false),
  ("opl", "Fulminating Potion", false, true, false),
  ("opm", "Exploding Potion", false, true, false),
  ("ops", "Oil Potion", false, true, false),
  ("pa1", "Targe", true, false, false),
  ("pa2", "Rondache", true, false, false),
  ("pa3", "Heraldic Shield", true, false, false),
  ("pa4", "Aerin Shield", true, false, false),
  ("pa5", "Crown Shield", true, false, false),
  ("pa6", "Akaran Targe", true, false, false),
  ("pa7", "Akaran Rondache", true, false, false),
  ("pa8", "Protector Shield", true, false, false),
  ("pa9", "Gilded Shield", true, false, false),
  ("paa", "Royal Shield", true, false, false),
  ("pab", "Sacred Targe", true, false, false),
  ("pac", "Sacred Rondache", true, false, false),
  ("pad", "Ancient Shield", true, false, false),
  ("pae", "Zakarum Shield", true, false, false),
  ("paf", "Vortex Shield", true, false, false),
  ("pax", "Poleaxe", false, true, false),
  ("pc1", "PoC Test Small Charm I", false, false, false),
  ("pc2", "PoC Test Small Charm II", false, false, false),
  ("pc3", "PoC Test Small Charm III", false, false, false),
  ("pc4", "PoC Test Small Charm IV", false, false, false),
  ("pc5", "PoC Test Small Charm V", false, false, false),
  ("pik", "Pike", false, true, false),
  ("pil", "Pilum", false, true, false),
  ("pk1", "Key of Terror", false, false, false),
  ("pk2", "Key of Hate", false, false, false),
  ("pk3", "Key of Destruction", false, false, false),
  ("plt", "Plate Mail", true, false, false),
  ("qbr", "Khalim's Brain", false, false, false),
  ("qey", "Khalim's Eye", false, false, false),
  ("qf1", "Khalim's Flail", false, true, false),
  ("qf2", "Khalim's Will", false, true, false),
  ("qhr", "Khalim's Heart", false, false, false),
  ("qlf", "Root Awakening Talisman", false, false, false),
  ("qll", "Quill", false, false, false),
  ("qui", "Quilted Armor", true, false, false),
  ("r01", "El Rune", false, false, false),
  ("r02", "Eld Rune", false, false, false),
  ("r03", "Tir Rune", false, false, false),
  ("r04", "Nef Rune", false, false, false),
  ("r05", "Eth Rune", false, false, false),
  ("r06", "Ith Rune", false, false, false),
  ("r07", "Tal Rune", false, false, false),
  ("r08", "Ral Rune", false, false, false),
  ("r09", "Ort Rune", false, false, false),
  ("r10", "Thul Rune", false, false, false),
  ("r11", "Amn Rune", false, false, false),
  ("r12", "Sol Rune", false, false, false),
  ("r13", "Shael Rune", false, false, false),
  ("r14", "Dol Rune", false, false, false),
  ("r15", "Hel Rune", false, false, false),
  ("r16", "Io Rune", false, false, false),
  ("r17", "Lum Rune", false, false, false),
  ("r18", "Ko Rune", false, false, false),
  ("r19", "Fal Rune", false, false, false),
  ("r20", "Lem Rune", false, false, false),
  ("r21", "Pul Rune", false, false, false),
  ("r22", "Um Rune", false, false, false),
  ("r23", "Mal Rune", false, false, false),
  ("r24", "Ist Rune", false, false, false),
  ("r25", "Gul Rune", false, false, false),
  ("r26", "Vex Rune", false, false, false),
  ("r27", "Ohm Rune", false, false, false),
  ("r28", "Lo Rune", false, false, false),
  ("r29", "Sur Rune", false, false, false),
  ("r30", "Ber Rune", false, false, false),
  ("r31", "Jah Rune", false, false, false),
  ("r32", "Cham Rune", false, false, false),
  ("r33", "Zod Rune", false, false, false),
  ("rh1", "Reincarnation Jade I", false, false, false),
  ("rh2", "Reincarnation Jade II", false, false, false),
  ("rh3", "Reincarnation Jade III", false, false, false),
  ("rh4", "Reincarnation Jade IV", false, false, false),
  ("rh5", "Reincarnation Jade V", false, false, false),
  ("rh6", "Reincarnation Jade VI", false, false, false),
  ("rin", "Ring", false, false, false),
  ("rl1", "Fusion Elixir (10)", false, false, false),
  ("rly", "Fusion Elixir", false, false, false),
  ("rm1", "Gate of Reincarnation I", false, false, false),
  ("rm2", "Gate of Reincarnation II", false, false, false),
  ("rm3", "Gate of Reincarnation III", false, false, false),
  ("rm4", "Gate of Reincarnation IV", false, false, false),
  ("rm5", "Gate of Reincarnation V", false, false, false),
  ("rm6", "Gate of Reincarnation VI", false, false, false),
  ("rng", "Ring Mail", true, false, false),
  ("rp1", "Reincarnation Token I", false, false, false),
  ("rp2", "Reincarnation Token II", false, false, false),
  ("rp3", "Reincarnation Token III", false, false, false),
  ("rp4", "Reincarnation Token IV", false, false, false),
  ("rp5", "Reincarnation Token V", false, false, false),
  ("rp6", "Reincarnation Token VI", false, false, false),
  ("rpl", "Large Red Potion", false, false, false),
  ("rps", "Small Red Potion", false, false, false),
  ("rvl", "Full Rejuvenation Potion", false, false, false),
  ("rvs", "Rejuvenation Potion", false, false, false),
  ("rxb", "Repeating Crossbow", false, true, false),
  ("sbb", "Short Battle Bow", false, true, false),
  ("sbr", "Saber", false, true, false),
  ("sbw", "Short Bow", false, true, false),
  ("scl", "Scale Mail", true, false, false),
  ("scm", "Scimitar", false, true, false),
  ("scp", "Scepter", false, true, false),
  ("scy", "Scythe", false, true, false),
  ("scz", "Scalp", false, false, false),
  ("skc", "Chipped Skull", false, false, false),
  ("skf", "Flawed Skull", false, false, false),
  ("skl", "Flawless Skull", false, false, false),
  ("skp", "Skull Cap", true, false, false),
  ("skr", "Scissors Katar", false, true, false),
  ("sku", "Skull", false, false, false),
  ("skz", "Perfect Skull", false, false, false),
  ("sml", "Small Shield", true, false, true),
  ("sol", "Soul", false, false, false),
  ("spc", "Spiked Club", false, true, false),
  ("spe", "Spleen", false, false, false),
  ("spk", "Spiked Shield", true, false, true),
  ("spl", "Splint Mail", true, false, false),
  ("spr", "Spear", false, true, false),
  ("spt", "Spetum", false, true, false),
  ("ssd", "Short Sword", false, true, false),
  ("ssp", "Short Spear", false, true, false),
  ("sst", "Short Staff", false, true, false),
  ("std", "Standard of Heroes", false, false, false),
  ("stf", "Startup Fund", false, false, false),
  ("stu", "Studded Leather", true, false, false),
  ("swb", "Short War Bow", false, true, false),
  ("t01", "Apprentice", false, false, false),
  ("t02", "Foundation", false, false, false),
  ("t03", "Golden Core", false, false, false),
  ("tal", "Tail", false, false, false),
  ("tax", "Throwing Axe", false, true, false),
  ("tbk", "Tome of Town Portal", false, false, false),
  ("tbl", "Heavy Belt", true, false, false),
  ("tbt", "Light Plated Boots", true, false, false),
  ("tch", "Torch", false, false, false),
  ("tes", "Twisted Essence of Suffering", false, false, false),
  ("tgl", "Light Gauntlets", true, false, false),
  ("tkf", "Throwing Knife", false, true, false),
  ("toa", "Token of Absolution", false, false, false),
  ("tow", "Tower Shield", true, false, true),
  ("tr1", "Horadric Scroll", false, false, false),
  ("tr2", "Scroll of Resistance", false, false, false),
  ("tri", "Trident", false, true, false),
  ("tsc", "Scroll of Town Portal", false, false, false),
  ("tsp", "Throwing Spear", false, true, false),
  ("ua1", "Uber Ancient Summon Material Act 1", false, false, false),
  ("ua2", "Uber Ancient Summon Material Act 2", false, false, false),
  ("ua3", "Uber Ancient Summon Material Act 3", false, false, false),
  ("ua4", "Uber Ancient Summon Material Act 4", false, false, false),
  ("ua5", "Uber Ancient Summon Material Act5", false, false, false),
  ("uap", "Shako", true, false, false),
  ("uar", "Sacred Armor", true, false, false),
  ("ucl", "Loricated Mail", true, false, false),
  ("uea", "Wyrmhide", true, false, false),
  ("uh9", "Bone Visage", true, false, false),
  ("uhb", "Myrmidon Greaves", true, false, false),
  ("uhc", "Colossus Girdle", true, false, false),
  ("uhg", "Ogre Gauntlets", true, false, false),
  ("uhl", "Giant Conch", true, false, false),
  ("uhm", "Spired Helm", true, false, false),
  ("uhn", "Boneweave", true, false, false),
  ("ui0", "Overview Guide", false, false, false),
  ("ui1", "Growth Guide", false, false, false),
  ("ui2", "Dungeon Guide", false, false, false),
  ("uit", "Monarch", true, false, true),
  ("ukp", "Hydraskull", true, false, false),
  ("ula", "Scarab Husk", true, false, false),
  ("ulb", "Wyrmhide Boots", true, false, false),
  ("ulc", "Spiderweb Sash", true, false, false),
  ("uld", "Kraken Shell", true, false, false),
  ("ulg", "Bramble Mitts", true, false, false),
  ("ulm", "Armet", true, false, false),
  ("ult", "Hellforge Plate", true, false, false),
  ("um1", "Uber Ancient Upgrade Material  Fire", false, false, false),
  ("um2", "Uber Ancient Upgrade Material Poison", false, false, false),
  ("um3", "Uber Ancient Upgrade Material  Cold", false, false, false),
  ("um4", "Uber Ancient Upgrade Material Physical", false, false, false),
  ("um5", "Uber Ancient Upgrade Material Lightning", false, false, false),
  ("um6", "Uber Ancient Upgrade Material Magic", false, false, false),
  ("umb", "Boneweave Boots", true, false, false),
  ("umc", "Mithril Coil", true, false, false),
  ("umg", "Vambraces", true, false, false),
  ("uml", "Luna", true, false, true),
  ("ung", "Diamond Mail", true, false, false),
  ("uow", "Aegis", true, false, true),
  ("upk", "Blade Barrier", true, false, true),
  ("upl", "Balrog Skin", true, false, false),
  ("urg", "Hyperion", true, false, true),
  ("urn", "Corona", true, false, false),
  ("urs", "Great Hauberk", true, false, false),
  ("ush", "Troll Nest", true, false, true),
  ("usk", "Demonhead", true, false, false),
  ("utb", "Mirrored Boots", true, false, false),
  ("utc", "Troll Belt", true, false, false),
  ("utg", "Crusader Gauntlets", true, false, false),
  ("uth", "Lacquered Plate", true, false, false),
  ("utp", "Archon Plate", true, false, false),
  ("uts", "Ward", true, false, true),
  ("utu", "Wire Fleece", true, false, false),
  ("uuc", "Heater", true, false, true),
  ("uui", "Dusk Shroud", true, false, false),
  ("uul", "Shadow Plate", true, false, false),
  ("uvb", "Scarabshell Boots", true, false, false),
  ("uvc", "Vampirefang Belt", true, false, false),
  ("uvg", "Vampirebone Gloves", true, false, false),
  ("vbl", "Light Belt", true, false, false),
  ("vbt", "Heavy Boots", true, false, false),
  ("vgl", "Heavy Gloves", true, false, false),
  ("vip", "Amulet of the Viper", false, false, false),
  ("vou", "Voulge", false, true, false),
  ("vps", "Stamina Potion", false, false, false),
  ("wa1", "Old Book", false, false, true),
  ("wa2", "Tome", false, false, true),
  ("wa3", "Codex", false, false, true),
  ("wa4", "Compendium", false, false, true),
  ("wa5", "Grimoire", false, false, true),
  ("wa6", "Burnt Text", false, false, true),
  ("wa7", "Dark Tome", false, false, true),
  ("wa8", "Dark Codex", false, false, true),
  ("wa9", "Possessed Compendium", false, false, true),
  ("waa", "Possessed Grimoire", false, false, true),
  ("wab", "Forgotten Volume", false, false, true),
  ("wac", "Occult Tome", false, false, true),
  ("wad", "Occult Codex", false, false, true),
  ("wae", "Blasphemous Compendium", false, false, true),
  ("waf", "Blasphemous Grimoire", false, false, true),
  ("wax", "War Axe", false, true, false),
  ("whm", "War Hammer", false, true, false),
  ("wms", "Thawing Potion", false, false, false),
  ("wnd", "Wand", false, true, false),
  ("wrb", "Wrist Blade", false, true, false),
  ("wsc", "War Scythe", false, true, false),
  ("wsd", "War Sword", false, true, false),
  ("wsp", "War Scepter", false, true, false),
  ("wst", "War Staff", false, true, false),
  ("xa1", "Western Worldstone Shard", false, false, false),
  ("xa2", "Eastern Worldstone Shard", false, false, false),
  ("xa3", "Southern Worldstone Shard", false, false, false),
  ("xa4", "Deep Worldstone Shard", false, false, false),
  ("xa5", "Northern Worldstone Shard", false, false, false),
  ("xap", "War Hat", true, false, false),
  ("xar", "Ornate Armor", true, false, false),
  ("xcl", "Tigulated Mail", true, false, false),
  ("xea", "Serpentskin Armor", true, false, false),
  ("xf1", "Immortal Rune (10)", false, false, false),
  ("xfu", "Immortal Rune", false, false, false),
  ("xh9", "Grim Helm", true, false, false),
  ("xhb", "War Boots", true, false, false),
  ("xhg", "War Gauntlets", true, false, false),
  ("xhl", "Basinet", true, false, false),
  ("xhm", "Winged Helm", true, false, false),
  ("xhn", "Mesh Armor", true, false, false),
  ("xit", "Dragon Shield", true, false, true),
  ("xkp", "Sallet", true, false, false),
  ("xla", "Demonhide Armor", true, false, false),
  ("xlb", "Demonhide Boots", true, false, false),
  ("xld", "Sharktooth Armor", true, false, false),
  ("xlg", "Demonhide Gloves", true, false, false),
  ("xlm", "Casque", true, false, false),
  ("xlt", "Templar Coat", true, false, false),
  ("xmb", "Mesh Boots", true, false, false),
  ("xmd", "Sumeru Pouch", false, false, false),
  ("xmg", "Heavy Bracers", true, false, false),
  ("xml", "Round Shield", true, false, true),
  ("xng", "Linked Mail", true, false, false),
  ("xow", "Pavise", true, false, true),
  ("xpk", "Barbed Shield", true, false, true),
  ("xpl", "Russet Armor", true, false, false),
  ("xrg", "Scutum", true, false, true),
  ("xrn", "Grand Crown", true, false, false),
  ("xrs", "Cuirass", true, false, false),
  ("xsh", "Grim Shield", true, false, true),
  ("xsk", "Death Mask", true, false, false),
  ("xtb", "Battle Boots", true, false, false),
  ("xtg", "Battle Gauntlets", true, false, false),
  ("xth", "Embossed Plate", true, false, false),
  ("xtp", "Mage Plate", true, false, false),
  ("xts", "Ancient Shield", true, false, true),
  ("xtu", "Trellised Armor", true, false, false),
  ("xuc", "Defender", true, false, true),
  ("xui", "Ghost Armor", true, false, false),
  ("xuj", "Sumeru Pouch - Unique", false, false, false),
  ("xul", "Chaos Armor", true, false, false),
  ("xvb", "Sharkskin Boots", true, false, false),
  ("xvg", "Sharkskin Gloves", true, false, false),
  ("xyz", "Potion of Life", false, false, false),
  ("yps", "Antidote Potion", false, false, false),
  ("ywn", "Yew Wand", false, true, false),
  ("zhb", "War Belt", true, false, false),
  ("zlb", "Demonhide Sash", true, false, false),
  ("zmb", "Mesh Belt", true, false, false),
  ("ztb", "Battle Belt", true, false, false),
  ("zvb", "Sharkskin Belt", true, false, false),
];
// Total: 819 items (691 vanilla + 128 mod)

/// Mod-added item codes (auto-generated, not in vanilla D2R 3.2-92777)
/// Generated by comparing base/ vs mod/ TXT files
pub const MOD_ITEM_CODES: &[&str] = &[
  "a01",
  "a05",
  "a10",
  "a15",
  "a20",
  "a25",
  "a30",
  "atc",
  "cll",
  "cly",
  "cs2",
  "d01",
  "d05",
  "d10",
  "d15",
  "d20",
  "d25",
  "d30",
  "def",
  "ftb",
  "ftt",
  "ftu",
  "ftw",
  "jl1",
  "jlf",
  "lac",
  "lag",
  "lbd",
  "lcb",
  "lck",
  "lcr",
  "ld1",
  "ldc",
  "ldf",
  "lem",
  "lfb",
  "lfs",
  "lft",
  "lfu",
  "lfw",
  "lgc",
  "lgp",
  "lgs",
  "lgx",
  "lgy",
  "lgz",
  "lhc",
  "lhr",
  "li1",
  "lin",
  "lji",
  "ljs",
  "lka",
  "lkd",
  "lkg",
  "lkh",
  "lkm",
  "lks",
  "lkt",
  "lmc",
  "lmf",
  "lmn",
  "lmp",
  "lpn",
  "lqd",
  "lre",
  "lri",
  "ls1",
  "ls2",
  "lsc",
  "lsh",
  "lsk",
  "lsw",
  "ltc",
  "lud",
  "lvp",
  "lvs",
  "lwf",
  "lyd",
  "lzb",
  "m01",
  "m05",
  "m10",
  "m15",
  "m20",
  "m25",
  "m30",
  "mag",
  "mfp",
  "nl1",
  "nls",
  "pc1",
  "pc2",
  "pc3",
  "pc4",
  "pc5",
  "qlf",
  "rh1",
  "rh2",
  "rh3",
  "rh4",
  "rh5",
  "rh6",
  "rl1",
  "rly",
  "rm1",
  "rm2",
  "rm3",
  "rm4",
  "rm5",
  "rm6",
  "rp1",
  "rp2",
  "rp3",
  "rp4",
  "rp5",
  "rp6",
  "stf",
  "t01",
  "t02",
  "t03",
  "ui0",
  "ui1",
  "ui2",
  "xf1",
  "xfu",
  "xmd",
  "xuj",
];
// Total: 128 mod items
