/// Set item definitions (auto-generated from setitems.txt)
/// Format: (id, name, set_name, base_code, level, level_req)
#[rustfmt::skip]
pub const SET_ITEMS: &[(u16, &str, &str, &str, u8, u8)] = &[
  (0, "Large Shield", "Civerb's Vestments", "lrg", 13, 9),
  (1, "Amulet", "Civerb's Vestments", "amu", 13, 9),
  (2, "Grand Scepter", "Civerb's Vestments", "gsc", 13, 9),
  (3, "Chain Boots", "Hsarus' Defense", "mbt", 4, 3),
  (4, "Buckler", "Hsarus' Defense", "buc", 4, 3),
  (5, "Belt", "Hsarus' Defense", "mbl", 4, 3),
  (6, "Long Sword", "Cleglaw's Brace", "lsd", 6, 4),
  (7, "Small Shield", "Cleglaw's Brace", "sml", 6, 4),
  (8, "Chain Gloves", "Cleglaw's Brace", "mgl", 6, 4),
  (9, "Amulet", "Iratha's Finery", "amu", 21, 15),
  (10, "Light Gauntlets", "Iratha's Finery", "tgl", 21, 15),
  (11, "Crown", "Iratha's Finery", "crn", 21, 15),
  (12, "Heavy Belt", "Iratha's Finery", "tbl", 21, 15),
  (13, "Broad Sword", "Isenhart's Armory", "bsd", 11, 8),
  (14, "Gothic Shield", "Isenhart's Armory", "gts", 11, 8),
  (15, "Breast Plate", "Isenhart's Armory", "brs", 11, 8),
  (16, "Full Helm", "Isenhart's Armory", "fhl", 11, 8),
  (17, "Long Battle Bow", "Vidala's Rig", "lbb", 19, 14),
  (18, "Light Plated Boots", "Vidala's Rig", "tbt", 19, 14),
  (19, "Leather Armor", "Vidala's Rig", "lea", 19, 14),
  (20, "Amulet", "Vidala's Rig", "amu", 19, 14),
  (21, "Kite Shield", "Milabrega's Regalia", "kit", 23, 17),
  (22, "War Scepter", "Milabrega's Regalia", "wsp", 23, 17),
  (23, "Crown", "Milabrega's Regalia", "crn", 23, 17),
  (24, "Ancient Armor", "Milabrega's Regalia", "aar", 23, 17),
  (25, "Battle Staff", "Cathan's Traps", "bst", 15, 11),
  (26, "Chain Mail", "Cathan's Traps", "chn", 15, 11),
  (27, "Mask", "Cathan's Traps", "msk", 15, 11),
  (28, "Amulet", "Cathan's Traps", "amu", 15, 11),
  (29, "Ring", "Cathan's Traps", "rin", 15, 11),
  (30, "Military Pick", "Tancred's Battlegear", "mpi", 27, 20),
  (31, "Full Plate Mail", "Tancred's Battlegear", "ful", 27, 20),
  (32, "Boots", "Tancred's Battlegear", "lbt", 27, 20),
  (33, "Amulet", "Tancred's Battlegear", "amu", 27, 20),
  (34, "Bone Helm", "Tancred's Battlegear", "bhm", 27, 20),
  (35, "Gauntlets", "Sigon's Complete Steel", "hgl", 9, 6),
  (36, "Great Helm", "Sigon's Complete Steel", "ghm", 9, 6),
  (37, "Gothic Plate", "Sigon's Complete Steel", "gth", 9, 6),
  (38, "Greaves", "Sigon's Complete Steel", "hbt", 9, 6),
  (39, "Plated Belt", "Sigon's Complete Steel", "hbl", 9, 6),
  (40, "Tower Shield", "Sigon's Complete Steel", "tow", 9, 6),
  (41, "Cap", "Infernal Tools", "cap", 7, 5),
  (42, "Grim Wand", "Infernal Tools", "gwn", 7, 5),
  (43, "Heavy Belt", "Infernal Tools", "tbl", 7, 5),
  (44, "Helm", "Berserker's Garb", "hlm", 5, 3),
  (45, "Splint Mail", "Berserker's Garb", "spl", 5, 3),
  (46, "Double Axe", "Berserker's Garb", "2ax", 5, 3),
  (47, "Leather Gloves", "Death's Disguise", "lgl", 8, 6),
  (48, "Sash", "Death's Disguise", "lbl", 8, 6),
  (49, "War Sword", "Death's Disguise", "wsd", 8, 6),
  (50, "Sabre", "Angelical Raiment", "sbr", 17, 12),
  (51, "Ring Mail", "Angelical Raiment", "rng", 17, 12),
  (52, "Ring", "Angelical Raiment", "rin", 17, 12),
  (53, "Amulet", "Angelical Raiment", "amu", 17, 12),
  (54, "Short War Bow", "Arctic Gear", "swb", 3, 2),
  (55, "Quilted Armor", "Arctic Gear", "qui", 3, 2),
  (56, "Light Belt", "Arctic Gear", "vbl", 3, 2),
  (57, "Light Gauntlets", "Arctic Gear", "tgl", 3, 2),
  (58, "Amulet", "Arcanna's Tricks", "amu", 20, 15),
  (59, "War Staff", "Arcanna's Tricks", "wst", 20, 15),
  (60, "Skull Cap", "Arcanna's Tricks", "skp", 20, 15),
  (61, "Light Plate", "Arcanna's Tricks", "ltp", 20, 15),
  (62, "Grim Helm", "Natalya's Odium", "xh9", 22, 59),
  (63, "Scissors Suwayyah", "Natalya's Odium", "7qr", 22, 79),
  (64, "Loricated Mail", "Natalya's Odium", "ucl", 22, 73),
  (65, "Mesh Boots", "Natalya's Odium", "xmb", 22, 25),
  (66, "Hunter's Guise", "Aldur's Watchtower", "dr8", 29, 36),
  (67, "Shadow Plate", "Aldur's Watchtower", "uul", 29, 76),
  (68, "Jagged Star", "Aldur's Watchtower", "9mt", 29, 42),
  (69, "Battle Boots", "Aldur's Watchtower", "xtb", 29, 45),
  (70, "Avenger Guard", "Immortal King", "ba5", 37, 47),
  (71, "Sacred Armor", "Immortal King", "uar", 37, 76),
  (72, "War Belt", "Immortal King", "zhb", 37, 29),
  (73, "War Gauntlets", "Immortal King", "xhg", 37, 30),
  (74, "War Boots", "Immortal King", "xhb", 37, 31),
  (75, "Ogre Maul", "Immortal King", "7m7", 37, 76),
  (76, "Mesh Belt", "Tal Rasha's Wrappings", "zmb", 26, 53),
  (77, "Amulet", "Tal Rasha's Wrappings", "amu", 26, 67),
  (78, "Swirling Crystal", "Tal Rasha's Wrappings", "oba", 26, 65),
  (79, "Lacquered Plate", "Tal Rasha's Wrappings", "uth", 26, 71),
  (80, "Death Mask", "Tal Rasha's Wrappings", "xsk", 26, 66),
  (81, "Corona", "Griswold's Legacy", "urn", 44, 69),
  (82, "Ornate Plate", "Griswold's Legacy", "xar", 44, 45),
  (83, "Caduceus", "Griswold's Legacy", "7ws", 44, 53),
  (84, "Vortex Shield", "Griswold's Legacy", "paf", 44, 68),
  (85, "Bone Visage", "Trang-Oul's Avatar", "uh9", 32, 65),
  (86, "Chaos Armor", "Trang-Oul's Avatar", "xul", 32, 49),
  (87, "Cantor Trophy", "Trang-Oul's Avatar", "ne9", 32, 54),
  (88, "Heavy Bracers", "Trang-Oul's Avatar", "xmg", 32, 45),
  (89, "Troll Belt", "Trang-Oul's Avatar", "utc", 32, 47),
  (90, "Diadem", "M'avina's Battle Hymn", "ci3", 21, 59),
  (91, "Kraken Shell", "M'avina's Battle Hymn", "uld", 21, 70),
  (92, "Battle Gauntlets", "M'avina's Battle Hymn", "xtg", 21, 32),
  (93, "Sharkskin Belt", "M'avina's Battle Hymn", "zvb", 21, 45),
  (94, "Grand Matron Bow", "M'avina's Battle Hymn", "amc", 21, 70),
  (95, "Amulet", "The Disciple", "amu", 39, 30),
  (96, "Bramble Mitts", "The Disciple", "ulg", 39, 63),
  (97, "Demonhide Boots", "The Disciple", "xlb", 39, 29),
  (98, "Dusk Shroud", "The Disciple", "uui", 39, 43),
  (99, "Mithril Coil", "The Disciple", "umc", 39, 65),
  (100, "Reinforced Mace", "Heaven's Brethren", "7ma", 55, 68),
  (101, "Ward", "Heaven's Brethren", "uts", 55, 81),
  (102, "Cuirass", "Heaven's Brethren", "xrs", 55, 44),
  (103, "Spired Helm", "Heaven's Brethren", "uhm", 55, 69),
  (104, "Winged Helm", "Orphan's Call", "xhm", 41, 34),
  (105, "Battle Belt", "Orphan's Call", "ztb", 41, 42),
  (106, "Sharkskin Gloves", "Orphan's Call", "xvg", 41, 37),
  (107, "Round Shield", "Orphan's Call", "xml", 41, 29),
  (108, "Grand Crown", "Hwanin's Majesty", "xrn", 28, 45),
  (109, "Tigulated Mail", "Hwanin's Majesty", "xcl", 28, 30),
  (110, "Belt", "Hwanin's Majesty", "mbl", 28, 35),
  (111, "Bill", "Hwanin's Majesty", "9vo", 28, 28),
  (112, "Cryptic Sword", "Sazabi's Grand Tribute", "7ls", 34, 73),
  (113, "Balrog Skin", "Sazabi's Grand Tribute", "upl", 34, 67),
  (114, "Basinet", "Sazabi's Grand Tribute", "xhl", 34, 43),
  (115, "Colossus Blade", "Bul-Kathos' Children", "7gd", 50, 61),
  (116, "Mythical Sword", "Bul-Kathos' Children", "7wd", 50, 54),
  (117, "War Hat", "Cow King's Leathers", "xap", 20, 25),
  (118, "Studded Leather", "Cow King's Leathers", "stu", 20, 18),
  (119, "Heavy Boots", "Cow King's Leathers", "vbt", 20, 13),
  (120, "Elder Staff", "Naj's Ancient Set", "6cs", 43, 78),
  (121, "Hellforge Plate", "Naj's Ancient Set", "ult", 43, 71),
  (122, "Circlet", "Naj's Ancient Set", "ci0", 43, 28),
  (123, "Cap", "McAuley's Folly", "cap", 20, 25),
  (124, "Heavy Boots", "McAuley's Folly", "vbt", 20, 20),
  (125, "Heavy Gloves", "McAuley's Folly", "vgl", 20, 28),
  (126, "Bone Wand", "McAuley's Folly", "bwn", 20, 25),
  (127, "Gauntlets", "Warlord's Glory", "hgl", 100, 1),
  (128, "Great Helm", "Warlord's Glory", "ghm", 100, 1),
  (129, "Full Plate Mail", "Warlord's Glory", "ful", 100, 1),
  (130, "Greaves", "Warlord's Glory", "hbt", 100, 1),
  (131, "Plated Belt", "Warlord's Glory", "hbl", 100, 1),
  (132, "Kriss", "Bane's Garments", "kri", 7, 8),
  (133, "Hard Leather Armor", "Bane's Garments", "hla", 7, 8),
  (134, "Light Belt", "Bane's Garments", "vbl", 7, 8),
  (135, "Demonhead", "Horazon's Splendor", "usk", 40, 62),
  (136, "Russet Armor", "Horazon's Splendor", "xpl", 40, 55),
  (137, "Demonhide Gloves", "Horazon's Splendor", "xlg", 40, 48),
  (138, "Mirrored Boots", "Horazon's Splendor", "utb", 40, 67),
  (139, "Occult Codex", "Horazon's Splendor", "wad", 40, 57),
  (140, "Crystal Sword", "Frost Prison", "ftw", 26, 56),
  (141, "Lacquered Plate", "Frost Prison", "ftu", 26, 56),
  (142, "Mesh Belt", "Frost Prison", "ftb", 26, 56),
  (143, "War Boots", "Frost Prison", "ftt", 26, 56),
  (144, "Crystal Sword", "Lightning Prison", "lfw", 26, 56),
  (145, "Lacquered Plate", "Lightning Prison", "lfu", 26, 56),
  (146, "Mesh Belt", "Lightning Prison", "lfb", 26, 56),
  (147, "War Boots", "Lightning Prison", "lft", 26, 56),
];

pub fn lookup_set_item(id: u16) -> Option<(&'static str, &'static str, &'static str)> {
    SET_ITEMS
        .iter()
        .find(|entry| entry.0 == id)
        .map(|entry| (entry.1, entry.2, entry.3))
}
// Total: 148 set items

/// Set bonus definitions (auto-generated from sets.txt)
/// Format: (name)
#[rustfmt::skip]
pub const SET_BONUSES: &[&str] = &[
  ("Civerb's Vestments"),
  ("Hsarus' Defense"),
  ("Cleglaw's Brace"),
  ("Iratha's Finery"),
  ("Isenhart's Armory"),
  ("Vidala's Rig"),
  ("Milabrega's Regalia"),
  ("Cathan's Traps"),
  ("Tancred's Battlegear"),
  ("Sigon's Complete Steel"),
  ("Infernal Tools"),
  ("Berserker's Garb"),
  ("Death's Disguise"),
  ("Angelical Raiment"),
  ("Arctic Gear"),
  ("Arcanna's Tricks"),
  ("Natalya's Odium"),
  ("Aldur's Watchtower"),
  ("Immortal King"),
  ("Tal Rasha's Wrappings"),
  ("Griswold's Legacy"),
  ("Trang-Oul's Avatar"),
  ("M'avina's Battle Hymn"),
  ("The Disciple"),
  ("Heaven's Brethren"),
  ("Orphan's Call"),
  ("Hwanin's Majesty"),
  ("Sazabi's Grand Tribute"),
  ("Bul-Kathos' Children"),
  ("Cow King's Leathers"),
  ("Naj's Ancient Set"),
  ("McAuley's Folly"),
  ("Warlord's Glory"),
  ("Bane's Garments"),
  ("Horazon's Splendor"),
];
// Total: 35 set bonuses
