#!/usr/bin/env python3
"""
Regenerate auto-generated data tables for D2R Marketplace.

Usage:
    python tools/regen_data_tables.py

Reads from:
    extracted_data/itemstatcost.json       → src-tauri/src/data/python_stats.rs
    extracted_data/d2core/magic_prefix.json → src-tauri/src/data/affix_names.rs
    extracted_data/d2core/magic_suffix.json → (appended)

Output:
    Overwrites the auto-gen files in src-tauri/src/data/
"""

import json
import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EXTRACTED = REPO_ROOT / "extracted_data"
OUT_DIR = REPO_ROOT / "src-tauri" / "src" / "data"


def regen_python_stats():
    """Regenerate python_stats.rs from itemstatcost.json."""
    src = EXTRACTED / "itemstatcost.json"
    if not src.exists():
        print(f"[SKIP] {src} not found")
        return False

    with open(src, encoding="utf-8") as f:
        data = json.load(f)

    rows = data["rows"]
    stat_map = {}
    for row in rows:
        sid = row.get("*ID", "")
        if not sid:
            continue
        sid_i = int(sid)
        save_bits = int(row.get("Save Bits", 0) or 0)
        save_add = int(row.get("Save Add", 0) or 0)
        save_param_bits = int(row.get("Save Param Bits", 0) or 0)
        stat_map[sid_i] = (save_bits, save_param_bits, save_add)

    ids = sorted(stat_map.keys())
    lines = [
        "//! Python jm_parser.py 的 stat 数据表 — 直接从 itemstatcost.txt 的 Save Bits / Save Add / Save Param Bits / NP 生成。",
        "//! 用于 `items_new::parse_stat_stream`，确保 Rust 的 stat stream 解析与 Python 完全一致。",
        "//!",
        "//! Auto-regenerated by tools/regen_data_tables.py",
        "",
        "use std::collections::HashSet;",
        "",
        "/// Python _STAT_ALL_IDS: itemstatcost.txt 中有行的所有 stat ID。",
        "/// 包括 save_bits=0 的 stat —— 只要在文件里就算\"已知\"，读默认 9 bits。",
        "pub fn known_stat_ids() -> HashSet<u16> {",
        "    static IDS: &[u16] = &[",
    ]
    # known_stat_ids — 20 per line
    for i in range(0, len(ids), 20):
        chunk = ids[i:i+20]
        lines.append("        " + ",".join(str(s) for s in chunk) + ",")
    lines.extend([
        "    ];",
        "    let mut s = HashSet::new();",
        "    for &id in IDS { s.insert(id); }",
        "    s",
        "}",
        "",
        "/// Save bits for each stat — from ItemStatCost.txt col 'Save Bits'.",
        "pub fn stat_bits(sid: u16) -> usize {",
        "    match sid {",
    ])
    for sid in ids:
        bits = stat_map[sid][0]
        lines.append(f"        {sid} => {bits},")
    lines.extend([
        "        _ => 9,",
        "    }",
        "}",
        "",
        "/// Save add offset — from ItemStatCost.txt col 'Save Add'.",
        "pub fn stat_save_add(sid: u16) -> i32 {",
        "    match sid {",
    ])
    for sid in ids:
        add = stat_map[sid][2]
        lines.append(f"        {sid} => {add},")
    lines.extend([
        "        _ => 0,",
        "    }",
        "}",
        "",
        "/// Save param bits — from ItemStatCost.txt col 'Save Param Bits'.",
        "pub fn stat_param_bits(sid: u16) -> usize {",
        "    match sid {",
    ])
    for sid in ids:
        bits = stat_map[sid][1]
        lines.append(f"        {sid} => {bits},")
    lines.extend([
        "        _ => 0,",
        "    }",
        "}",
        "",
        "/// D2R sub-property overrides (Python _STAT_NP).",
        "/// Hand-crafted — not from ItemStatCost.txt.",
        "pub fn stat_np(sid: u16) -> u8 {",
        "    match sid {",
        "        17 | 48 | 50 | 52 => 2,",
        "        54 | 57 => 3,",
        "        _ => 1,",
        "    }",
        "}",
    ])

    out = OUT_DIR / "python_stats.rs"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[OK] Regenerated python_stats.rs ({len(ids)} stats, {len(lines)} lines)")
    return True


def regen_affix_names():
    """Regenerate affix_names.rs from magic_prefix.json + magic_suffix.json."""
    pref_src = EXTRACTED / "d2core" / "magic_prefix.json"
    suff_src = EXTRACTED / "d2core" / "magic_suffix.json"

    if not pref_src.exists() or not suff_src.exists():
        print(f"[SKIP] {pref_src} or {suff_src} not found")
        return False

    with open(pref_src, encoding="utf-8") as f:
        prefixes = json.load(f)
    with open(suff_src, encoding="utf-8") as f:
        suffixes = json.load(f)

    lines = [
        "// Auto-generated by tools/regen_data_tables.py from magic_prefix.json + magic_suffix.json",
        "// DO NOT EDIT MANUALLY — run `python tools/regen_data_tables.py` to regenerate.",
        "#[rustfmt::skip]",
        "pub const MAGIC_PREFIX_NAMES: &[(u16, &str)] = &[",
    ]

    for idx, p in enumerate(prefixes, start=1):
        name = p.get("name", "").replace("\\", "\\\\").replace('"', '\\"')
        if name:
            lines.append(f'  ({idx}, "{name}"),')

    lines.extend([
        "];",
        "",
        "#[rustfmt::skip]",
        "pub const MAGIC_SUFFIX_NAMES: &[(u16, &str)] = &[",
    ])

    for idx, s in enumerate(suffixes, start=1):
        name = s.get("name", "").replace("\\", "\\\\").replace('"', '\\"')
        if name:
            lines.append(f'  ({idx}, "{name}"),')

    lines.append("];")

    out = OUT_DIR / "affix_names.rs"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[OK] Regenerated affix_names.rs ({len(prefixes)} prefixes, {len(suffixes)} suffixes, {len(lines)} lines)")
    return True


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    regen_python_stats()
    regen_affix_names()
    print("\nDone. Run `cargo check` to verify the generated files compile.")


if __name__ == "__main__":
    main()
